### ISSUE TITLE
selectmenu width without CSS width

### ISSUE THREAD

**Issue by mmukhin** [fnagel/jquery-ui#100]
is anyone else having a problem with firefox4 and the 'selectmenu' widget? 

all browsers work beautifully, but in firefox4, the width of the select is always ~1/2 of the normal value (value in all other browsers: chrome, safari, firefox 3), when set the width is not set (so generated manually based on width of  the biggest <option> im guessing)

thanks in advance!!

**Comment by fnagel** [comment]
Im not able to reproduce this issue. Please post a demo zip or use this: https://github.com/fnagel/jquery-ui/issues/61

Did you try one of the width options like width or menuWidth? See https://github.com/fnagel/jquery-ui/wiki/Selectmenu

**Comment by mmukhin** [comment]
The original problem was on an iMac, I checked on Windows, looks good. When I get a chance, I will replicate the problem. Thanks.

**Comment by fnagel** [comment]
Uhhh I not able to test with a Mac at home but I frequently check the selectmenu widget when using it at work and I experienced no problems so far. If you able to help out here I would be thankful.

**Comment by mmukhin** [comment]
Hey, heres a screen capture, please notice the width of the anchor element in the html. Let me know if there's anything else I can provide.

iMac OSX, chrome 10 on left, firefox 4 on right

http://oi54.tinypic.com/2m4q78x.jpg

**Comment by lephyrius** [comment]
I don't know if this helps but I have created a jsFiddle for the problem:
http://jsfiddle.net/e9wMg/
This doesn't work on FIrefox 4 mac os x 10.6.6 it only gives me a half width selectmenu. But I have also a problem with google chrome on OS X but have not been able to recreate it in jsFiddle.

**Comment by lephyrius** [comment]
Ahh!
I have discovered that this jsFiddle.
http://jsfiddle.net/CSgqB/

All browsers running on Mac OS X 10.6.6 :

Firefox 4: displays half the width.
Chrome  10.0.648 : Has bad position on the arrow pointing downward.
Safari 5.0.4 : Has bad position on the arrow pointing downward inside the text.
Opera 11.10 : Has position of the arrow inside the text.

Hope this helps!

**Comment by corydodt** [comment]
I can reproduce this in my own code--FF4/Ubuntu64: half width.  Chromium/Ubuntu64: full width.

However, with the above jsfiddle posted by lephyrius, BOTH browsers are half-width, no difference.

**Comment by fnagel** [comment]
Sorry about the long waiting time, but I had an surgery and was not able to work on the selectmenu widget the last few weeks. I will take a look asap, please be patient!

**Comment by fnagel** [comment]
@mmukhin
Thnaks for the screenshot.

@lephyrius 
In your first fiddle Im not able to see any width because there are missing style sheets.
Second fiddle works so far, but there is no width for original selectmenu defined. So the selectmenu widget has some browser default width. 

Please always (!) define a width for the original selctemenu (see http://jsfiddle.net/CSgqB/2/) or use the width option (see http://jsfiddle.net/CSgqB/3/)

Does this solve your problem?

**Comment by lephyrius** [comment]
@fnagel
Yes it solves my problem but should not the default behavior be to have an auto width like normal selectmenus on Windows and OS X. The minimum width in order to display the longest word in the selectmenu list and the down pointing arrow.

**Comment by fnagel** [comment]
I did some research and the width is already set. I improved the JS algorithm a little but this is not only solvable by scripting. Please note that you properly need to adjust the CSS (mainly padding of the lis) and the handleWidth value. Another solution is to change the option style to dropdown.

**Comment by Filirom1** [comment]
The width specified in the select CSS, is not the width of the select menu.
http://jsfiddle.net/suxM4/

But in jquery.ui.selectmenu.js

If you replace (line 166 and 363)

```
 // original selectmenu width
```

--   var selectWidth = this.element.width();
++ var selectWidth = this.element.outerWidth();

It works

**Comment by fnagel** [comment]
@Filirom1
Did you test this with the latest commit? It seems you did test with a
version before the above mentioned patch applied as we already using
outerWidth()

**Comment by Filirom1** [comment]
Yes you're right, it works well with the last commit.

Sorry for not having checked.

**Comment by fnagel** [comment]
@Filirom1
No problem :-)

@mmukhin
@lephyrius
@Filirom1
@corydodt
So is this issue fixed for you? Please give feedback!

**Comment by Filirom1** [comment]
For me, this issue is fixed.

**Comment by lephyrius** [comment]
No, not for me.
Overall it gives me only a more consistant error.(it looks the same on all the browsers I test)
So this works: var selectWidth = this.element.outerWidth()+32;
But it feels kind of a hacky approach to the problem. Is there maybe a way to get the width of the arrow and just add that to the width?

**Comment by fnagel** [comment]
@lephyrius
Demo please. The width of the arrow is set by using option handleWidth.

**Comment by lephyrius** [comment]
I tested in Mac OS X 10.6.6 and Google Chrome 11 and Firefox 4.
Yes here is the demo:
First the case where it fails:
http://jsfiddle.net/Gg5tm/2/
As you can see I got short 4 letter words.
Where it works:
http://jsfiddle.net/Gg5tm/4/
This is why you won't see the error easily. Because you didn't use small 4 letter words.
Looks like 8 letters is minimum for it to work perfectly:
http://jsfiddle.net/Gg5tm/5/

Hope this helps!

**Comment by fnagel** [comment]
You need to adjust the CSS: padding and or width of the original select. I will not patch every possible use case with massive font-size and tiny values.

See here what to do: http://jsfiddle.net/Gg5tm/6/

**Comment by mmukhin** [comment]
@fnagel

Looks great! Thank you.

**Comment by fnagel** [comment]
Seems to be fixed, please reopen if necessary.
