### ISSUE TITLE
Options with a blank value show up with li smaller than other options

### ISSUE THREAD

**Issue by mjost5v** [fnagel/jquery-ui#102]
Steps to recreate:
1. Create a dropdown with an empty option like so:
select
option /option
option value="A" A /option
/select
1. The jquery-ui selectmenu li for the first option will appear smaller than the second.

I was able to resolve this issue by storing the text of the option (stored in selectOptionData[i].text) in a variable in the for loop on line 260. I then tested the length of the variable, if it was 0, I overwrote the value with '&nbps;'. I then passed the variable where selectOptionData[i].text is used on line 261.

**Comment by fnagel** [comment]
Could this problem be related with this one?
https://github.com/fnagel/jquery-ui/issues/82

**Comment by mjost5v** [comment]
I don't think so. There weren't any issues in the Firebug Console. It 
only occurs when the option has no text.

**Comment by fnagel** [comment]
Sorry for the late response. Plase try to press the "m" key (when not within the textarea) for markup info when you want to post code.

Ive tried this HTML

```
<select>
    <option value=""></option>
</select>
```

and you're right, the li is not fully expanded as there is no value.
Ive tried something like this within the loop, but it failed. The &nbps; is displayed as text.

```
 text: (opt.text().length) ? self._formatText(opt.text()) : '&nbps;',
```

**Comment by outprove** [comment]
I had the same issue and followed mjt5v's advice. This is the relevant code snippet that I modified for other's people reference. (at line 287 in the current version of the js) I'm sure there might be a more elegant way to do it, I'm no javascript jedi.

```
// write li's
    if (selectOptionData.length) {
        for (var i = 0; i < selectOptionData.length; i++) {
            var savedata = selectOptionData[i].text;
            if (savedata.length == 0) savedata = '&nbsp;';

            var thisLiAttr = { role : 'presentation' };
            if ( selectOptionData[ i ].disabled ) {
                thisLiAttr[ 'class' ] = this.namespace + '-state-disabled';
            }                   
            var thisAAttr = {
                //html: selectOptionData[i].text,
                html : savedata,
                href : '#nogo', 
                tabindex : -1, 
                role : 'option',
                'aria-selected' : false
            };
```

**Comment by fnagel** [comment]
Sorry for the late response. I must confess Ive forgot this issue. 

I commited a fix, please test and give feedback!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by outprove** [comment]
Sorry, fix works well. Thanks!
