### ISSUE TITLE
Disabled option performance issues 

### ISSUE THREAD

**Issue by gcko** [fnagel/jquery-ui#104]
Hey; 

I just tried out the new Disabled option code and spent some time working through the provided demos. There is one performance issue I would like to bring to your attention.

This is specific to the disable_enable.html "disabled option by HTML" demo. While arrowing through a selectmenu whose list is open, Trying to arrow past the slow option (disabled) and then arrowing down will cause script errors in all browsers (except possibly chrome due to their robust handling). In any case it causes slow performance. the issue is compounded if you either: a) hold down the arrow key trying to key past the element, or b) press the arrow key repeatedly. 

Since I wrote the original code for this section (which takes care of these issues), I would like to talk about the algorithm which I was using and the issues that are cropping up in the current implementation. 

I will step through the important parts of the implementation

<pre>
            //Occurs when a full loop has been made
            if (newIndex === recIndex) { return false; }
</pre>

This is a line that has been taken out of the current implementation. The algorithm i the push I sent relies on a recursive loop to find the next non-disabled option that the user can select while keying through the list. by taking this line out, you allow the code to enter a recursion loop. this causes the code to fail. Other users were noticing that they would receive the following error:

<pre>
recIndex is not defined on line 601 of selectmenu.js for this line:
</pre>

In the algorithm i pushed, this was defined in the method call 

<pre>
_moveFocus: function(amt, recIndex){
</pre>

and was passed in when the recursion loop was entered:

<pre>
if (this._optionLis.eq(newIndex).hasClass('disabled')) {
                //if option at newIndex is disabled, call _moveFocus, incrementing amt by one
                (amt > 0) ? amt++ : amt--;
                this._moveFocus(amt, newIndex); //newIndex is passed in as the recIndex
            } else {
                this._optionLis.eq(newIndex).find('a:eq(0)').attr('id',activeID).focus();
            }
</pre>

On the first iteration of _moveIndex, it will probably be the case that recIndex is undefined. the proper solution would be to add another condition to the statement:

<pre>
            if (recIndex && newIndex === recIndex) { return false; }
</pre>

This will keep the code from failing.

I have found a few other issues for which I will open a separate bug as they just may be related to doc and not functionality.

**Comment by gcko** [comment]
I would like to add that this is an issue when the disabled option is on a boundry (the first or last in the list), or is part of a series of disabled options that lead up to the boundry (a series of first options or a series of last options in the list). 

I would suggest that you do testing with multiple options disabled and options disabled in different positions (edge cases, first, middle, last).

**Comment by fnagel** [comment]
Sorry about the long waiting time, but I had an surgery and was not able to work on the selectmenu widget the last few weeks. I will take a look asap, please be patient!

**Comment by fnagel** [comment]
First of all thanks for your contribution, this is reall appriciated!

Your first issue should be a problem related to this issue:disabled options: navigate by keyboard (see https://github.com/fnagel/jquery-ui/issues/116). You are about to solve this issue so Ive updated the above mentioned issue.

Im sorry we sacrificed your code. I never really dig into this problem and relied (with some testing) on the feedback of others. Im not quite sure where to add you fix and currently there is no recInded defined anywhere in the script. Would you please show me where to find the original solution and perhaps post the complete modified _moveFocus fuction. 
Thanks for you help and contribution!

**Comment by gcko** [comment]
I'll create another pull request based that includes the _moveFocus function before it got updated.

**Comment by fnagel** [comment]
Great! This is the last issue blocking the v1.1 release.

**Comment by gcko** [comment]
I made a pull request, you can grab it to see the cahnges

**Comment by fnagel** [comment]
Merged (https://github.com/fnagel/jquery-ui/pull/119) and committed. Please give feedback!

**Comment by gcko** [comment]
Seems to be working correctly through my limited testing of the new pull. I'll leave it for you to close
