### ISSUE TITLE
disabled_enabled demos don't perform as stated

### ISSUE THREAD

**Issue by gcko** [fnagel/jquery-ui#105]
Again, thanks for spending the time to work on this code. I want to highlight some issues with the demo I found in Chrome 11 & FF4.0

Demo 1 ( Disabled by select callback (does not change original select) ): the selectmenu does not become disabled after selecting "off"

Demo 2 (Disable whole select): Clicking "off" or "on" has no effect

Demo 3 (Disabled option by HTML): Not actually disabling by html but disabling by callback click of the "on/off" toggle. Also, does not disable the "medium" option as spec'ed but disables "slower"

Demo 4 (disable optGroup): the disabled optGroup options still receive hover state

Demo 5 (disabled by HTM): original select is disabled, but not the selectmenu

**Comment by fnagel** [comment]
Thanks for reporting. My fault, I did not test this enough. This is some kind of a regression bug: https://github.com/fnagel/jquery-ui/pull/93

 I committed a fix, please test and give fedback!

**Comment by fnagel** [comment]
Any feedback on this one, please?

**Comment by gcko** [comment]
I believe I opened new issues related to your fixes..

**Comment by gcko** [comment]
I'll check the latest build and let you know if they have been fixed.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by gcko** [comment]
Hey, just tested again;

The following is still applicable:

Demo 4 (disable optGroup): the disabled optGroup options still receive hover state

**Comment by fnagel** [comment]
Thanks for your feedback. 
Should be fixed in latest commit. Please test and give feedback!

**Comment by fnagel** [comment]
@gcko
Please give feedback!

**Comment by gcko** [comment]
Works great!
