### ISSUE TITLE
Needs installation documentation

### ISSUE THREAD

**Issue by jaylevitt** [fnagel/jquery-ui#107]
It took me a while to figure out that, in addition to jquery.ui.selectmenu.js, I needed to add both jquery-ui.css (which is not included in the package) and jquery.ui.selectmenu.css to my page.  I was trying to add jquery.ui.base.css and/or jquery.ui.core.css (which ARE included in the package) but that's apparently not enough.

**Comment by fnagel** [comment]
All needed files are inlcuded. Just open the demo files found in \demos\selectmenu and see for example default.html.

Please note selectmenu widget is not part of the official jQuery UI widgets and therefore not as perfect as these scripts. Consider selectmenu as stable and ready for productive use but recommended for experienced developers only. Some hints for non jQuery UI users: include a UI CSS file from jqueryui.com and add the jquery.ui.selectmenu.css (see \themes\base)

The selectmenu widget had initially hardly any docu but if you like to write some more notes you're welcome to help me to improve the wiki. Please see here: https://github.com/fnagel/jquery-ui/issues/51

**Comment by fnagel** [comment]
Did my answer solved your problem?
