### ISSUE TITLE
jquery menu, are You going to continue this project?

### ISSUE THREAD

**Issue by lumyslinski** [fnagel/jquery-ui#108]
Hello,
I was wondering if You are still developing this menu - http://www.filamentgroup.com/lab/jquery_ipod_style_and_flyout_menus/ . I'm interested especially in iPod style menu if there is any new version. There is a statement:

Thanks for the helpful feedback!

We're no longer taking comments on this post because we've handed off development of this widget to the jQuery UI development team. The menu is currently being refactored and is slated for an upcoming jQuery UI release. We encourage you to track its progress and continue contributing your ideas at the jQuery UI Development & Planning Wiki.

But jquery wiki doesn't work, hmmm...Regards and thanks in advance for any information!

**Comment by fnagel** [comment]
I never was involved in the development of the above mentioned widget, so I can not give any information about this. Please note Im not part of the filament group but an encouraged user of the selectmenu.

Im able to open the jQuery Wiki, perhaps it was just a temporary problem.
