### ISSUE TITLE
Invalid positioning of selectmenu if <select> is located inside block width overflow: auto

### ISSUE THREAD

**Issue by betalb** [fnagel/jquery-ui#11]
Menu dropdown is attached to document.body if select box have been placed inside a div with fixed height & overflow: auto, dropdown may appear not in the right place

**Comment by fnagel** [comment]
Would you please provide a demo zip?

**Comment by betalb** [comment]
Sorry, it seems that when I was expreimenting with selectmenu I forgot to include css from theme, only the selectmenu stuff
