### ISSUE TITLE
Standalone Version

### ISSUE THREAD

**Issue by gercheq** [fnagel/jquery-ui#110]
Are you planning to implement the standalone jQuery version at some point? jQueryUI is huge and I don't want to include it in my source. Keep up the great work! Thanks.

**Comment by fnagel** [comment]
No. This would be way too much work and Im sure there are other, pretty nice, standalone selectemnu scripts out there.

Please note we are talking about less than 15kb minified "overhead". Optimize one picture on your website to compensate this :-)
