### ISSUE TITLE
Widget enable problem

### ISSUE THREAD

**Issue by trollixx** [fnagel/jquery-ui#113]
I got a strange issue. I fill selectmenu's items after AJAX call accessing its orignal <select>. During this widget is disabled. After filling is done, I want to enable widget. And if I use $('select#my_select').selectmenu('enable') it gets enabled, but doesn't contain any items. Using $('select#my_select').selectmenu({disabled: false}) prevents this bug.

**Comment by fnagel** [comment]
This is no bug, this is normal behavior of any jQuery widget.

Solution: init the widget after injecting the options or update the widget by using $('select#my_select').selectmenu() after injecting the options and before enabling it.

**Comment by trollixx** [comment]
Thanks. Didn't know this.
