### ISSUE TITLE
Disable does not work in certain circumstance

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#12]
This seems to be an bug which needs more investigation. Following code is an example in which the links (#on and #off)  work but the select callback does not. The disable function within the method always calls the enable method of the jQuery UI widget.js. I just don't know why. 

This needs further investigation, but seems to be a UI internal problem. Help is appreciated!

JS
<code>
            var speedB = $('select#speedB').selectmenu();

```
        var speedA = $('select#speedA').selectmenu({
            select: function(event, options) {
                if (options.value) { 
                    speedB.selectmenu('enable');
                } else {
                    speedB.selectmenu('disable');
                }
            }
        });

        $("#on").click(function(){
            speedB.selectmenu("enable");
        });

        $("#off").click(function(){
            speedB.selectmenu("disable");
        });
```

</code>

HTML
<code>
    <a href="#nogo" id="on">on</a><br />
    <a href="#nogo" id="off">off</a><br />
    <form action="#">
        <h2>Default: "popup" Style</h2>
        <fieldset>
            <label for="speedA">Select a Speed:</label>
            <select name="speedA" id="speedA">
                <option value="1">On</option>
                <option value="0">Off</option>
            </select>
        </fieldset>

```
    <h2>Same with option text formatting</h2>
    <fieldset>
        <label for="speedB">Select an Address:</label>
        <select name="speedB" id="speedB">
            <option value="Slower" selected="selected">Slower</option>
            <option value="Slow">Slow</option>
            <option value="Medium">Medium</option>
            <option value="Fast">Fast</option>
            <option value="Faster">Faster</option>
        </select>
    </fieldset>
</form>
```

</code>

**Comment by KosmoNut** [comment]
The true portion of the IF branch was always being called because options.value was always a string.

I got the demo working by changing the IF condition to "if (!options.index)..."

**Comment by fnagel** [comment]
I will check this asap. Thanks your your contribution.

**Comment by fnagel** [comment]
Does not work for me with your snippet but this way:

```
select: function(event, options) {
    if (options.value == "on") { 
        speedA_depends.selectmenu('enable');
    } else {
        speedA_depends.selectmenu('disable');
    }
}
```

Thanks for your idea for checking the type of the passed value.

Closed as "fixed" :-)
