### ISSUE TITLE
Please help to test version 1.1

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#120]
Please help to test the first tagged version of the selectmenu widget. Its called v1.1 because this is the first tagged version after the filamentgroup initially posted it.

Our aim is to ensure that all important features work in most browsers. Take a look at the milestone issues: https://github.com/fnagel/jquery-ui/issues?milestone=3

WHAT TO DO:
Download the latest version (using Git or this link: https://github.com/fnagel/jquery-ui/zipball/selectmenu) and open file /demos/selectmenu/index.html

WHAT TO TEST:
default & disable / enable demo (both with keyboard control testing), background image demo

WHERE TO TEST:
FF 3.6
FF 4 DONE
Chrome (latest) DONE
IE 6 DONE with errors
IE 7 DONE
IE 8 DONE
Opera (latest) DONE
Safari (latest) PARTLY (please could somebody test in latest version)

It would be nice of somebody could give some feedback for MAC and Linux browser, too.

**Comment by fnagel** [comment]
Tested in Chrome and Firefox4.

**Comment by fnagel** [comment]
Tested in Opera.

**Comment by fnagel** [comment]
Tested in old (3.2.1) Safari.

**Comment by fnagel** [comment]
Tested in IE8

**Comment by fnagel** [comment]
Some issues in IE7:
https://github.com/fnagel/jquery-ui/issues/121 (solved)

**Comment by fnagel** [comment]
Testes IE6 in spoon VM-App but needs to be verified with MS VirtualPC Image. Current issues: 
https://github.com/fnagel/jquery-ui/issues/123
https://github.com/fnagel/jquery-ui/issues/10
https://github.com/fnagel/jquery-ui/issues/80

Both are non-blocking for the upcoming release.

**Comment by lephyrius** [comment]
All tested on Mac OS X 10.6.7
Firefox 4: OK
Chrome 11: OK
Opera 11.11: No rounded corners on disabled selectmenus.
Safari 5.0.5: Disabled by HTML(initial) is not displaying any initial text.

Thats the only things I found.

**Comment by fnagel** [comment]
Thanks for the feedback. 

I can confirm the Opera issue on Windows. This is a problem with opactity but as we use the jQuery UI CSS framework this is not a selectmenu problem. 

I can confirm the Safari issue on Windows. I consider this non-blocking for the upcoming release but I opened a new issue for this: https://github.com/fnagel/jquery-ui/issues/124

**Comment by fnagel** [comment]
Version 1.1.0 released!

Download:https://github.com/fnagel/jquery-ui/zipball/selectmenu_v1.1.0

Milestones (all issues since I take over development): https://github.com/fnagel/jquery-ui/issues?milestone=3
