### ISSUE TITLE
Safari: initial disabled select without text

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#124]
In Safari 5.0.5 on MAC and Windows there is no text visible on the new selectmenu a tag when using inital disable for the whole selectmenu.

**Comment by Globulopolis** [comment]
Same problem on Mozilla FF 3.+ on Windows

**Comment by fnagel** [comment]
FF3 is already outdated and insecure. Latest FF works fine.

Again verified for Safari 5.x on Win.

**Comment by fnagel** [comment]
Closed as outdated.
