### ISSUE TITLE
Support empty optgroup label

### ISSUE THREAD

**Issue by nabbo** [fnagel/jquery-ui#129]
Hi

I'm trying to use the selectmenu plugin, which is great so far,

however, I have an issue when I get some empty optgroups (it can look weird to have some empty groups, but there is a reason for that in the application).
So, when the optgroup is empty (I mean : no option in it), well, the optgroup just doesn't show up.

Any reason for that ?

Version used : last one (just d/l it few minutes ago)
code used : 
$("#select_list").selectmenu({style:'dropdown'});

Thanks for your help

**Comment by fnagel** [comment]
This problem is confirmed in FF4. As as empty selects (see: #46 & #82) and optgroups are not handled yet this is a feature request. Will be supported in v1.2 - I hope so :-)

**Comment by nabbo** [comment]
Hi

thanks for the reply

I also noticed some issues when using nested optgroups. in some cases, the optgroup doesn't show up. I'm not sure yet in which cases, but it sometimes happen.
I think that nested optgroup is not fully W3C compliant, but the display is fine (at least in FF3/4) with "standard" select boxes containing optgroups..

So that would be fine to have nested menus in select menus.

Thanks

**Comment by fnagel** [comment]
I would be happy if you could figure out when the optgroup problem appears. Please open a new issue for that.
What do you mean by nested optgroups? You are only allowed to have one level oprgroups.

**Comment by fnagel** [comment]
Please give some feedback on the nested optgroups issue. Perhaps you could open up a new issue for that :-)

**Comment by fnagel** [comment]
Im currently working on the problem with empty selects and I must confess the whole processing of the lis must be rewritten to support empty optgroups. Im currently not able to allocate the needed time to implement this feature. Sorry.

Perhaps somebody wants to help out here with a patch or by sponsoring this feature?

**Comment by fnagel** [comment]
Closed, please reopen if needed.
