### ISSUE TITLE
Incorrect option HTML escaping

### ISSUE THREAD

**Issue by fdx** [fnagel/jquery-ui#131]
When you are not using the "format" option, and you have an &lt;option /&gt; element with escaped HTML like this one:
&lt;option value="10"&gt;Hello &amp;lt;h1&amp;gt;world&amp;lt;/h1&amp;gt;&lt;/option&gt;
The resulting &lt;li /&gt; will be:
&lt;li&gt;&lt;a&gt;Hello &lt;h1&gt;world&lt;/h1&gt;&lt;/a&gt;&lt;/li&gt;

So the &lt;h1&gt;world&lt;/h1&gt; is injected in the DOM!

A simple fix for this security problem was changing the line 562 from:
return (this.options.format ? this.options.format(text) : text);
To:
return (this.options.format ? this.options.format(text) : $('&lt;div /&gt;').text(text).html());

This works fine without the "format" option. If this option is used, the HTML should be escaped inside the this.options.format() function, (responsability of the user, not the selectmenu jquery-ui plugin).

Regards,
fdx

**Comment by fnagel** [comment]
I dont see any security issue here as the escaped HTML needs to be delivered by your own server.

**Comment by fdx** [comment]
I've prepared an example for you:
http://www.fdxdev.com/jquery-ui-selectmenu-example/index.php
The problem is when you are converting a normal HTML select to a jquery-ui-selectmenu.

Here is the fixed version:
http://www.fdxdev.com/jquery-ui-selectmenu-example/fixed.php

This is the diff for the selectmenu JS:

```
$ diff jquery.ui.selectmenu.1.1.0.js jquery.ui.selectmenu.1.1.0.fixed.js
562c562
<               return (this.options.format ? this.options.format(text) : text);
---
>               return (this.options.format ? this.options.format(text) : $('<div />').text(text).html());
```

**Comment by fnagel** [comment]
I understand you point but this is no security issue. The issue you are talking about is when an attacker is able to change the HTML delivered to the client form within your server. This has nothing (!) to do with selectmenu.

**Comment by fnagel** [comment]
Some more questions on this issue?

**Comment by fdx** [comment]
Yes. I have an ABM that are used by my users to add categories. All the html-escaping is perfectly managed by my application. Also, I then draw a native <select> tag correctly escaped in order to let the user select a previous created category. At this point, the user is not able to inject any HTML code in the page. But when I init the .selectmenu() element, the corresponding JS selectmenu could be broken because the data of the native HTML <select> is not correctly "translated" to the JS selectmenu.

**Comment by bedirhan** [comment]
I second fdx. 
I had an XSS issue because of this behavior. HTML Encoding was done at the server side, and at the client side it turned into XSS. We can call this a DOM based XSS and it was hard to catch.
We mitigated it by encoding twice at the server side.

https://www.owasp.org/index.php/DOM_Based_XSS

**Comment by fnagel** [comment]
I will implement this with an option. Changed to feature request. Please be patient as there are some urgent bugs to fix first :-)

**Comment by robert7** [comment]
I don't know.. I would not call a XSS vulnerability problem a "feature request"..

Code example (corrently HTML escaped "select"):

```
    <select id="xx" name="yy">
       <option value="aa">Abcd&lt;script&gt;alert(123)&lt;/script&gt; </option>
    </select>
```

Then:

```
    $('select').selectmenu();
```

**Comment by fnagel** [comment]
I talked to some guys at jQuery UI and they agreed this is not a problem when using widgets probably. The developer must take care that no malicious code is placed as text in the select options. The only problem I see is when a developer is forced to use escaped tags like in the demo fdx posted, perhaps in a rich text editor toolbar.

@bedirhan
Why did you need to place escaped tags in your options?

As I already wrote, I will implement this as an option soon after v1.2 release.

**Comment by robert7** [comment]
Ok thanks for attention.

**Comment by fnagel** [comment]
Implemented as option escapeHtml which default is false.

Please test and give feedback!

**Comment by robert7** [comment]
Hello Felix!
with the new option the escaping works correctly.
I personaly would prefer the option "escapeHtml" to be true by default..
thanks
Robert

**Comment by fnagel** [comment]
Thanks for your feedback! Closed as solved.
