### ISSUE TITLE
Select Menu as a Link

### ISSUE THREAD

**Issue by 422** [fnagel/jquery-ui#132]
This isnt so much of an issue as a request for information.

We have the following HTML:

< option value="4def1b88a1247" >< a href="link" >Text< /a >< /option  >

When using jquery-ui select menu, the option is changed to:

< span class="ui-selectmenu-status" >Text< /span >

How do we get a jquery-ui selectmenu option to link to another page? We have tried onclick, but this also gets removed when the select menu is re-written.

We just want our options to link to pages without the need of a form to be submitted, is this possible with jquery-ui selectmenu?

Apologies if this wrong palce to ask a question, we have tried on Stackoverflow. With no luck

**Comment by fnagel** [comment]
Hey 422, 
this is absolutely correct place to ask questions like this. Please take a look at the to wiki: https://github.com/fnagel/jquery-ui/wiki/Selectmenu and search for the callback headline.

Something like this should help:

<pre>
$('select').selectmenu({
    change: function(e, object){
        window.location.href = object.value;
    }
});
</pre>


see demo: http://jsfiddle.net/fnagel/GXtpC/1/

ps: you should not embed a tags within an option. Afaik its invalid HTML.

**Comment by 422** [comment]
Felix you are a star !!!
We will get working with this code right now, yeah I had thought it wouldnt be valid.. but will go thru this code and hopefully solve our issue ( compliantly ) if that's a word .
Cheers and Kudos mate.

Incidentally, we made a lovely ( yet simple ) dynamic select menu to show/hide two other select menus.. with fallback, using some jQuery and your elements .. excellent stuff. Thanks once again. WIll report back

**Comment by fnagel** [comment]
No problem, your welcome :-)

**Comment by 422** [comment]
Absolutely perfect, a little class jiggery pokery and working like a charm :) thanks so much :)
