### ISSUE TITLE
Chrome: Error when setting selectedindex = -1 and then try to open

### ISSUE THREAD

**Issue by sfradel** [fnagel/jquery-ui#134]
The error occurs when trying to set focus in open method.
Putting this above focus call at least unblocks the control and resets its selected value.

if (this._selectedIndex() == -1){
                this.element[0].selectedIndex = 0;
                this._refreshValue();
            }

**Comment by fnagel** [comment]
Sorry for the late response, I will take a look as soon as #147 is fixed. 

Perhaps you would like to test the new jQuery UI Selectmenu built from scratch? See #140

**Comment by fnagel** [comment]
Would you mind test the latest commit?

**Comment by fnagel** [comment]
Im not able to reproduce the problem, please test the latest commit and give feedback!

**Comment by fnagel** [comment]
Closed as no feedback was given.
