### ISSUE TITLE
change the function name..

### ISSUE THREAD

**Issue by elombashy** [fnagel/jquery-ui#135]
hiii
I liked your code, and used it in some page for the select menu, but also, I need the same code in the same page for another use, so i have to change the name of the function from ui.selectmenu into  ui.changemenu..

the problem is that this change is not enough to the code to work. and changing all the words with "selectmenu" into "changemenu" is not enough too.. what also should I do?

**Comment by fnagel** [comment]
Im not quite sure why you do this but one possible problem could be the CSS which has the selectmenu prefix too!
Would you please post your changed code in a pastebin so I can take a look?

**Comment by elombashy** [comment]
that's wright... it's because of the css... I want to update your code into checkbox instead of select menu..

thanxs a lot

**Comment by fnagel** [comment]
So this issue is resolved I guess. Please reopen if needed!
