### ISSUE TITLE
IE bug when selectmenu is embedded in a jQueryUI modal dialog

### ISSUE THREAD

**Issue by andretti1977** [fnagel/jquery-ui#137]
A visualization bug raises when selectmenu is embedded in a jQueryUI modal dialog under IE7-8.

If dialog is modal, when a user click the selectmenu, page grows in width, height, modal opacity layer becomes completely opaque and page scrolls to the right and down.

Example is visible at http://jsfiddle.net/teo_/mjj3s/1/

Modal dialog is defined in html window: changing modal from false to true under IE7-8 produces above descripted bug.

I debugged code and found that this line of code is the one responsible for the bug:

```
this.list.addClass(self.widgetBaseClass + ‘-open’)
.attr(’aria-hidden’, false)
.find(’li:not(.’ + self.widgetBaseClass + ‘-group):eq(’ + this._selectedIndex() + ‘) a’)[0].focus(); 

```

Changing line to this solves the bug (as you can see at http://jsfiddle.net/VTqTx/  ):

```
this.list.addClass(self.widgetBaseClass + ‘-open’)
.attr(’aria-hidden’, false)
//.find(’li:not(.’ + self.widgetBaseClass + ‘-group):eq(’ + this._selectedIndex() + ‘) a’)[0].focus(); 

```

**Comment by fnagel** [comment]
This problem seems to be related to this one: https://github.com/fnagel/jquery-ui/pull/94#issuecomment-1270916
Im currently not aware of a workaround and this bug needs further investigation. Perhaps we need to disable popup style until a solution is ready. Any help is appreciated!

**Comment by fnagel** [comment]
I hopefully solved this problem as I heavily modified some possible involved parts of the widget. Please test the latest commit and give feedback. Ive updated your fiddle with the latest sources (please note CSS was changed) and it seems to work: http://jsfiddle.net/fnagel/mjj3s/7/

I will close this one as multiple issues are affected. Please see this #147 summery and give feedback there!
Please re-open this issue if the problem persists in latest commit!

**Comment by fnagel** [comment]
I feel cautiously optimistic Ive found a solution for this whole flickering/jumping/positioning issue. Finally. See and comment #147
