### ISSUE TITLE
Dropdown doesn't hide

### ISSUE THREAD

**Issue by dfleury** [fnagel/jquery-ui#14]
Dropdown doesn't hide when an item selected. It's occurs when I use jquery 1.4.2 and jquery-ui 1.8.4.
If I go to line 410 and change <strong>this.element.trigger('change');</strong> to <strong>this.element.triggerHandler('change');</strong>, the dropdown hides.

**Comment by fnagel** [comment]
Sorry for the late response. Too much work to do.

My branch works with jQuery 1.4.2 and UI 1.8.4. I downloaded jquery UI (v1.8.5) as zip from jqueryui.com as well and still not able to reproduce the above mentioned problem.
Are you able to provide a example zip file?

**Comment by fnagel** [comment]
Please re-open if problem persists.
