### ISSUE TITLE
Destroy method doesn't work when using 'wrapperElement'

### ISSUE THREAD

**Issue by adipasquale** [fnagel/jquery-ui#141]
Hi,

I am experiencing a trouble with the 1.1.0 version 'destroy' method when using the wrapperElement option.

I have a page on which you can click a button that loads (via ajax) a form. you can then cancel or validate, go back to the page, and then reopen the form and so on, all of this via ajax.
In the callback of the form loading, i initialize my selects with selectmenu and a wrapper element, because of jquery themes.

My problem is that I can't destroy the selectmenu instances when closing the form, nor can i reopen them on second loading : it gives back this js error : 
uncaught exception: Syntax error, unrecognized expression: >
It seems to come from the wrapperElement, since it works if i take it off.

I have created a small gist, so that you can check it out : git://gist.github.com/1053321.git 
You will see clearly that you can't destroy selectmenu instances with wrapperElement.

Keep up the good work, and congrats on this amazing widget !

Adrien

**Comment by fnagel** [comment]
Thanks for your feedback. Always appriciated.

Can you please post your selectmenu init code aka the used option for the wrapper element? And would you please give a hyperlink to the gist?

WrapperElement will soon be obsolete as I plan to use a wrapper for the ul element in every case.

**Comment by fnagel** [comment]
Please note the wrapper element is now forced to fix some problems. Please anser my questions above and check the latest branch. Should be fixed!

**Comment by adipasquale** [comment]
Hi,

I've tested the new version, and it works smoothly.

My init call passes dropdown as style and a div with a specific class attribute as a wrapperElement.

FYI, i had made a quick and dirty patch to get wrapperElement to work : 

(line 415 in the old version)

```
    if ( this.options.wrapperElement ) {
        this.newelement.parent().remove();
        this.list.parent().remove();
    } else {
        this.newelement.remove();
        this.list.remove();
    }
    this.element.show();
```

The DOM was not traversed correctly it seems.

Anyway thanks for your help, and keep up the good work !

Adrien

**Comment by fnagel** [comment]
Your fix was already implemented in one of the latest versions (before it was obsolete).
