### ISSUE TITLE
Positioned bottom right after resize

### ISSUE THREAD

**Issue by RWOverdijk** [fnagel/jquery-ui#142]
This occurs in Chrome on MacOSX. When resizing the window, or en- disabling developer tools the select menu (so just the dropdown part) jumps to the bottom right of the window. After clicking the selectmenu a dozen times it returns to its original position.

**Comment by fnagel** [comment]
Does this occur on Chrome MacOSX only or on other browsers / platforms?

**Comment by RWOverdijk** [comment]
MacOSX chrome and firefox (havent tested any others on MacOSX) and Ubuntu Linux in chrome and firefox.

**Comment by fnagel** [comment]
Im not able to reproduce this issue on Win, neither in Chrome or FF. 

Im currently working on some changes to the positioning system and will commit an update soon. Perhaps this fixes your issue, otherwise I will do some research. Any help is appreciated!

**Comment by fnagel** [comment]
This problem could be related to #147. Would you mind test this again with the latest commit?

**Comment by RWOverdijk** [comment]
I will,as soon as i get home.

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Any feedback on this?

**Comment by RWOverdijk** [comment]
Sorry, hectic here forgot all about it. As far as I can tell it's fixed. I can't reproduce.

**Comment by fnagel** [comment]
Thanks, so I consider this as resolved.
