### ISSUE TITLE
Disable selectmenu don't disable select

### ISSUE THREAD

**Issue by nachtgold** [fnagel/jquery-ui#143]
If I want to disable the selectmenum, I use .selectmenu('disable'); but the select-element will not disabled, so .serialize() take the value.

I made a demo in which you can see, that the select-element is not disabled, only the list and the button: http://jsfiddle.net/m2hXe/10/

Sorry for my bad english ;)

**Comment by fnagel** [comment]
Thats correct, thanks for reporting. Currently the widget inits with the same attributes like the original select but the widget does not change the status of the original element. 

This needs to be fixed but Im not quite sure if everybody would like to skip these values. Why not do this manually? 
    $('select').attr("disabled", "disabled").selectmenu('disable');
See: http://jsfiddle.net/m2hXe/16/

**Comment by nachtgold** [comment]
yes, so I have solved this also first

**Comment by fnagel** [comment]
And did it work? Perhaps it would be suitable to add a notice into the wiki. What do you think?

**Comment by nachtgold** [comment]
yes it works great. a note in the wiki is a good idea

**Comment by fnagel** [comment]
Done and closed. Thanks for your contibution!
