### ISSUE TITLE
Sequential typeahead should cycle through the options (same char)

### ISSUE THREAD

**Issue by limkianyong** [fnagel/jquery-ui#144]
Given that we have the following options in the select menu: 
  James
  John
  Johnson

when I type 'j' twice, then the second option (John) should be selected.

Currently, the first option (James) is always selected, which is not the expected behaviour of a normal select list.

**Comment by fnagel** [comment]
Thanks for reporting. This error is confirmed.

Its a strange but as typing different chars works perfectly. I must confess Im not into this typeahead thing. I will try to ask somebody to take a look.

**Comment by limkianyong** [comment]
I have created a fix for this, and sent a pull request to Tauren's fork (https://github.com/tauren/jquery-ui/pull/1) since it's mentioned that there are more fixes there.

Or maybe I should put the pull request here instead?

**Comment by limkianyong** [comment]
Reopening because I mistakenly clicked on the "comment & close" button instead of the "comment" button

**Comment by fnagel** [comment]
Im pretty sure my fork has much more fixes, take a look at the commits and the issues :-)
He once added this notice without asking anyone at jQuery UI. My fork is the "official" follower of the filaments group script.

Does your fix work with pop-up style and did you test in different browser? I would be very interested in how you fixed this as Im planning to do some refactoring to catch a few issues listed here at GitHub.

Thanks for your contribution!

**Comment by limkianyong** [comment]
Oh.. I have forked Tauren's branch, as ccording to the JQuery UI wiki: http://wiki.jqueryui.com/w/page/12138056/Selectmenu

> Additional Bugfixes can be found in this repo:  http://github.com/tauren/jquery-ui/tree/selectmenu. 

As my code is forked from Tauren's (containing some of his other fixes), should I just send the pull request, or re-do the fixes from another different fork?

I have tested the fix with Safari 5.1, Chrome 12.0.742.122, Firefox for Mac 5.01, Firefox 4, and IE9. 

As for the implementation, the main gist is: 

```
        function doSearch() {
            var listToSearch = this.list.find('li a');

            // for the 1st letter, should select the first item which has the same first letter
            if ( prevChars.isEmpty() ) {
                matchFirstLetter.call(this, listToSearch);
                return;
            }

            // try to match by string first
            if ( matchByString.call(this, listToSearch, prevChars.toString()) ) {
                return;
            }                   

            // if previous char is different from current char, flush the currentFocusedPosition
            if ( prevChars.lastCharIsNotEqualTo(c) ) {
                currentFocusedPosition.reset();
            }

            // try to match by the first letter starting from current position
            if ( matchByFirstCharFromCurrentFocusedPosition.call(this, listToSearch) ) {                
                return;
            }               

            // lastly, try to rematch from the beginning again
            matchFirstCharFromTheBeginningOfList.call(this, listToSearch);
        }
```

**Comment by fnagel** [comment]
Please re-do the fixs from my fork. This would make it much easier for me to merge it. Thanks for your contribution!

**Comment by limkianyong** [comment]
Sure, I will get to it later today. :)

**Comment by fnagel** [comment]
Thanks, that was fast :-)
I will close this issue. Please comment on the pull request!
