### ISSUE TITLE
wrapperElement doesn't bind <ul>

### ISSUE THREAD

**Issue by danpep** [fnagel/jquery-ui#148]
I am trying to wrap the select in a <div> element to do some additional styling, however the <ul> is not bounded by the DIV wrapper  (e.g. I'm trying to give the menu rounded corners using a top-image and bottom image but allowing for elastic height).. 

so doing:  {wrapperElement:'<div class="selectWrap">'} gives me the div around the selectmenu <UL>, but the DIV is always right over the select element, and will not grow with the menu upon open.

**Comment by fnagel** [comment]
Please take a look here how to post code: http://github.github.com/github-flavored-markdown/ (try prssing m key now!) or use a pastebin. I assume some of your post is missing.

Which version do you use? Lastest version has some changes to the wrapper functionality.

**Comment by danpep** [comment]
sorry about the code, didn't know about pastbin, thought it was all preformatted.  There wasn't much code there.  
Anyways, I just pulled the DEV version and it looks better.  I was using the latest stable version, so I thought.

with the DEV build, I have found some other issues.  I'll write them as separate issues.

**Comment by fnagel** [comment]
I just answered your other issue. Just reopen if needed.
