### ISSUE TITLE
scrollbar problems

### ISSUE THREAD

**Issue by danpep** [fnagel/jquery-ui#149]
clicking on the scrollbar will hide the selectmenu.  e.g list of US States in the menu.  I'm using latest DEV build pulled today, tested in IE8 and Firefox 4

Firefox also shows a horizontal scroll whereas IE does not, related to the width of the menu?

**Comment by fnagel** [comment]
Ive tested with current stable FF (which is version 5) and IE8 again and was not able to reproduce your reported problems. Did you update the CSS files? This could be your problem as the demo fiddle (http://jsfiddle.net/fnagel/GXtpC/) had similar issues before updating CSS.

**Comment by danpep** [comment]
Yes, you are correct in my error yet again.  Closing this one.
