### ISSUE TITLE
Z-index is set to the list and not the listWrap ==> listWrap shows under source element. (qTip 2)

### ISSUE THREAD

**Issue by viskenxp** [fnagel/jquery-ui#151]
When selectmenu is used in combination with qTip2, the z-index is not set correctly. It sets the z-index of the list and not the listWrap. This results in the list being shown under the qTip as it has the same z-index as the qtip but it's included in the same level in the DOM-tree. 

Was there any particular reason why the z-index is set to the list and not listWrap?

Tested Browsers: FX 5, Chrome 14

**Comment by fnagel** [comment]
Ahh thanks for this. Its a follow up to this issue(s) #147

Fixed and committed. Please test and give feedback!

**Comment by gregaton** [comment]
I had the same problem when the selectmenu is displayed in a jQuery Tools Overlay and I can confirm that your fix solves the problem.

**Comment by fnagel** [comment]
Thanks for your feedback. Closed as solved.
