### ISSUE TITLE
Hiding Default Option Breaks in IE7+

### ISSUE THREAD

**Issue by ghost** [fnagel/jquery-ui#152]
Repro steps:

1) Attach a class of "default" to the default option in my select menu.
2) Once selectmenu() transfers over the classes, hide with css using display: none

This works in Chrome, Firefox and Safari. It doesn't work in IE6, 7, or 8 ... but honestly, who cares about IE6!

Here's a link to my demo. http://wecodesign.com/demos/selectmenu.htm

I tried to add an option called hideDefault, and then writing some code to prevent the default option from being written to the new drop down; however, it also prevents it from being the default option in the new select menu, perhaps someone with more time than I can take on the task of expanding this solution. The code I wrote this far is as follows:

`// write li's
if (selectOptionData.length) {
    for (var i = 0; i < selectOptionData.length; i++) {
        if(!o.hideDefault && selectOptionData[i].indexOf >= 0){
            var thisLi = ... Rest of code
        }
    }
}`

**Comment by ghost** [comment]
I've create a solution which fixes this issue, and should be taken into consideration for official integration

1) Added hideDefault to options{}
`options: {
    hideDefault: null
}`

2) Changed the _init function
```// update value
this.index( this._selectedIndex() );
if( o.hideDefault ) {
    $( '.' + self.widgetBaseClass + '-menu .default' ).remove();
}

``````

4) added default class to the default option
```<select tabindex="1" class="custom-selectmenu">
    <option value="0" selected="selected" class="default">Choose Month</option>
...
</select>
``````

3) set hideDefault to true when calling selectmenu()
```$( '.custom-selectmenu' ).selectmenu({
    hideDefault: true
});

```
```

**Comment by fnagel** [comment]
Im not quite why to implement this feature as its not supported by the native select. The problem in IE is that it is not possible to give the first li focus as its hidden. This will cause other problems too as the internal set selectedIndex will be incorrect. There is need of additional changes to make this work in all circumstance. 

A quick fix (easier than yours) would be to add a simple :visible in function open:

```
var selected = self.list.attr('aria-hidden', false).find('li:not(.' + self.widgetBaseClass + '-group):eq(' + self._selectedIndex() + '):visible a');
```

and keep using your display: none CSS.

Why not use the disable option feature or just give feedback to the user the field is required?

**Comment by ghost** [comment]
I was unaware as to the exact reasoning behind why IE was not behaving properly, but I'm glad to know that :visible fixes the issue. I thing propose that that should go into the build. Asking that users add a specific class to a select drop-down does seem like it would have some drawbacks.

Thanks for the solution, it works great. The reason why I wanted to do this was so that I wouldn't be prompting the user to select the default option which would then just result in a submission error. My goal is to remove as many obstacles from the user as possible.

**Comment by fnagel** [comment]
Perhaps you're right. I will commit this as its a small thing which could help prevent problems. Thanks for your contribution!
