### ISSUE TITLE
Option for menu container DIV

### ISSUE THREAD

**Issue by payahnih** [fnagel/jquery-ui#155]
Hi, I am creating a popup menu/div M which contains selectmenu. I want to have the popup menu to be contained within my own div X which is nested inside div M (child of div M). The popup menu/div M will be shown on hover in and hide on hover out.
When the select menu list is shown, my popup div M is hovered out immediately. 

Using wrapperElement cannot satisfy this as the menu <ul> it still appended to the end body. Is there a way to stop hover out event to be triggered on div M ?

Another way I've tried is adding selectmenu option for menuContainer which we will pass as a string. Can be #divid or .divclass, then inside selectmenu.js, I change the code everywhere: appendTo ('body') to appendTo($(this.options.menuContainer)).

Sample:
if ( this.options.menuContainer ) {  
            this.list = $('<ul class="' + self.widgetBaseClass + '-menu ui-widget ui-widget-content" aria-hidden="true" role="listbox" aria-labelledby="' + this.ids[0] + '" id="' + this.ids[1] + '"></ul>').appendTo($(this.options.menuContainer));
        }
        else {
            this.list = $('<ul class="' + self.widgetBaseClass + '-menu ui-widget ui-widget-content" aria-hidden="true" role="listbox" aria-labelledby="' + this.ids[0] + '" id="' + this.ids[1] + '"></ul>').appendTo('body');
        }

I think this would be a good feature also.
Thanks.

eddy

**Comment by fnagel** [comment]
This feature was requested before. I will add this soon!

**Comment by fnagel** [comment]
In accordance to jQuery UI this option should be named "appendTo".

**Comment by fnagel** [comment]
Sorry for the delay. Ive implemented an option "appendTo". Please test latest commit and give feedback!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by payahnih** [comment]
Hi,

Sorry, I've not got a chance to try/test anymore.

Regards,
eddy

**Comment by dguzzo** [comment]
this feature is immensely helpful and solves a major feature issue that i was running into for a project. works like a charm, thanks Felix!

**Comment by fnagel** [comment]
Thanks for the feedback! Feature has been documented.
