### ISSUE TITLE
Selectmenu: Can't scroll using mouse

### ISSUE THREAD

**Issue by davidpenick** [fnagel/jquery-ui#156]
In the latest dev code (35b4a7a), attempting to use the mouse to scroll through a large menu causes the selectmenu to close. I'm pretty much a jquery newbie, but I think the introduction of the wrapper around the list (listWrap) has caused the problem because it is not handling the mousedown and mouseup events. Adding a handler for these events to listWrap that returns false seems to fix the issue. Here's the diff:

``` ruby
@@ -188,11 +188,13 @@
        });
        this.listWrap = $( o.wrapperElement )
            .addClass( self.widgetBaseClass + '-menu' )
            .append( this.list )
            .appendTo( 'body' );
-       
+                // this allows for using the scrollbar in an overflowed list
+       this.listWrap.bind( 'mousedown.selectmenu mouseup.selectmenu', function() { return false; });
+
        // transfer menu click to menu button
        this.list
            .bind("keydown.selectmenu", function(event) {
                var ret = false;
                switch (event.keyCode) {
```

**Comment by fnagel** [comment]
Mhh Im not able to reproduce this problem. Please take a look here how to post a proper bug report: #61

Thanks for your contribution!

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by davidpenick** [comment]
Sorry, I'm really busy at work. I will try to provide more information soon.

David

**Comment by kingtut** [comment]
Thanks davidpenick, great fix for this issue.

Edit: jQuery 1.6.4, jQuery UI dev (fnagel)

**Comment by fnagel** [comment]
@kingtut
Are you able to provide a step by step instruction how to reproduce this issue? A demo fiddle would be perfect! See #61

**Comment by mamchale** [comment]
Firstly, thanks for creating this, it's awesome! I just have a couple of problems!

I think I have the same problem as above.

See:

http://www.staging.safety-marine.co.uk/life-rafts-and-accessories/liferafts/p4612s64/charter-iso-9650-liferaft-type-1.htm

I'm pulling my hair out. Clicking on the scroll bar causes the menu to close. You can scroll with the mouse scroll button, but not clicking, I think it is the same problem as above.

Using latest jquery, jquery ui 1.8.6 I think and the latest ui.selectmenu from here. Latest css also I think.

Also I'm getting a horizontal scroll bar, not sure why.

Any help gratefully received.

Thanks

Marc

**Comment by mamchale** [comment]
Sorry, I have just found the updated CSS on here and it has solved my problems. Sorry!

Thanks again for a great widget!

**Comment by fnagel** [comment]
So this issue could be closed?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by kingtut** [comment]
For me, it's likely I was also using old CSS. I used davidpenick's hack and simply haven't the time right now to modify a finished project to investigate. I will revisit this in a month or two for a new project. For now I guess you may as well close this as no-one else has any thoughts on the issue.

**Comment by davidpenick** [comment]
I should have some time to look at this early next week. If you can give me a week before closing, that'd be cool. Sorry for being so unresponsive.

David

**Comment by fnagel** [comment]
I will wait, no problem. I was just going trough all issues in order to close some outdated.

**Comment by fnagel** [comment]
Just a gentle reminder...

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by kwc5811** [comment]
I can confirm this issue and the above code resolved the issue. My code packaged with 1.8.16.

**Comment by martijnhoutman** [comment]
Another confirm using commit cf6eff7, jQuery 1.4.4 and the above fix.

**Comment by fnagel** [comment]
Im sorry but Im still not sure how to reproduce the issue. Please post a jsfiddle or a zip file, see #61

Is it reproducible in the demo fiddle? http://jsfiddle.net/fnagel/GXtpC/
Does this problem occur cross browser?

**Comment by fnagel** [comment]
Any feedback on this issue? Still a problem in latest commit?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by martijnhoutman** [comment]
Hi Felix,

Sorry for the delayed response! The latest commit seems to be working fine for me now (some other improvements as well), thanks a lot!

**Comment by fnagel** [comment]
Nice, thanks for the feedback!
