### ISSUE TITLE
.remove() on parent with selectmenu inside failed

### ISSUE THREAD

**Issue by harriswong** [fnagel/jquery-ui#157]
## brief:

`<tr id="deleteMe"><select class="test">....</select></tr>`
called $('#deleteMe').remove() gives the following error:

**$("label[for=" + this.newelement.attr("id") + "]").attr("for", this.element.attr("id")) is undefined
http://localhost/sys/include/js/plugin/jquery.ui.selectmenu.js
Line 309**

I tried $('#deleteMe').empty(), same error.
## System:

FF 6.0
jquery-ui 1.8.14
jquery 1.6.1
selectmenu config: 

```
$('.test').selectmenu({
style: 'dropdown',
width: 250
}); 
```

**Comment by fnagel** [comment]
Would you please explain what you trying to archive? You can post an demo if its easier: #61

**Comment by harriswong** [comment]
Hi,

Thanks for the reply.  
- Browser:  FF 6.0.2
- OS:  Mac Lion, Ubuntu
- Steps to reproduce: I have attached the following demo with jsfiddle:

http://jsfiddle.net/zJYqx/5/

**Comment by fnagel** [comment]
Take a look here: http://jsfiddle.net/zJYqx/7/
Please note I moved the deleteMe id.

You need to use the destroy method on the widget and remove the original select manually.

**Comment by harriswong** [comment]
Thanks.  I will destroy the selectmenu before removing the element.
