### ISSUE TITLE
Selectmenu button should be inline-block

### ISSUE THREAD

**Issue by betalb** [fnagel/jquery-ui#158]
After setting wrapperElement to &lt;div&gt; by default selectmenu became block-level element.

Default browser select box is inline-block

Here is sample fiddle http://jsfiddle.net/nwFMs/

**Comment by fnagel** [comment]
Thanks for your contribution.

I can confirm this issue on FF4. Any idea how to get rid of it? display: block seems to be necessary atm.

**Comment by betalb** [comment]
Opened pull request with proposed fix

**Comment by fnagel** [comment]
Closed as we have a pull request: #166
