### ISSUE TITLE
selectmenu doesn't toggle dropdown on multi-click

### ISSUE THREAD

**Issue by brainTrain** [fnagel/jquery-ui#159]
clicking the drowdown arrow, etc, doesn't toggle the dropdown.  The issue is in line 596 of jquery.ui.selectmenu.js  (the _toggle function).  Changing 

if ( this.list.is('.' + this.widgetBaseClass + '-open') ) {

to

if ( this.list.parent().is('.' + this.widgetBaseClass + '-open') ) {

fixed the issue.  Gonna send a pull request when I figure it out (still new-ish to this github stuff).

**Comment by fnagel** [comment]
Thanks for your contribution!

This is a legacy issue related to #147. Thanks for that!

ps: Small fixes like this could be posted as inline comments without any problems. Type 'm' to get some infos about markup!

**Comment by brainTrain** [comment]
sweet!  Yeah I'm still learning about all this markup stuff.  I never got around to doing a pull request, but I'm assuming you just put that guy in since it was a super easy fix.
