### ISSUE TITLE
"disable" doesn't disable adding and removing .ui-state-hover

### ISSUE THREAD

**Issue by mad-doctor** [fnagel/jquery-ui#16]
When the selectmenu is disabled, the hover state is still added when the mouse is over.
I've added if ( o.disabled ) { return false; } after lines 109 and 112 and it solved the problem, but this may be needs some more testing.

Best regards,
Stoyan Koevsky

**Comment by fnagel** [comment]
Thanks for your contribution. I will integrate this asap!

**Comment by fnagel** [comment]
commited!
