### ISSUE TITLE
insufficient right padding for .ui-selectmenu-status

### ISSUE THREAD

**Issue by jfirebaugh** [fnagel/jquery-ui#161]
A fixed-width selectmenu with enough text ends up with the text overlapping the arrow icon:

http://jsfiddle.net/KtEaK/

The default right-padding for the `ui-selectmenu-status` class is 1em. It should be 2.1em, the padding jQuery UI buttons use when an icon is present.

**Comment by fnagel** [comment]
Thanks for your contribution!

This problem is confirmed, fixed and pushed to the repo.

**Comment by njankit** [comment]
Still facing the issue where the text has no spaces. I'm using the latest css from your repo and jQuery 1.7.1 and jQuery UI 1.8.16

http://jsfiddle.net/KtEaK/21/

**Comment by fnagel** [comment]
You will need to set font-size smaller or make your select bigger as your text wont fit into the 100px selectmenu.
