### ISSUE TITLE
setting value does not work properly

### ISSUE THREAD

**Issue by jcrawford** [fnagel/jquery-ui#165]
I was working on a task using a selecmenu drop down for a report form.  Next to the drop down was a span that had an onclick event.

When the span is clicked the following event is triggered.

```
    $("#transactionCodesResetBtn").click(function() {
        $('#transactionCodes').val(0);
        redrawTable();
    });
```

When this is executed the drop down does not visibly change the value.  It remains on the selected value.  However if I add an alert after I set the value, it reports the value just fine.

alert($("#transactionCodes").val());

I noticed this was an issue with selectmenu because when I comment out the following code, everything works perfectly.

// $('#transactionCodes').selectmenu();

**Comment by fnagel** [comment]
You should use the value method of the widget to retrieve data.

Please take a look at the to wiki: https://github.com/fnagel/jquery-ui/wiki/Selectmenu

**Comment by jcrawford** [comment]
I have tried this and it seems to return [object Object] is there a way to determine which property I need to try to fetch from that object?

var dateField = $("#datepicker").selectmenu("value");

I am using the onClose function because I am using it to make and ajax request and cannot use on change because that gets fired off twice and 
do not want to have 2 ajax requests per date selection.

Also using

$("#datepicker").val(default_date_range); works but the code below does not set the value

var default_date_range = '<?=$default_start_date." - ".$default_end_date;?>';
$("#datepicker").selectmenu("value", default_date_range);

I am not sure why this is so hard for me to figure out lol

Thanks,
Joseph Crawford

**Comment by jcrawford** [comment]
My bad, the reason I cannot figure it out is I confused you with the developer of another plugin lol

Sorry.

**Comment by fnagel** [comment]
So this could be closed?

**Comment by jcrawford** [comment]
yes thank you and sorry.
