### ISSUE TITLE
Can not refresh Select Menu text

### ISSUE THREAD

**Issue by omerx** [fnagel/jquery-ui#167]
I am changing "select menu" via ajax. Then I see the changing on "option selected" value in "select menu" but text seen on ".selectmenu" does not change. I triede "refresh method" but it did not work as well. Can you please help? Thank you in advance. 

Screen Picture:
http://b1109.hizliresim.com/11/9/28/5759.jpg

**Comment by fnagel** [comment]
I assume your trying to change some state or value but without knowing how to do this. Please take a look at the wiki: https://github.com/fnagel/jquery-ui/wiki/Selectmenu Search for "methods".

If Im wrong, please show me some demo, see #61

**Comment by omerx** [comment]
The code I used on DEMO page is as follows. When I run this code and when I click "mybutton" , item selected does not change. 

<script type='text/javascript'>
           $(document).ready(function() {
$("#mybutton").click(function(){
$("#speedA [value='Fast']").attr("selected","selected");
alert('test');
    });
            }); 
</script>


<input type='button' id='mybutton' value='Change'>

**Comment by fnagel** [comment]
No, of course its not changing. Why should it? 
See my post above as you need to use methods value or index on the widget.

**Comment by omerx** [comment]
Hello, when I added the code I see on the method page, the problem is fixed. Thank you @fnagel

"https://github.com/fnagel/jquery-ui/blob/selectmenu/demos/selectmenu/methods.html "

"console.log($('select#speedA').selectmenu("value", "Fast"));"
