### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by omerx** [fnagel/jquery-ui#168]
Hello 
I have problem with "z-index". I can not arrange the orders of the "select menu" object and "ui-dialog"
object. Select menu is under the ui-dialog object. But I want to bring the select nemu  to front . I assigned z-index of select menu as 9000 and  ui-dialog is assigned z-index automatically 1002. But even 9000 is bigger than 1002 ui-dialog object is in front of select menu. Can you please advice how can I bring select menu in front? Thank you very much.

http://b1110.hizliresim.com/11/10/3/3639.jpg

**Comment by fnagel** [comment]
Mhh, zIndex() is used so this should be no problem afaik. I know some people using selectmenu within a dialog. 

Would you mind posting a demo fiddle? See #61

**Comment by omerx** [comment]
Hello 

Problem is solved when I made below changing on "ui.selectmenu.js". Below code is generating a "zindex" and it does not accept the one I entered in css. There is no proble at the moment at all.  Thank You

```
    // update zIndex if jQuery UI is able to process
    /*
    var zIndexElement = this.element.zIndex();
    if ( zIndexElement ) {
        this.listWrap.css( 'zIndex', zIndexElement );
    }
    */
```

**Comment by fnagel** [comment]
I assume youre using the z-index wrong. The zIndex is definitely needed to
make selectmenu work with dialog, tabs, etc.
Perhaps you should search the issues for dialog.
