### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by JonoB** [fnagel/jquery-ui#169]
Is it possible to have a prompt for the selectmenu: i.e. an in item that is displayed by default, but not selectable (not in the dropdown list). Something like 'Please select...' ?

**Comment by fnagel** [comment]
No its currently not possible to have a default value which does not appear in the opened list but on the button.

You could disable the select and change the visual style. This would do the trick but will only work if you do not need "real" disabled options. 

You could extend the renderItem method on the new version of selectmenu. See #140 for more infos.
I plan to add a demo for that usecase anyway. Recheck the selectmenu branch of the jqueryui here at GitHub from time to time!

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed!
