### ISSUE TITLE
Problems with IE9

### ISSUE THREAD

**Issue by cotp** [fnagel/jquery-ui#170]
Hello all :)

I am trying to use demos/selectable/default.html

Impossible to use (focus) the select element, both in IE9 and Chrome, I click on the list but nothing happens

Works well in firefox though...

Looking for a Jscrollpane that would work for Select elements...

Cotp

**Comment by fnagel** [comment]
Hey there! :-)

Im pretty sure it works in both, are you able to post a demo fiddle? (see #61)

Sadly Im not able to give you an advise with an scrollpane script as I have no experience using any on selectmenu. Did you tried  http://jscrollpane.kelvinluck.com/ Its my favorite and pretty solid.

**Comment by cotp** [comment]
Hello, first thanks verty much fnagel to take the time and respond to me ! :)

I posted it here http://cotp.free.fr/testscroll/default.html, to me works in firefox not in IE or chrome (I'm using PC Windows 7)

But actually it is not what I am look for anyway as I am lookin to achieve the same effect with a select.

I tried jscrollpane by kelvinluck.com but can't seem to get it working with a select element (all these are ul an li elements)
I have tried jquery and mootools without anyluck.

IE is always my nightmare :/

Cotp

**Comment by fnagel** [comment]
Ahhh Im sorry. Im only maintaining the selectmenu branch and a modified version of the tabs widget. All other files are only forked.

Youre talking about the selectable demo here which is not part of my work. Please refer to the original branch at jqueryui, see: https://github.com/jquery/jquery-ui

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed!
