### ISSUE TITLE
Can not remove option from select list

### ISSUE THREAD

**Issue by drobazko** [fnagel/jquery-ui#171]
Hi, colleagues!

I have _select_ element: 
select id="material-name"
option id="1">text1/option
option id="2">text2/option
option id="3">text3/option
...
/select

On JQuery I do:
$('#material-name').selectmenu()

Also I want remove selected option in some action handler. I do it like this:
function (e, data) {
        $('#material-name option:selected').remove();
        $('#material-name').selectmenu();
}

Here is some unexpected behevior: option is removing from original _select_ but not from widget, and there is duplicate widget.
But I want refresh existing select widget.

Thanks for replay!

**Comment by fnagel** [comment]
Hey, 

you need to read the Wiki :-)
Search for "Add / delete / modify options" at https://github.com/fnagel/jquery-ui/wiki/Selectmenu

Please comment if you need more help or this issue oculd be closed.

**Comment by drobazko** [comment]
Hey, fnagel
Thanks for help, it's useful for me!

**Comment by fnagel** [comment]
Youre welcome :-)
