### ISSUE TITLE
Make selectmenu easier to download/extract/use

### ISSUE THREAD

**Issue by poeboy** [fnagel/jquery-ui#172]
Right now, it isn't obvious to most people how to use selectmenu.  Let's pretend I'm your average Joe programmer who has never touched git but I want to integrate selectmenu into my website.  I see your recommended downloads and click one of them.  The 5.5MB file downloads and I extract it.  I'm used to seeing a single .js file and maybe a .css and some image files but instead see a jumbled mess (the entire jQuery UI tree).  So then I visit the Wiki and see nothing obvious there.

**Comment by fnagel** [comment]
Hey poeboy, 

I agree that its not that easy to use the widget at the moment. This branch was original created to built a functional version of the selectmenu original published by filament group (see wiki: https://github.com/fnagel/jquery-ui/wiki/Selectmenu). Nothing more. I have only a certain amount of time to give support and maintain the code. 

So, any help is welcome and if you are able to improve the wiki or help out make this widget more usable dont hesitate to contribute! Please be aware that there are plans to integrate a new, built from scratch version into the official jQuery UI branch. Please see: #140

**Comment by fnagel** [comment]
I thought about this some more. One of the main problems is that when you download the zip there are some many unneeded files (other widgets, build, etc.). I assume it would be very helping to delete these files. Only problem is that Im not quite sure if its a problem when the latest jquer-ui fork is merged into my branch. 
Is there a way to merge the needed files only? Im not quite that experienced in Git.

**Comment by poeboy** [comment]
I've seen other projects do a separate push containing the final builds.  That is, the developer does a build and has a special directory for the minified content.  When you download the ZIP, you get everything else too.

Also, look into Git submodules.  You should be able to pull jQuery UI in as a submodule and submodules aren't included in the ZIP files that GitHub generates.

**Comment by fnagel** [comment]
Yeahh, thats possible. Perhaps with Apache ant or something similar. Problem is Im already at the absolute limit of time to maintain the OS projects Im involved in. Isnt there a service like https://gemnasium.com/ for doing stuff like that? That would be great _sigh_

Mhh submodules look interesting. Im not quite sure how to do this with an existing branch, but I definitly will take a look. 
Any hints how to do this without risking messing up my local branch?

Are you aware what will happen if I just simple delete unneeded files and merge with the jquery UI branch?

**Comment by spacedevin** [comment]
I created a ghetto little script that will probably work for what you want. It will create the archive and upload it to github everything the service hook is triggered.

https://github.com/arzynik/github-auto-release

**Comment by fnagel** [comment]
Seems promising, I will definitly take a look asap!

**Comment by fnagel** [comment]
I've decided to delete unneeded files and add them to gitignore. 

Please take a look and give feedback!

**Comment by fnagel** [comment]
What do you think? Easy enough?

**Comment by fnagel** [comment]
No feedback? :-(

**Comment by fnagel** [comment]
Closed. Please reopen if needed.
