### ISSUE TITLE
selectmenu: cycle on same letter on keypress

### ISSUE THREAD

**Issue by danpep** [fnagel/jquery-ui#174]
most select menus cycle back to the first item when keying the same letter.  hitting F for the list "Fast, Faster, Fastest" will go back to "Fast" on the 4th keying of the letter "F".

**Comment by danpep** [comment]
I finally got it to cycle back to the beginning of the list by adding the following around line 498, but not positive it's correct.

if( thisText.indexOf(C) == 0 || thisText.indexOf(c) == 0){
if(self._prevChar[0] == C){
if(self._prevChar[1] < i){ focusOpt(this,i); }
/**INSERTED CODE**/
else if (self._prevChar[1] == i){ self._prevChar[1]=0; }

**Comment by thg2k** [comment]
I want to try to implement this.. how is the algorithm exactly?

If I have the following entries:

  foobar
  foocaz
  fobobo
  fzzbar
  baarrr

When I click f-f it should go to "foocaz", when i click "f-o-o" it should go to "foobar", but for example what happens when i click "f-o-o-o"? shouldn't it go to fobobo?

**Comment by danpep** [comment]
Interesting question.  I was just trying to get it back to "foobar" on the
5th "f":  e.g.  f-f-f-f-f
I was not doing second letters on type, as there would need to be some
distinction in time between the 2 keystrokes.  There's a difference of
typing "fo"  versus "f----------o" with time lag.
in your example (let me add one to the list):

 foobar
 foocaz
 fobobo
 fzzbar
 baarrr
 oohlahlah

"fo" typing quickly would land on foobar.  f---------o  would be "oohlahlah"
to answer your question: I would say that f-o-o-o would remain on foocaz, as
there are no other search-ahead results that would be found after the second
"o" and not enough time lapsed between keystrokes to land on "oohlahlah"

In my application, f-o would go to "oohlahlah" because I am only interested
in the first letter of the word and not doing a search-ahead function.
That's not to say this is right, it's just my preference.  I could see where
type ahead is useful, though and it's implementation would probably be
welcome.

On Tue, Oct 18, 2011 at 7:34 AM, Giovanni Giacobbi <
reply@reply.github.com>wrote:

> I want to try to implement this.. how is the algorithm exactly?
> 
> If I have the following entries:
> 
>  foobar
>  foocaz
>  fobobo
>  fzzbar
>  baarrr
> 
> When I click f-f it should go to "foocaz", when i click "f-o-o" it should
> go to "foobar", but for example what happens when i click "f-o-o-o"?
> shouldn't it go to fobobo?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fnagel/jquery-ui/issues/174#issuecomment-2440625

## 

--- sent from my big old honkin' desktop computer

**Comment by thg2k** [comment]
I have a even more example here:

  foobar
  foobaz
  foobak
  foobbc
  ffzzbb

if you type "f-f-z" it shall select "foobar" at the first "f", "foobaz" at second "f", and "ffzzbb" when you type "z".
I'm working now on an implementation to do this because I need this behaviour for some very long lists.
I'll keep you posted.

**Comment by danpep** [comment]
I would say that if you type "f-f-z" it would select "ffzzbb" on the 2nd
"f", not the "z".  There are no other words that start with "ff".  Again,
thought, I would say that it depends on the time between typing the letters.
  If you type "f-f" quickly, then you would select "ffzzbb".  If you type
"f" then wait a second to type another "f", you would select "foobar" then
"foobaz" on each keypress.

On Tue, Oct 18, 2011 at 8:56 AM, Giovanni Giacobbi <
reply@reply.github.com>wrote:

> I have a even more example here:
> 
>  foobar
>  foobaz
>  foobak
>  foobbc
>  ffzzbb
> 
> if you type "f-f-z" it shall select "foobar" at the first "f", "foobaz" at
> second "f", and "ffzzbb" when you type "z".
> I'm working now on an implementation to do this because I need this
> behaviour for some very long lists.
> I'll keep you posted.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fnagel/jquery-ui/issues/174#issuecomment-2441299

## 

--- sent from my big old honkin' desktop computer

**Comment by thg2k** [comment]
I understand your point, but if you think about it, typing f-f-f would mean selecting foobar, foobaz, and foobak sequentially, so it's wrong to select ffzzbb on the second "f", it would be very unlinear, but typing f-f-z should indeed select ffzzbb. So I came out with this algorith:
 1) save all typed characters within the time frame (1 second)
 2a) if all typed characters are the same, select the next one starting with that letter (and wrap up if needed)
 2b) otherwise, select the first prefix match using the saved characters

i tested it with a firefox default combo box and this is the behaviour implemented (as far as i could understand, finding the actual code in gecko's source would be a very nice pointer!)

So here is my test implementation which kind of works:

``` javascript

    _typeAhead: function( code, eventType ) {
        var self = this,
            focusFound = false,
            c = String.fromCharCode(code).toLowerCase();

        console.debug("typeAhead(" + c + ") " +
                      "[timer: " + self._typeAhead_timer + "] " +
                      "[cycling: " + self._typeAhead_cycling + "] " +
                      "[chars: " + self._typeAhead_chars + "]");

        // Clear any previous timer if present
        if ( self._typeAhead_timer ) {
            window.clearTimeout( self._typeAhead_timer );
            self._typeAhead_timer = null;
        }

        // Store the character typed
        self._typeAhead_chars = (self._typeAhead_chars === undefined ? "" : self._typeAhead_chars).concat(c);

        // Detect if we are in cyciling mode or direct selection mode
        if ( self._typeAhead_chars.length < 2 ||
             (self._typeAhead_chars.substr(-2, 1) === c && self._typeAhead_cycling) ) {
            // If we are at the same place again
            console.debug("cycling because length " + self._typeAhead_chars.length + " and last char " + self._typeAhead_chars.substr(-2, 1));

            var $items = this.list.find( 'li a' );
            var matchee = c;

            var firstIndex = null;
            var nextIndex = null;
            // FIXME: i don't need selectedIndex, i can get it as <select>'s prop
            //var selectedIndex = null;
            var selectedIndex = $(self.element).prop("selectedIndex");

            for (var i = 0; i < $items.length; i++) {
                var thisText = $items.eq(i).text().substr(0, matchee.length).toLowerCase();

                //if ( $items.eq(i).parent('li').hasClass("ui-selectmenu-item-selected") )
                    //selectedIndex = i;

                if ( thisText === matchee ) {
                    if ( firstIndex === null )
                        firstIndex = i;

                    if ( selectedIndex !== null && nextIndex === null &&
                         selectedIndex < i )
                        nextIndex = i;
                }
            }

            console.debug(".. real selected index = " + $(self.element).prop("selectedIndex"));
            console.debug(".. search results selectedIndex=" + selectedIndex + " " +
                          "firstIndex=" + firstIndex + " " +
                          "nextIndex=" + nextIndex);

            if ( nextIndex === null )
                nextIndex = firstIndex;

            if ( nextIndex !== null ) {
            console.debug(".. activating " + nextIndex);
                $items.eq(nextIndex).trigger( eventType );
            }

            // Save the new typed character
            self._typeAhead_cycling = true;
        }
        else {
            // We are not cycling
            self._typeAhead_cycling = false;

            console.debug("selecting");

            // Choose an index based on the first match from the top
            var $items = this.list.find( 'li a' );
            var matchee = self._typeAhead_chars;

            for (var i = 0; i < $items.length; i++) {
                var thisText = $items.eq(i).text().substr(0, matchee.length).toLowerCase();
                if ( thisText === matchee ) {
                    $items.eq(i).trigger( eventType );
                    console.debug(".. .. comparing with " + thisText + " (match!)");
                    break;
                }
                console.debug(".. .. comparing with " + thisText);

            }
        }

        self._typeAhead_timer = window.setTimeout(function() {
            console.debug("typeAhead timer: clearing everything");
            self._typeAhead_timer = undefined;
            self._typeAhead_chars = undefined;
            self._typeAhead_cycling = undefined;
        }, self.options.typeAhead);
    },
```

**Comment by thg2k** [comment]
And here is the cleaned up version:

```
_typeAhead: function( code, eventType ) {
    var self = this,
        c = String.fromCharCode(code).toLowerCase(),
        items = this.list.find( 'li a' ),
        matchee = null,
        nextIndex = null;

    // Clear any previous timer if present
    if ( self._typeAhead_timer ) {
        window.clearTimeout( self._typeAhead_timer );
        self._typeAhead_timer = undefined;
    }

    // Store the character typed
    self._typeAhead_chars = (self._typeAhead_chars === undefined ? "" : self._typeAhead_chars).concat(c);

    // Detect if we are in cyciling mode or direct selection mode
    if ( self._typeAhead_chars.length < 2 ||
         (self._typeAhead_chars.substr(-2, 1) === c && self._typeAhead_cycling) ) {
        self._typeAhead_cycling = true;

        // Match only the first character and loop
        matchee = c;
    }
    else {
        // We won't be cycling anymore until the timer expires
        self._typeAhead_cycling = false;

        // Match all the characters typed
        matchee = self._typeAhead_chars;
    }

    var selectedIndex = $(self.element).prop("selectedIndex");
    for (var i = 0; i < items.length; i++) {
        var thisText = items.eq(i).text().substr(0, matchee.length).toLowerCase();

        if ( thisText === matchee ) {

            if ( self._typeAhead_cycling ) {
                if ( nextIndex === null )
                    nextIndex = i;

                if ( i > selectedIndex ) {
                    nextIndex = i;
                    break;
                }
            } else {
                nextIndex = i;
            }
        }
    }

    if ( nextIndex !== null ) {
        items.eq(nextIndex).trigger( eventType );
    }

    self._typeAhead_timer = window.setTimeout(function() {
        self._typeAhead_timer = undefined;
        self._typeAhead_chars = undefined;
        self._typeAhead_cycling = undefined;
    }, self.options.typeAhead);
},
```

**Comment by fnagel** [comment]
@danpep
Did you test thg2k's changes? Some feedback would be nice before merging it! Please comment at #181

**Comment by danpep** [comment]
I replaced my script with your function.  are the undefined timeouts or characters setable by the programmer?  I noticed some difficulty typing quick enough to trigger the multi-character selection.

**Comment by danpep** [comment]
never mind, i see it now, set to 1000 by default.

**Comment by fnagel** [comment]
Should we change the default?

**Comment by thg2k** [comment]
I'm getting very confused with these tickets, can we close all the related ones and continue the discussion in #181?
Also the code that I copy-pasted here contains some minor glitches which are fixed in the pull request.

**Comment by danpep** [comment]
I agree to move further discussion to #181 and close this ticket, the main point has been addressed
@fnagel no, I would say default 1 second is good, it's a configurable property when you call selectmenu().

**Comment by fnagel** [comment]
Agree, please comment on #181.

**Comment by fnagel** [comment]
Added in v1.2.
