### ISSUE TITLE
jQuery.data()

### ISSUE THREAD

**Issue by shub01** [fnagel/jquery-ui#178]
In my webapp I store all elements in the form with the jQuery.data() method. Also the select fields where the selectmenu plugin is applied. After replacing (jQuery.html() method) the content with the before stored object (jQuery.data()) the select fields aren't working. This means you can click on the select fields but it doesn't happen anything. The refresh, enable methods don't take an effect too.
.
Storing: $('body').data("form", $("#form").html());
Replacing: $('#form').html($('body').data('form'));

Demo:
http://jsfiddle.net/KbnSE/
(Look at the info text in the demo and try out the selectmenu.)

Please solve this in your code.

**Comment by fnagel** [comment]
Please post a demo fiddle as Im not quite sure what are you trying to achieve here. 

See #61

**Comment by shub01** [comment]
Hi fnagel

Thank you for the prompt answer. I updated my bug description with a demo fiddle.

Thanks and regards
shub01

**Comment by fnagel** [comment]
You removed the elements on which the selectmenu widget was called. You could destroy the widget before saving (so you dont have the plain added buttons in your saving) and reinit. When calling get you must reinit your selectmenus as all selects are a new HTML element injected to the DOM.
Take a look here: http://jsfiddle.net/KbnSE/3/

Im sorry but this is not a bug but normal behaviour of a UI widget. Im still not sure what exactly you like to implement, but Im pretty sure there is a better way to do so ;-)

**Comment by shub01** [comment]
Thank you very much for your help. Now it works in my application.
Regards
shub01

**Comment by fnagel** [comment]
No problem, you're welcome :-)
