### ISSUE TITLE
Support for multiple and size attribute

### ISSUE THREAD

**Issue by collincouch** [fnagel/jquery-ui#179]
The multiple="multiple" size="XX" attributes don't seem to work.   Will there be a patch to support this?

**Comment by fnagel** [comment]
There is already an issue for that feature request (see #71) but I dont think this will be implemented in this branch as there will be a new version of Selectmenu integrated in UI soon (see #140). 

The new version will not support multiple options, too. Why? See here: http://wiki.jqueryui.com/w/page/12138021/Multiselect
