### ISSUE TITLE
Disable single option (summery)

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#18]
We need to add the possibility to disable a single option within a select.

**Comment by fnagel** [comment]
This could help: http://filamentgroup.com/lab/jquery_ui_selectmenu_an_aria_accessible_plugin_for_styling_a_html_select/#commentNumber252

**Comment by tombigel** [comment]
Also - Make the ui part aware of options being disabled by javascript

**Comment by fnagel** [comment]
al did fix that, I'm waiting for his branch url to fix this issue.
http://filamentgroup.com/lab/jquery_ui_selectmenu_an_aria_accessible_plugin_for_styling_a_html_select/#commentNumber283

**Comment by fnagel** [comment]
Some more about this issue is posted here:
https://github.com/fnagel/jquery-ui/issues#issue/40

**Comment by fnagel** [comment]
Pull request (incomplete but very helpful) here: https://github.com/fnagel/jquery-ui/issues#issue/48

**Comment by fnagel** [comment]
Selectmenu now fully supports disable / enable functionality:
- All elements supported: select, options and optgroups
- Use API or set attributes on original select element
- API transfers all states to original element
- ARIA support

Please test and report as this is one of the last two issues before releasing first tagged version! Extended demo available see /demos/selectmenu/disable_enable.html

**Comment by fnagel** [comment]
Here are some accessibility issues: https://github.com/fnagel/jquery-ui/issues/89

**Comment by fnagel** [comment]
Any feedback on this new feature or could this issue be closed?
