### ISSUE TITLE
Selectmenu opening upwards when in in overlay

### ISSUE THREAD

**Issue by finny310** [fnagel/jquery-ui#182]
Hi Felix,
Great work! I have a question - i have a select menu in an overlay. The dropdown has 31 entries and is opening upwards instead of down and so it's going off the top of the viewport but the user can't scroll to it. Is this a bug or is there a setting i can change?  I have a screen shot, not sure how to post it on here.

**Comment by fnagel** [comment]
Please try to type "m" when not in the form (here at GitHub) or use an image
hoster. A demo fiddle would be nice too! See #61

**Comment by finny310** [comment]
![screenshot](http://i51.tinypic.com/z7uh2.png)

**Comment by finny310** [comment]
thanks Felix. I'm not sure i can put the code on jsfiddle, the pages are jsp

**Comment by fnagel** [comment]
Did you tried the maxHeight option?

**Comment by finny310** [comment]
i'll try max height now

**Comment by finny310** [comment]
is maxHeight an option for selectmenu? i tried maxHeight: 100 and there was no change  
$("#signUpForm select").selectmenu({
        maxHeight: 100,
        change:function(e){
        GlobalJS.Utility.clearSelectFieldError(e,$(this));
    }});

**Comment by fnagel** [comment]
Correct. maxHeight forces a scrollbar within the menu. See the default demo
file.

Are you able to provide a stripped down demo fiddle so Im able to
investigate the problem?

**Comment by finny310** [comment]
i'll try to get the scroll working. i think my code has too many dependencies for jsfiddle
