### ISSUE TITLE
Several mis-calculations with automatic width

### ISSUE THREAD

**Issue by thg2k** [fnagel/jquery-ui#183]
Please see the following test case:
http://thgnet.it/stuff/data/selectmenu-bug-autowidths.html

It highlights the following problems:

1) When options are all the same length, the width is calculated in the wrong way. I worked around it by adding a fixed 10 px (which is enough in my layout) to o.width when it is calculated from .width(), but of course it's a hack and we should study a proper solution.

2) Not sure how this one is calculated, but i'm sure that the inside "pre-calculated" should stay in the same line..at least that one! Don't you think anyway that choosing longest option would be better? I think the builtin combo box does exactly this.

3) Well, here the problem is quite evident..i think this bug was introduced with the wrapper change, because in my website it works in this case, but i got rid of the wrapper element!

I think these are showstoppers for 1.2 release, the 1) and 2) actually existed for a long time, that's why i worked around them in my production website, but the third one is kind of new.

**Comment by thg2k** [comment]
You might want to take a look at this:
https://github.com/thg2k/jquery-ui/commit/1fdd7f92193aee3928af471b77e572b79eb4e12e
It addresses a couple of problems even though is based on my fork..

**Comment by fnagel** [comment]
1) There are 2 ways to fix this: specifiy a width for original select or use width option. I will not fix ANY use case, the sourcecode is already way too big.

2) I see the problem but what if a you would like to have multi line option? We use this in our projects as there is limited space available in our form. We could implement something that checks for the longest option. Perhaps menuWidth is default to menu, could be switched to a number or auto (which takes care of the longest option)? What do you think?

3) Should be easy to handle, just init the widget on click (after using show()) or use jQuery Peek (see the Wiki).

About your fixes:
I dont think adding a fixed number is a solution as you can change padding, margin, icon width for a specific design.

ps: Seems not like show-stopper to me (but #147 is) but anyway, Im way too tired to prepare the release :-(

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
