### ISSUE TITLE
style:'popup' no longer works correctly

### ISSUE THREAD

**Issue by mherbold** [fnagel/jquery-ui#184]
I just updated to the latest version of selectmenu because I updated to jquery-1.6.2 and jquery-ui-1.8.16.  After updating, I saw that the positioning of the popup no longer works correctly.  It worked in the older version of selectmenu that I was using.  With the new version of selectmenu if the pop up needs to be forced down or up due to limitations of window size, it puts it too high or too low.  I will try to make a test case for you.  Please let me know about how long it will take to fix this - if it will be more than a few weeks then I must go back to the older version.

**Comment by mherbold** [comment]
It turns out I do not need to make a reproduction case for you - it breaks in your own demo.  Go to your demo page for selectmenu named "default.html".  In the second selectmenu on that page (the one that says "default popup" style with maxHeight set and custom wrapper) just select one of the bottom-most items like "6 faster". Then click on the select menu again - you'll see that the popup now appears near the bottom of the page.

**Comment by fnagel** [comment]
Im really happy to get some feedback on my latest commit, so: thanks a lot! :-)

Please test the latest commit. Seems to be fixed, but Im struggling since a few month (!) to find a solution for the reported problems (please see and comment on #147).

Perhaps you should test the new, built from scratch version of Selectmenu (see #140).

I will close this issue to focus all feedback at #147

**Comment by mherbold** [comment]
I got the latest version and it seems to be fixed.  Thanks!  I also appreciate that type-ahead is working now - it was not working in the old version I had (only worked on the first letter).  Does your new built from scratch version of Selectmenu work with jquery ui 1.8?  Or is it 1.9 only?

**Comment by fnagel** [comment]
Nice! Thats the news I wanted to hear :-)
Mhh I did not change anything about the type ahead functionality, but there are upcoming changs, see #181
Yes, you will need to use the new Menu Widget and an updated Widget factory.

**Comment by mherbold** [comment]
The version of selectmenu I have been using before updating it yesterday is pretty old - I think I last updated it late 2010 or early 2011.  Type ahead was definitely not working in that version.  :-)

jQuery 1.9 should be awesome, but I can't update to it until it's been officially released and relatively bug free, because this stuff is being used on a live production website with many federal government customers and we can't allow to have something not work. :-)

Thanks for all your good work!

**Comment by fnagel** [comment]
Thats possible :-)

Yeaah. In most of my project I need to stick to the old version, too :-(

Are you able to provide a real world example when your project is finished? Please see #60

**Comment by mherbold** [comment]
I may be able to provide you with a login to access a test version of our website so you can see how selectmenu is being used in our project.  I would need to set up a clone of our project and wipe all data from it (we have sensitive federal customer data that we can't share with the public).  Our project is actually done but we are constantly adding new features and functionality to it.

Can you provide me with a private email address that I can send login information to?

**Comment by fnagel** [comment]
Ahh no, thats not what Im searching for. I would like to have some examples in real websites as a showcase, but thanks for your commitment.
