### ISSUE TITLE
transparent background on some list items, unwanted horizontal scrollbar

### ISSUE THREAD

**Issue by wakingweb** [fnagel/jquery-ui#185]
Although the latest development version fixes an issue with jumping to the top of the screen on first click (even when i changed the hrefs to something other than "#", the "jumping" was still happening in version 1.1.0)...

I now have an issue where the height of the ui-widget ul does not expand to fully encapsulate it's children.  This was causing a transparent background on a bunch of the bottom list items.  This also added an horizontal scrollbar which was not cool.

Adding overflow: auto to ul.ui-widget seems to fix it.

**Comment by fnagel** [comment]
Sadly I needed to push another commit to fix the mentioned jumping problem. You should update your code.

Can you provide a demo fiddle (see #61) for you problem? Im not quite sure what to do to reproduce the problem.

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by wakingweb** [comment]
I will provide more feedback soon, sorry for the delay!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given.
