### ISSUE TITLE
Original select element is not getting updated when the selectmenu is changed

### ISSUE THREAD

**Issue by x10** [fnagel/jquery-ui#186]
The original select element is not having the selected="selected" attribute applied to it when the selectmenu is changed. 

The onChange event of the original select is used to trigger other scripts in my code. Is there a workaround?

**Comment by fnagel** [comment]
Are you aware of the change callback event?

See https://github.com/fnagel/jquery-ui/wiki/Selectmenu

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Closed as no feedback was given, please reopen if needed.
