### ISSUE TITLE
Selectmenu width in dialog

### ISSUE THREAD

**Issue by netcelli** [fnagel/jquery-ui#187]
I have a problem when using selectmenu-1.2.0 in dialog. Widget width is always set  to 6px when <select> has outerWidth bigger than this value. 

``` javascript
       // set width when not set via options
        if (!o.width) {
            o.width = this.element.outerWidth();
        }
```

If I print this.element.outerWidth();it returns 6px instead of correct width. Thanks :)

**Comment by fnagel** [comment]
Did you check the dialog demo.html within the demo directory?

Should work afaik. Are you able to provide a demo fiddle? See #61

**Comment by netcelli** [comment]
Sorry I can't provide a online demo. From demo it works, but if I set a width to <select> then JS sets correct width

**Comment by netcelli** [comment]
If you remove select { width: 200px; } from dialog.html in demo folder and you open the dialog you will see that selectmenu width is set to 2px

**Comment by fnagel** [comment]
You need to set at least one width: via CSS or by option.

**Comment by netcelli** [comment]
But for other select menus in the page I do not set width attribute and they work

**Comment by fnagel** [comment]
Mhh, so some Selectmenu widgets "find" a width and some not? I would assume none of them get a proper width. What I can say is that setting no width at all should break the widget, but I would need a test case or a demo fiddle for that.

**Comment by netcelli** [comment]
Here i just copy the selectmenu/dialog.html demo: http://jsfiddle.net/netcelli/Uz9c3/

**Comment by fnagel** [comment]
You need to change the order of your initialisation. See here: http://jsfiddle.net/Uz9c3/1/
But it wont work as the options are too short.

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Closed as no feedback was given, please reopen if needed.
