### ISSUE TITLE
Original select's change event

### ISSUE THREAD

**Issue by amit-goyal** [fnagel/jquery-ui#188]
Is a way to associate the original dropdown's change event to the generated dropdown's value? 

I have a piece of code that's targeting the original selectbox's selection which fails to change the generated selectbox's selection.

**Comment by fnagel** [comment]
No, this is not supported. And even the new, built from scratch version (see #140) will not support that feature. It needs event pulling which is "bad".

Perhaps I could help when you tell me what you want to achieve?

**Comment by amit-goyal** [comment]
Agreed, it goes against every fiber of my being but I can't change the script; it's already in production and I don't have the authority to modify it.

Anyway, here's the scenario,

There are four swatches which when clicked select the relative value from the original select box and vice versa. The latter scenario works perfectly fine, the former however, does not. 

Now, I can't target the onChange event of the original select boxes because they're autogenerated (I'm targeting select boxes through '#content select'), so I need a generic way to target the original selectbox's change event to bring the selection of the generated selecbox in-sync when one of the swatches is clicked.

i.e.
oSelectBox -> When changed, selects the relative swatch.
A   B   C  D -> When clicked changes the original selectbox.
gSelectBox -> Selects the relative swatch but does not change based on the relative swatch.

Any help would be greatly appreciated.

**Comment by fnagel** [comment]
Mhh ok, when you HAVE to do it that way why not built a event pulling functionality? Just check the original select via timeout or intervall every 500ms and update the widget with the available methods. Should be no big thing.

**Comment by fnagel** [comment]
Mhh and when onChange would be suitable why not use $('#content select').change() or $('#content select').bind("change", ?

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Closed as no feedback was given, please reopen if needed.
