### ISSUE TITLE
The calculation of the menu height is flawed

### ISSUE THREAD

**Issue by Cito** [fnagel/jquery-ui#189]
In selectmenu 1.2.0, the height of the menu is set using the following code:

``` javascript
// calculate default max height
if ( o.maxHeight && o.maxHeight < listH ) {
this.list.height( o.maxHeight );
} else {
var winH = $( window ).height() / 3;
if ( winH < listH ) this.list.height( winH );
}
```

The logic here seems a bit flawed. Let's assume our window is 300px high.

Now if the menu is 150px high and I set maxheight to 200px, the height
will still be cut back to 100px.

On the other hand, if the menu is 500px high, and I set maxheight to 200px,
the height will be set to 200px. Even worse, if I set maxheight to 400px,
then the height will be set to 400px even though the window is only 300px high.

This behavior does not seem to make sense to me.
I would expect a logic that is more like this:

``` javascript
var winH = $(window).height();
var maxH = o.maxHeight ? Math.min(o.maxHeight, winH) : winH/3;
if (listH > maxH) this.list.height(maxH);
```

But even with this fix, there are still two other flaws:
- If the user resizes the window, the list heights are not adapted.
- Even winH/3 can be too large when the menu is at the top or bottom
  edge of the menu. In this case, the menu position should be adapted
  so that the menu fits on the screen.

**Comment by Cito** [comment]
Also, you can't specify maxHeight with units, like '20ex', you can only specify it as a number,

**Comment by fnagel** [comment]
Hey @Cito, 

thanks for your contribution! I really like to improve height calculation as we have some comlaints about this some time ago (see #, take a look @ ). 

Would you like to develop a patch for the open issues? Im currently pretty busy so otherwise I would add your current patch and open a new issue for the open issues.
Please note. menu positioning could be changed by using positionOptions.collision, see http://jqueryui.com/demos/position/

What is format is 20ex? I know 20em but ex?

**Comment by Cito** [comment]
Yes, the Position utility is the way to go. This probably needs some serious refactoring. But unfortunately I'm in the same situation, too busy with other stuff.

"ex" is a relative CSS unit, 6px for normal fonts. It is more appropriate for specifying heights, while "em" makes more sense for specifying widths. But the problem here is that you can't specify maxHeight with any units.

**Comment by fnagel** [comment]
So I will include your fix after I did some testing and we'll see what we can do with position later?

Mhh, as jQuery UI does not support relative width and height at all Im not willing to implement this atm.

**Comment by fnagel** [comment]
Ive implemented you patch. Thanks for your contribution.
Please test the latest commit and give feedback!

Positioning issues can be solved by using collision. Ive tried to improve the current auto collision settings, but if a custom setting is needed just set it via positionOptions.

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by Cito** [comment]
Looks good to me, thanks.
