### ISSUE TITLE
selectmenu theme to match regular select look and feel

### ISSUE THREAD

**Issue by csaket** [fnagel/jquery-ui#193]
I have been trying to style the selectmenu to match the html select dropdown but so far my attempts have been failures.
Has anyone done this or know which styles to change to enable this?

**Comment by fnagel** [comment]
Im currently not aware of a UI CSS style which makes this possible. You should try the themeroller to make your own: http://jqueryui.com/themeroller/

Please note: As every OS (Operating System) has its own style for standard form elements you will need to make different style sheets for every OS. On a Windows a select looks different from an MAC select. Even some OS versions have different styles (for example WinXP and Win7 look different).

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by csaket** [comment]
I tried for a day but could not get it to match exactly.
