### ISSUE TITLE
Select menu slides under the handles on jQuery UI slider

### ISSUE THREAD

**Issue by dougwo** [fnagel/jquery-ui#194]
I have a slider just below my drop-down select box and the handle (only the handle!) appears on top of the select box contents. I searched using firebug and it appears as though the handle is at z-index = 2. So I tried the following:

```
$(".myselect").selectmenu({
            style:'dropdown',
            maxHeight: 150 
        }).css('z-index','100'). change(function() {
            var mid = $(this).attr("id").substr(1);
            var item = $('#g'+mid+' :selected').val(); 
            $.ajax({ url:"/blah blah blah });
})
```

but it didn't work. Any other ideas?

**Comment by fnagel** [comment]
Mhh, try to change the zIndex of the original select. Selectmenu widget uses the zIndex of the original element +1 to set its zIndex (common jQuery UI way to do this).

**Comment by dougwo** [comment]
I tried setting the z-index of select to 2, 10, 100 1 d 1000 and none worked. Just the handles on the slider bar under it jump up on top. Really strange.

**Comment by fnagel** [comment]
Would you please create a demo fiddle (see #61), I will take a look!

**Comment by dougwo** [comment]
Can't figure out fiddle... :) Here is a link to a very simple test file: http://www.publishmymusic.com/test

**Comment by dougwo** [comment]
Any luck? I am still stuck.

**Comment by fnagel** [comment]
Issue confirmed, see: http://jsfiddle.net/fnagel/PKnky/1/

**Comment by fnagel** [comment]
Just add a postion and a z-Index to the original select: http://jsfiddle.net/fnagel/PKnky/4/

**Comment by dougwo** [comment]
Ah! The position fixed it! Thank you.
