### ISSUE TITLE
enhancement (with source): for 'format', make option node available.

### ISSUE THREAD

**Issue by matthucke** [fnagel/jquery-ui#199]
Selectmenu presently provides a 'format' callback in the options object, allowing the user to transform the text from the initial HTML option into something different for the selectmenu's 'li' element.

In my uses of selectmenu, I have often found the need for more information in the transformed 'li' element than was in the original 'option' element.  For example, consider a colour picker for an online shopping cart.  The original option should just display the colour name, but the selectmenu equivalent would also show an icon, whether that colour is in stock, pricing data, etc., none of which are easily obtainable from the colour name.

SUGGESTED ENHANCEMENT:

Pass a second parameter to the 'format' callback - this would be the jquery object representing the original option node whose text is being rewritten.  Because the first parameter is still simply the text, this is backwards compatible.  

DIFF:

```
281c281
<                                       text: self._formatText(opt.text()),

---
>                                       text: self._formatText(opt),
628,629c628,629
<       _formatText: function(text) {
<               return (this.options.format ? this.options.format(text) : text);

---
>       _formatText: function(opt) {
>               return (this.options.format ? this.options.format(opt.text(), opt) : opt.text());
```

EXAMPLE USAGE:

```
$('.foo').selectmenu({
    format: function (text, opt) { 
        // various operations on opt.attr('id'), opt.attr('class'), etc.
       return "new label for value : " + opt.attr('value');
    }
});
```

**Comment by fnagel** [comment]
Thanks for your contribution! Im pretty busy right now, but I will definitely take a look. This is a one man show and I have only a certain amount of spare time to maintain selectmenu.

Please check out #106 which seem to aim a similar approach.

Did you know there is another Selectmenu (built from scratch) which will be included in jQuery Ui 1.9.x? Its still under development and has some issues with Menu widget atm. See #140

Example how to render custom items in Selectmenu "2.0": https://github.com/jquery/jquery-ui/blob/selectmenu/demos/selectmenu/custom_render.html

**Comment by fnagel** [comment]
Please note: this issue seems to be solved within this pull request: #257

Please test and give feedback!

**Comment by fnagel** [comment]
Any feedback in this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
