### ISSUE TITLE
Hover style

### ISSUE THREAD

**Issue by netcelli** [fnagel/jquery-ui#203]
When you go hover a selectmenu both ui-selectmenu-focus and ui-state-hover classes are added. So I can't set a different style for focus and hover status.

**Comment by fnagel** [comment]
Thanks for your contribution! 

Seems like a problem to me, too. 

Should be fixed asap. Are you able to provide a fix?

**Comment by netcelli** [comment]
I send a new pull request. I tested the fix on my code and it works :). I split mouseover.selectmenu focus.selectmenu events

**Comment by fnagel** [comment]
Thanks I will take a look asap. Pretty busy atm.

**Comment by fnagel** [comment]
I will close this issue please comment on the pull request!
