### ISSUE TITLE
Problem with refreshing

### ISSUE THREAD

**Issue by s7anley** [fnagel/jquery-ui#204]
Hi,

thank you for updating this plugin.

Today I found some bugy behavior. I have 2 selects on page. One option in every select is special, if user choose it, it must change it to same value in another select too. So that's why i need refresh this select. 

```
if($(this).val()=='t1'){
    if($(this).hasClass("tutorial_am")){        
        select = $(this).parent().next().find("select");                
    } else {
        select = $(this).parent().prev().find("select");                
    }
    select.val('t1').selectmenu();      
}
```

After this, refreshed selectmenu doesn't work in IE 8 and below. After click on select nothing change. Also doesn't render it good in other browser (exception Firefox and Internet Explorer 9). See links. After click it doesn't render list I need hover it and then options are shown.

![Alt text](http://img542.imageshack.us/img542/2809/24927406.gif)
![Alt text](http://img708.imageshack.us/img708/913/96330976.gif)

Is this just my problem? I'm using jQuery v1.4.3, jQuery UI 1.8.13 and latest select menu plugin.

Thanks for respond

s7anley

**Comment by fnagel** [comment]
Mhh I have no idea whats the problem here. Please post a stripped down demo fiddle so I can investigate the problem, see #61.

```
select.val('t1').selectmenu(); 
```

What is val('t1') about?

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Closed as no feedback was given.
