### ISSUE TITLE
The computed width is different from the set width

### ISSUE THREAD

**Issue by oleersoy** [fnagel/jquery-ui#206]
See:
http://jsfiddle.net/cKVB5/2/

Both the button and the selectmenu have a configured width equal to 250px.  Firebug reports that the computed width of the button is 250px.  The computed width of the selectmenu is 211px.

Another thing that one notices when putting a button next to a selectmenu instance is that the button will center it's content by default, but the selectmenu left aligns the selection.  It would be nice if the default behavior was consistent across widgets.

**Comment by fnagel** [comment]
Your input has additional padding. Thats why its bigger. The selectmenu a tag has 250px (Firebig computed).

Mhh thats true but a native select has its text-align left. What is more important? Im pretty sure if I change this a lot people will complain that the selectmenu has centered text.

**Comment by oleersoy** [comment]
AH - You are right.  I played with it a little more aligning the text on the button to the left and now the form looks good.  

Some extra notes, in case you know the button designer :)  (Let me know if you think I should open another ticket for the button).  I think the button design should be changed slightly.  It should have text-align default to left and the left padding default value should be set such that text in the button and text in the selectmenu are aligned.  Also it would be great if the button had a "width" property that could be set such that the button total width corresponded with the selectmenu total width.

**Comment by fnagel** [comment]
In this version of selectmenu I am the button designer, but its style is related to jQuery UI button.

Please show me an example of what you want to achieve in a new issue, I do not understand whats the reason for your proposed change.

**Comment by oleersoy** [comment]
Scratch the comment.  Since JQuery UI is missing input text and text area plugins, I just assumed that the button was intended to be used across the board.  However I see that input text and text area components are on the 2.0 roadmap.

I started working on these plugins.  I'll get them on github asap.  Would love to hear what you think.  I'm modifying the button plugin for this.  My first two priorities are to line up content with the select menu and disable active "Flashing" when the space and enter keys are pressed.  Then I'll start thinking about the disable and refresh semantics, etc.  Please let me know if you have any thoughts / input.

**Comment by fnagel** [comment]
Just let me know if theres something I could take a look at.

Please note there is already a new selectmenu version in development, see #140

**Comment by oleersoy** [comment]
I just uploaded a "jquery.ui.input" (for input and textarea) plugin to a fork of this repository.  I'm hoping jquery.ui will be able to use this.  You can find it here:

https://github.com/oleersoy/jquery-ui/blob/selectmenu/ui/jquery.ui.input.js

And demo here:

https://github.com/oleersoy/jquery-ui/tree/selectmenu/demos/input

Thanks - I've been meaning to switch over to the <a href="https://github.com/fnagel/jquery-ui/issues/140">#140</a> selectmenu.  I'll start testing with that as soon as I get a beta done of the project that I'm using the current selectmenu in.

**Comment by oleersoy** [comment]
And more importantly - Happy New Year!!!
