### ISSUE TITLE
Small patch for the selectmenu

### ISSUE THREAD

**Issue by dtpop** [fnagel/jquery-ui#207]
Dear all,

thanks for the great work.

I just had a small problem with the height of the opened select. It calculated a smaller height than the real height of the box. So i tried this:
$('select#sel-product').selectmenu({maxHeight:'auto'});
but it did still show a smaller box with scroll bars.

So I patched the jquery.ui.selectmenu.js about line 423:

old code:

```
if ( o.maxHeight && o.maxHeight < listH ) {
...
```

to new code:

```
if ( o.maxHeight && o.maxHeight < listH || o.maxHeight == 'auto') {
...
```

and everything works fine now and I can assign the auto hight.

Best regards,
Wolfgang

**Comment by fnagel** [comment]
Ive lately adjusted the height calculation as proposed in #189 
Please test if the latest commit still has issues in your specific use case. 

Please post a step by step description how to reproduce your problem. 
A demo jsFiddle would be great, see #61

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by dtpop** [comment]
I just tested the patch and it works fine. Thanks!

**Comment by fnagel** [comment]
Closed as solved.
