### ISSUE TITLE
ul cleanliness

### ISSUE THREAD

**Issue by phazei** [fnagel/jquery-ui#21]
The ul's are all stored in the root body of the dom, it would be better if they were all contained in a div with class jqui-selectmenu, or something.

also:how do I apply labels to an issue?

**Comment by fnagel** [comment]
Would be an idea, but this a low priority issue as most plugins inject their layer elements to the root element.

Sorry, afaik your not able to do this, but you could go to the detail view of the issue, than click on one of the color icons (next to the labels) on the left side to open the context menu.

**Comment by fnagel** [comment]
We would need to reorder the elements in the wrapper div and the wrapper div itself. I will close this issue as Im not willing to add extra code to the widget for cosmetic changes. Sorry.

**Comment by phazei** [comment]
Actually, I beg to differ;  I don't believe it would be for cosmetic changes only.  By putting all the elements within a parent element, it should speed up the searching of the elements in the dom.  The parent element could be selected once then cached and then selecting any of the children should be much faster.

parent = $('.jqui-selectmenu');
parent.find('child_element');

**Comment by fnagel** [comment]
This speed gain should be almost nothing as the elements could be selected as
    $("body").children("LIST_ELEMENT")

Actually the list is already cached (this.list) so there is no need for faster selection at all.
