### ISSUE TITLE
Corners rounded incorrectly when menu appears above element

### ISSUE THREAD

**Issue by wyqydsyq** [fnagel/jquery-ui#210]
When the menu itself appears above the button, the top corners of the menu should be rounded rather than the bottom corners

**Comment by fnagel** [comment]
Thats not possible as Im not able to know what postiton plugin will use
(above, beneath or something between). Disbale collision option (for
position plugin) to avoid appearing above the button.
Whole problem should only appear when only minimal space is provided.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given.
