### ISSUE TITLE
Opera Event "change", submit form doesn't work. 

### ISSUE THREAD

**Issue by WDConcept** [fnagel/jquery-ui#212]
When you use selectMenu in a simple html form and you want submit this form with the submit function, it doesn't work in Opera. You are redirect on your home page.

Exemple :

<pre>
$('.select-sorts').selectmenu({
    width: 210,
    maxHeight: 250,
    change: function(){
        $(this).parent().submit();
    }
});
</pre>

<pre>
&lt;form action="link/to/action" method="post" class="list-sorts"&gt;
    &lt;select name="sorts" class="select-sorts"&gt;
        &lt;option value="val1" selected="selected"&gt;val1&lt;/option&gt;
        &lt;option value="val2" &gt;val2&lt;/option&gt;
        &lt;option value="val3" &gt;val3&lt;/option&gt;
        &lt;option value="val4" &gt;val4&lt;/option&gt;
        &lt;option value="val5" &gt;val5&lt;/option&gt;
    &lt;/select&gt;
&lt;/form&gt;
</pre>

**Comment by fnagel** [comment]
Works for me in Opera 11.61 on Win7:
http://jsfiddle.net/GXtpC/277/

Please test and give feedback!

**Comment by WDConcept** [comment]
Sorry, I have extract selectmenu of my system and it work on Opera. The problem comes from my site.
Thank for your interest.
