### ISSUE TITLE
Type-ahead doesn't work with jQuery 1.7.1

### ISSUE THREAD

**Issue by cberner** [fnagel/jquery-ui#213]
type-ahead in the selectmenu doesn't work properly (highlighting doesn't work, and arrow keys don't work) when used with jQuery 1.7.1, even though it seems to work with 1.6.2

**Comment by ubuntux** [comment]
This bug is proven... I had the same issue when I tried to upgraded jQuery from 1.6.2 to 1.7.1

**Comment by fnagel** [comment]
Any idea how to fix this?

**Comment by cberner** [comment]
Unfortunately not, I ended up using a different library instead.

On Wed, Feb 22, 2012 at 1:33 PM, Felix Nagel <
reply@reply.github.com

**Comment by fnagel** [comment]
Ive just updated Selectmenu to jQuery 1.7.2 and can confirm this problem. Any help is appreciated!

**Comment by fnagel** [comment]
Ive just tested this again and it seems it works pretty normal. Tested in latest FF, IE9 and IE7.

Please test latest commit and give feedback!

**Comment by cberner** [comment]
Going to be at Google I/O this week, but I'll try to test it out next week, and let you know!

**Comment by fnagel** [comment]
There is a confirmed issue when using up down arrow in opened menu, see #240

**Comment by cberner** [comment]
Ok cool, well I'll try to test it after that's fixed then

**Comment by fnagel** [comment]
Above mentioned issue seems to be fixed with #247. Please test and give feedback!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by cberner** [comment]
Still seems like it's not working. I didn't do the implement myself (my partner did), but you can see it on our site: http://carsabi.com/car-search/

**Comment by fnagel** [comment]
Mhh this seems to be related to your specific website. I'm not able to reproduce it in a fiddle. Are you?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as issue seems to be solved. Please reopen if needed.
