### ISSUE TITLE
Transparent background on non-hovered items

### ISSUE THREAD

**Issue by Ged-an** [fnagel/jquery-ui#215]
Hello,

I use Google Chrome (v.16) on Windows Seven.

On the Demo, the problem doesn't appear : http://jsfiddle.net/GXtpC/289/

A screenshot : http://img1.sunderpicture.com/_/3/select_bug-35a22e7707f47fbfb365ecd552235ed0.png

I tried to reinitialize main theme, disable all plugins and css : same problem.

Is it a bug ? Thanks

**Comment by Ged-an** [comment]
Finally I found a problem inside jquery's CSS. There was not a bug from your plugin. Sorry.

**Comment by fnagel** [comment]
No problem, glad you solved your issue!
