### ISSUE TITLE
When placed inline with jQuery ui buttons the select menu does not line up.

### ISSUE THREAD

**Issue by RichardAlan** [fnagel/jquery-ui#221]
When I place a select inline with two links and apply jQuery to make these into a select menu and two buttons then the three widgets do not line up. The select menu (when closed) appears 2-3 pixels lower than the buttons.

**Comment by fnagel** [comment]
This should be fixed already in #166

Please post a jsFiddle, see #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
