### ISSUE TITLE
transfer classes

### ISSUE THREAD

**Issue by DR9885** [fnagel/jquery-ui#227]
Currently if the Option for "transferClasses", will transfer the classes. but if you try to reinitialize it will just add more classes... I assume it's supposed to follow the classes exactly... if not there should be a "refresh" method or something... otherwise I've listed a quick fix.

```
        // transfer classes to selectmenu and list
        if (o.transferClasses) {
            this.newelement.add(this.list)
                .removeClass(this.transferClasses || '')
                .addClass(this.transferClasses = this.element.attr('class') || '');
        }
```

**Comment by fnagel** [comment]
Option transferClasses is obsolete and will be removed. And you're right its faulty :-)

Please use common jQuery UI widget method, like this:

```
$('select#speedAa').selectmenu("widget").addClass("wrap");
```

**Comment by fnagel** [comment]
Any feedback on this issue?
