### ISSUE TITLE
Problem with id attribute containing colon in Firefox 

### ISSUE THREAD

**Issue by ghost** [fnagel/jquery-ui#230]
I have problems witch such select in FF

```
<select id="one:two">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
</select>

```

it dont display selected value. IE has no problem with it. problem is that some code which escapes ':' character as ':'.
Pls who knows how to solve this problem, is it bug?
THx for any help

**Comment by fnagel** [comment]
This is a problem. Ive pushed a patch. Please test and give feedback!

Related to: #163 & #176

**Comment by ghost** [comment]
Great, now it works, thx !!!

**Comment by fnagel** [comment]
Great, thanks for your fast feedback!
