### ISSUE TITLE
Selectmenu open list breaks off from the element inside a fixed div

### ISSUE THREAD

**Issue by AlexMxm** [fnagel/jquery-ui#231]
When the selectmenu is inside a fixed div that can be dragged, or inside a fixed div that stays fixed when the document is scrolled, the selectmenu element stays with the fixed div, but the absolute positioned open selectmenu list detaches and stays with the document.

Open lists need to be created relative to the selectmenu element itself, not absolutely positioned relative to the document body.

Thank you,
Alex

**Comment by fnagel** [comment]
Hey Alex,

creating the menu relative to the selectmenu wont work. There's a reason
every Lightbox, Layer, etc. injects its HTML to the end of the body.
Im not quite sure what youre trying to do but I think its an edge case
which needs some custom code.

Perhaps Im able to help if you post a demo fiddle, see #61.

**Comment by AlexMxm** [comment]
Hi, thanks for the reply. I found a workaround by triggering $(document).trigger("mousedown"); when the drag or scroll starts. It closes the open selectlist.

**Comment by fnagel** [comment]
Great to hear! Would you mind post your snippet here so we have the solution documented?

**Comment by AlexMxm** [comment]
http://jsfiddle.net/AlexMxm/K6J7s/
should show the issue and the solution

**Comment by fnagel** [comment]
Thanks for your contribution!

Just to be sure, if the jsfiddle will be removed sometime:

```
$(window).scroll(function() { $(document).trigger("mousedown"); }); 
```

Closed as solved and documented.

**Comment by karlwestin** [comment]
Just a side note, since i was coming across the same issue:
I think what you want is to use the "appendTo" option, that selects which element the list gets appended to.

Check the example here:
http://jsfiddle.net/K6J7s/2/

(only the two first select-menus)
This one works even before clicking "trigger mousedown event"

Cheers guys!

**Comment by AlexMxm** [comment]
Cool. Thank you, Karl! That's what I needed.

**Comment by fnagel** [comment]
Nice to see you guys helping out each other -- I really need a helping hand here :-)
