### ISSUE TITLE
Selectmenu: list of options away from select

### ISSUE THREAD

**Issue by amacgyver** [fnagel/jquery-ui#232]
Hello,

my issue is the position of the list of options clicking the `select`: it appears at the top left of the page.
Using `appendTo` to insert the code in the same `div` of the `select`, the list appears at the top of the page ouside the `div`. Then assigning  the style `position:relative` to this `div` the list appears on top of itself.
Maybe I'm not paying attention to something. Could you point me in the right direction?

Thanks

**Comment by fnagel** [comment]
Could you provide a stripped down demo fiddle? Its very easy, just take a
look here: #61

Why do you need to adjust the appendTo option? It should be used in very
specific situations only.
Checked the needed CSS?

**Comment by amacgyver** [comment]
Thanks for your answer.
I can't reproduce this issue on jsfiddle because it doesn't happen there!!
I get a very strange problem... opening in the same browser (FF 12 or Chrome 19) the page (below added) sended by my development server (wamp) the list of options appears away from the select (at the top left corner of the page).

&lt;html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"&gt;
  &lt;head&gt;
    &lt;link rel="stylesheet" type="text/css" media="screen" href="http://github.felixnagel.com/selectmenu/themes/base/jquery.ui.core.css" /&gt;
&lt;link rel="stylesheet" type="text/css" media="screen" href="http://github.felixnagel.com/selectmenu/themes/base/jquery.ui.theme.css" /&gt;
&lt;link rel="stylesheet" type="text/css" media="screen" href="http://github.felixnagel.com/selectmenu/themes/base/jquery.ui.selectmenu.css" /&gt;
    &lt;script type="text/javascript" src="/js/frontend/jquery-1.7.2.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/js/jquery.ui.core.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/js/jquery.ui.widget.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/js/jquery.ui.position.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/js/jquery.ui.selectmenu.js"&gt;&lt;/script&gt;
    &lt;script type="text/javascript"&gt;
$(document).ready(function() {
  $('select#models').selectmenu({
    width: 300,
    style:'popup'
  });
});
&lt;/script&gt;

  &lt;/head&gt;
  &lt;body&gt;&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;
    &lt;div&gt;
  &lt;label for="models"&gt;Select:&lt;/label&gt;
  &lt;select name="models" id="models"&gt;
      &lt;option value = "A"&gt;A | A description&lt;/option&gt;
      &lt;option value = "B"&gt;B | B description&lt;/option&gt;
      &lt;option value = "C"&gt;C | C description&lt;/option&gt;
      &lt;option value = "D"&gt;D | D description&lt;/option&gt;
    &lt;/select&gt;
&lt;/div&gt;

  &lt;/body&gt;
&lt;/html&gt;

**Comment by fnagel** [comment]
Mhhh, seems to work for me. Would you mind to upload a demo zip? I need to
reproduce the problem in order to help!

And: please do not link to my server, save the files or get them at GitHub!

**Comment by amacgyver** [comment]
Hi,
I found the cause of the problem, a my stupid mistake!
In the project in my development server I already was using the jquery ui slider. I added the file js `ui position` in not minified version but I linked the minified one. Strangely I never had errors from the console.
I'm sorry I wasted your time. Thanks again.

**Comment by fnagel** [comment]
No Problem.  Im glad you found the issue.
