### ISSUE TITLE
Disabled/Selected first option will not show

### ISSUE THREAD

**Issue by ryanshrum** [fnagel/jquery-ui#233]
Is it possible to add a text like "Please choose..." and have it there before click (even after click), make it "disabled". It worked fine until I added the script. Or if there's a callback function I can add the Label value as the first option. Thoughts?

``` html
<select>
<option selected="selected" disabled="disabled">Please choose...</option>
<option>1</option>
<option>2</option>
</select>
```

**Comment by fnagel** [comment]
Closed as duplicate.
