### ISSUE TITLE
Disabled/Selected first option will not show

### ISSUE THREAD

**Issue by ryanshrum** [fnagel/jquery-ui#234]
Is it possible to add a text like "Please choose..." and have it there before click (even after click), make it "disabled". It worked fine until I added the script. Or if there's a callback function I can add the Label value as the first option. Thoughts?

``` html
<select>
    <option selected="selected" disabled="disabled">Please choose...</option>
    <option>1</option>
    <option>2</option>
</select>
```

**Comment by fnagel** [comment]
Mhh this (disbale single options) should be possible without problems. Please take a look at the enabled_disabled.html demo!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by ryanshrum** [comment]
Thanks for following up Felix. I should have closed the ticket. I ended up using a different plugin as I needed to offer multi-select as well. Thanks for your prompt support.

**Comment by abloore** [comment]
I know this issue has been closed, but I am having the same issue. I know that you are able to disable single options, but it looks like issue that the original reporter is talking about still exists:

If the first option in the HTML select is disabled via the "disabled" attribute AND set to "selected", then the selectmenu widget will not display the selected option as the label.

Example:

``` html
<select>
    <option disabled="disabled" selected="selected">Choose one...</option>
    <option>Option 1</option>
    <option>Option 2</option>
    <option>Option 3</option>
</select>
```

In raw HTML, this will display the select with the text "Choose one..." with that option disabled when it is open, but with the widget initialized, it will display with no label text. This feature is helpful when you want to use the option as a label or instructions for the selectmenu.

**Comment by fnagel** [comment]
Now I get the problem. Fixed in latest trunk. Thanks for helping!

**Comment by abloore** [comment]
Thanks! That looks like it works. That was quick!

**Comment by fnagel** [comment]
You're welcome!
