### ISSUE TITLE
SelectMenu is left aligning all my other selects on this page too

### ISSUE THREAD

**Issue by vincentwansink** [fnagel/jquery-ui#235]
I have applied the SelectMenu widget to a number of selects on my page, but there are several other selects on this same page to which I do not want to apply the SelectMenu styling.  Unfortunately all my selects on this page are now being force aligned on the left.  One of these I absolutely need aligned on the right.  I have tried everything I can think of to align it to the right, within it's TD, but to no avail.  If there is an easy way to do this I would be very appreciative.  I also would classify this as a bug, regardless of any available "work around".

**Comment by fnagel** [comment]
Please post a demo, see #61

**Comment by vincentwansink** [comment]
Here's a link to a demo that is an exact copy of my page.  I just saved the source code as html so there is no server side code in this file.

https://www.timesavr.net/dev/test.htm

Notice the Active/Inactive select is left aligned.
I'm using Google Chrome ver 19.0.1084.52 m although I get the same behaviour in IE 9, Opera 11 and FF 13
Windows 7 - 64

**Comment by fnagel** [comment]
Page works fine for me. What do you want to achieve? Whats wrong?

**Comment by vincentwansink** [comment]
Sorry.  I took another look and realized that the problem was the demo styles that I had copied from the demo page.  It was floating:left all my selects.  Issue closed.
