### ISSUE TITLE
Spaces in optgroup label causes duplications

### ISSUE THREAD

**Issue by asaworld** [fnagel/jquery-ui#236]
I saw someone else reported this 2 years ago and you said that you could not recreate it. The below code causes this issue to appear (optgroups are not grouped). Remove the spaces in the optgroup label and it works just fine. I only downloaded this library a few days ago.

```
<select name="data[sport]" class="selectmenu" id="sport">
<optgroup label="My Sports">
<option value="Kayaking">Kayaking</option>
<option value="Rock climbing">Rock climbing</option>
</optgroup>
<optgroup label="Other Sports">
<option value="Surfing">Surfing</option>
<option value="Skateboarding">Skateboarding</option>
</optgroup>
</select>
```

Thanks,
Asa

**Comment by fnagel** [comment]
Thanks for your contribution!
Ive tested your code in a fiddle (http://jsfiddle.net/GXtpC/475/) but it worked as expected. 

Did you find the old issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by asaworld** [comment]
Still seeing this happen. I have put together the simple code in jsfiddle. Can you see this happen?

http://jsfiddle.net/GXtpC/497/

**Comment by fnagel** [comment]
You are using outdated code. Please update!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by asaworld** [comment]
You are right, I think you can close this one.

**Comment by fnagel** [comment]
Thanks for your feedback! Closed as solved.
