### ISSUE TITLE
IE BUG: Defect in displaying selectMenus in toggleable container

### ISSUE THREAD

**Issue by ghost** [fnagel/jquery-ui#237]
Hi 

I am facing following problem:
My select menu objects are wrapped by div which is toggleAble ->  show/hide it's content with jquery slideToggle function
In FF everything is ok, but in IE (version 8), there is defect in toggling behaviour: when showing content, select menu is in wrong position (moved down a bit ). After mouse over, it returns to correct position.

On following link you can find simple example of what i am talking about, concretely file bug\demos\selectmenu\default.html. If any problem to access it, pls let mi know, i will upload it somewhere else.
http://www.ulozto.sk/xHRdM4S/bug-zip

Thanks for any help/suggestions
Regards

**Comment by fnagel** [comment]
Thanks for this proper bug report -- these are rare!

Please try to refresh the selectmenu by using 

```
$("#myElement").selectmenu();
```

on each select element by using callback of slideToggle

**Comment by ghost** [comment]
hi felix
i upgraded to newest version an its working now so thx
On Jun 26, 2012 11:46 PM, "Felix Nagel" <
reply@reply.github.com>
wrote:

**Comment by fnagel** [comment]
Great! I will close this issue. Please reopen if needed.
