### ISSUE TITLE
Mousedown event cancels propagation

### ISSUE THREAD

**Issue by danwarne** [fnagel/jquery-ui#238]
The selectmenu mousedown event always returns false.  This causes issues when other widgets are listening to the document.mousedown event as well.  I'm using the datepicker widget.  I have opened the date picker, and then I click on the selectmenu but the date picker control isn't hidden because the selectmenu cancels the event.

**Comment by fnagel** [comment]
Are you able to provide a demo fiddle? Would be much easier for me as Im
struggling with a work overlaod atm. Thanks!

See #61

**Comment by danwarne** [comment]
I think I have it set up here: http://jsfiddle.net/f29Lj/

If you click on the datepicker, then the select menu the date picker isn't dismissed

**Comment by fnagel** [comment]
Problem confirmed.

**Comment by fnagel** [comment]
Any idea how to fix this?

**Comment by danwarne** [comment]
I only debugged into this a little bit and saw that the mousedown event was cancelling propagation.  This prevents the mousedown event from firing in the calendar widget.

**Comment by twestervelt** [comment]
Any updates on this problem?

**Comment by fnagel** [comment]
I'm currently pretty busy and as this is a one man show -- nope :-(

I have only a certain amount of time to support this effort and will allocate it the best I can. Please consider a donation if you need to have this bug fixed asap.

**Comment by fnagel** [comment]
This issue should be fixed in #274. Please test and give feedback!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by danwarne** [comment]
We stopped using the plugin (we had other needs that a different plugin
met).  I don't know that I'll be able to get an environment set up to test
this so I guess just consider it closed

**Comment by fnagel** [comment]
Thanks for the feedback!
