### ISSUE TITLE
IE hangs with too many options?

### ISSUE THREAD

**Issue by shawncalvert** [fnagel/jquery-ui#239]
I used selectmenu on an admin site, and it worked great until we tested with a user that had incredibly long select options (a table pagination dropdown had nearly 4000 pgs, another screen had about 5 dropdowns with 100-200 options each). These screens worked just fine in FF and Chrome, but the page was killed in all versions of IE (the pagination took about a minute to load, and the other screen took about 5 minutes, or timed out). 

Any idea why this would only happen in IE? 

Thanks

**Comment by fnagel** [comment]
IE was always a problem _sigh_

There are a few hacks to make IE work, perhaps there is room for finetuning when not using all features (for example pop-up mode). Another idea would be switching to the new jQuery UI Selectmenu widget, see #140

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by shawncalvert** [comment]
Thank you for following up, we couldn't figure out why it was happening, so had to remove it from the pages with the huge number of select options (we have about 75% of our clients on IE, so couldn't hold out too long to troubleshoot). Otherwise, there were no noticeable performance issues until the options were somewhere between 100 and 4000,  then IE choked. I think we were using the latest (at least from couple of months ago) -- jquery.ui.selectmenu.js (jQuery UI selectmenu 1.3.0pre version) with the latest jquery UI core plugin.

**Comment by fnagel** [comment]
Wow, 4000 is a huge amount. I don't think its possible to improve the performance of this old script to match your requirements. I guess we should hope the new selectmenu will be included in jQuery 1.9.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
