### ISSUE TITLE
Keyboard navigation of dropdown throws JS error

### ISSUE THREAD

**Issue by aprilb** [fnagel/jquery-ui#240]
I can't seem to use the cursor keys to navigate up and down the drop-down menu.  I apologize if this is a redundant ticket.  has this been addressed?  If not, will it be?

**Comment by fnagel** [comment]
Problem confirmed. This seems to be a problem since the update of jQuery to 1.7.2.

I will take a look soon. Any help is appreciated!

**Comment by fnagel** [comment]
What JS error do you get? And how? Im not able to reproduce a error message, it just dont works.

**Comment by fnagel** [comment]
Problem seems to be located in _moveFocus().

**Comment by fnagel** [comment]
Im pretty busy atm, it will take some time to dig into this. Any help is appreciated!

**Comment by aprilb** [comment]
thanks for looking into it!

**Comment by fnagel** [comment]
No help? Any feedback?

**Comment by fnagel** [comment]
This seems to be fixed with #247

Please test and give feedback!

**Comment by aprilb** [comment]
I was able to test the new fix.  Works great!  Thanks.

**Comment by fnagel** [comment]
Nice, thanks for the feedback!
