### ISSUE TITLE
"focus" doesn't bubble

### ISSUE THREAD

**Issue by aglemann** [fnagel/jquery-ui#241]
What am I missing? The code seems to depend on focus bubbling from the anchor inside each list item to the item itself.. but as of at least jQuery 1.6 that doesn't happen. By subclassing the widget and adding a focus handler to each anchor that triggers "focus" on it's parent the widget works perfectly. But otherwise behaves pretty broken.

**Comment by aglemann** [comment]
http://bugs.jquery.com/ticket/9452

**Comment by aglemann** [comment]
http://jsfiddle.net/kCb6H/

**Comment by fnagel** [comment]
Ähh yes. I have no idea what you are talking about. What about a problem description with more than 3 words? Or a line about how to reproduce this? Or the relevant browsers? 

See #61

**Comment by aglemann** [comment]
Tks - sorry I didn't see #61. See the jsfiddle I had posted above, that duplicates the issue and includes an example fix. I will add a pull request shortly. This affects all browsers.

**Comment by aglemann** [comment]
Please see pull request #247:

https://github.com/fnagel/jquery-ui/pull/247

That includes a unit test that duplicates the issue and the patch that fixes the issue.

**Comment by fnagel** [comment]
Am I right that this issue is directly related to #240?
The problem is that the focus is not set to the link, but it does in previous commits (commits using jQuery 1.6.x), right?

Why didn't you use the prepared fiddle? Like http://jsfiddle.net/fnagel/GXtpC/498/

**Comment by fnagel** [comment]
I would prefer to understand why the focus doesnt bubble as with jQuery 1.6.x and I think this is not a clean solution. But, after all, it works pretty nice :-)

**Comment by fnagel** [comment]
The last unit test you created fails.

**Comment by aglemann** [comment]
Sorry, I posted my jsfiddle before you posted the reference to #61 that included the jsfiddle template.

I agree this solution is hacky. I'd prefer to either trigger all events on the LI or add all the listeners to the A. I'll put together a better fix. Which Browser/Ver/OS did the last test fail on? (ironic i'm asking this).

**Comment by fnagel** [comment]
No problem, it just had been easier.

I think it would be most suitable if the focus is handled within the anchors, as native lis wont get focus.

Ive tested in latest FF.

Please note I roughly cleaned my branch to get rid of unneded files.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by aglemann** [comment]
Will get this push request by EOD tomorrow... been swamped.

**Comment by aglemann** [comment]
Please see this pull request:

https://github.com/fnagel/jquery-ui/pull/257

Includes tests that have have passed in Safari, Chrome, FF, IE7/8.
