### ISSUE TITLE
Allow collision 'none' 

### ISSUE THREAD

**Issue by thiagofesta** [fnagel/jquery-ui#244]
Currently we can't use collision: 'none'... because it sets to flip or fit.

I made a change on mine code to allow (just ifs)

**Comment by fnagel** [comment]
Mhh it should be possible to change option positionOptions.collision. 

Related code snippet:

```
collision: o.positionOptions.collision || o.style == "popup" ? 'fit' :'flip'
```

So if optionpositionOptions.collision is set it will be used.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Fixed in #255

**Comment by fnagel** [comment]
Please test and give feedback!

**Comment by fnagel** [comment]
Closed as should be resolved. Please re-open if not!
