### ISSUE TITLE
Not populating <span> within Chrome/Safari?

### ISSUE THREAD

**Issue by jodriscoll** [fnagel/jquery-ui#246]
This is a first!
It seems to be populating the "selected" inside IE/Firefox, but not in Chrome/Safari!

Here is a working example:
http://www.massgeneral.org/top-doctors/default.aspx

Any help would be appreciated!

**Comment by fnagel** [comment]
I would assume you're missing / faulty CSS statements as its working just fine in the demo fiddle: http://jsfiddle.net/fnagel/GXtpC/

**Comment by jodriscoll** [comment]
Any idea what it could be that I'm missing? Not sure why it would malfunction in only Chrome/Safari...

**Comment by fnagel** [comment]
As far as I can see there is no text within your span. Why? I have no idea? Did you make any chanegs to selectmenu? Using latest version?

**Comment by jodriscoll** [comment]
I have no clue as well, which is the purpose of this support ticket...

It populates and works perfectly fine within Firefox and IE. It however, does not work in Chrome and Safari. If anyone can shed some light on what I did or what it's not doing, I would greatly appreciate it.

**Comment by fnagel** [comment]
Are you able to reproduce it within a fiddle or a minimal demo zip? Its
hard to debug without easy editable files.

**Comment by jodriscoll** [comment]
Can you tell me exactly what you need from my end? I'm almost certain everything is accessible by the end user, however, I can produce a fiddle if need be.

**Comment by jodriscoll** [comment]
Alright, I produced a fiddle for you!

http://jsfiddle.net/jodriscoll/qNKxX/1/

However, when I view the fiddle in Chrome/Safari, it works! However, it does NOT work when I view it on the environment it's meant to live on... Any ideas?

**Comment by fnagel** [comment]
Im able to access your demo (http://www.massgeneral.org/top-doctors/default.aspx) but its pretty hard to track the origin of the problem. What we need is a stripped down, minimal version of the problem. Or perhaps its easier to make a standalone zip out of it? 

Problem is it could be so much. Other Java-Scripts, doctype or some kind of strange side effects cause of whatever. Some ideas: You shouldnt use multiple JS libs at the same time. Try removing dojo and mootools libraries. Change doctype to strict, remove empty lines before doctype. Remove other scripts.

**Comment by jodriscoll** [comment]
In terms of the overall JS library, I'm unable to modify that. Trust me, I wish I could, but I can't :(

The odd part, was that it was working until I fully skinned the UI for the drop box. Which means, at some point, some form of CSS or something, managed to throw it out of wack in those two browsers. Do you have any idea what could of caused it to not populate in only 2 browsers?

**Comment by fnagel** [comment]
I have no idea but carefully remove those CSS until you find the problem
causing statement. Look for position and float statements, perhaps width.

Sorry I cant help more :-(

**Comment by fnagel** [comment]
Did you manage to fix your problem?

**Comment by jodriscoll** [comment]
I have not! I will look into it this/next week and hopefully be able to report back to you!

**Comment by tonnyavery** [comment]
Confirm the issue.
Seems like when select doesn't have initial value set
Firefox does set value to 0 index on blue
Chrome does not, returning null
That might result in unpopulated 'selected' if nothing was actually selected by user and only default element was highlighted

**Comment by tonnyavery** [comment]
And here's the underlying cause of that: http://code.google.com/p/chromium/issues/detail?id=143632

**Comment by jodriscoll** [comment]
AAverin, great work! What would you suggest as a solution for the current issue presented on the page I provided?

**Comment by tonnyavery** [comment]
Here's what I did in my code for chrome. You could try something similar
if (select[0].value == "") {
                                    select[0].value = select[0].options[0].value;
                                }

**Comment by jodriscoll** [comment]
I just attempted to implement this JS to the template and it still is producing a blank result within the select box. Any ideas on what can be conflicting with it from your research?

**Comment by tonnyavery** [comment]
seems like this chrome issue isn't going to be fixed, so I'd suggest to implement some global fix in selectmenu.value method. At the moment value method uses empty assignment to clear select to initial state, which is broken in chrome.

http://code.google.com/p/chromium/issues/detail?id=143632
https://bugs.webkit.org/show_bug.cgi?id=67233

jodriscoll, not sure what might be wrong in your case, just read through issue case notes, maybe it'll give you some new ideas. Basically, setting select value that's not present in list result in empty select for Chrome, so maybe you'll need to modify my snippet in some way.

**Comment by fnagel** [comment]
Would you mind to set up a demo fiddle for testing purposes? See #61, its really easy!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed!

**Comment by jodriscoll** [comment]
fnagel, I will be researching this bug next week! I will report back once I've spent some time figuring out the issue again. My apologies for the delayed response.
