### ISSUE TITLE
Problem with width on select

### ISSUE THREAD

**Issue by cutmaster** [fnagel/jquery-ui#248]
Hi,
Selectmenu always sets a too small width value so when a scrollbar is shown , it hides part of the longer texts

(look here : http://www.wptechnology.com/pics/selectmenu.png )

How can we ensure that an automatic size can be correctly set using this plugin ?

Thanks for your help

Bests.

**Comment by fnagel** [comment]
Please use the search!

You need to set at least one width: via CSS (on original select element) or by option.

**Comment by cutmaster** [comment]
For me it doesn't make sens, if we've got dynamic options on select, how can we know the min width to display ? width-auto seems to not work as it does the deal for the width of the div EXCEPT for the vertical scrollbar... How can we fix that ?
note that I've of course searched before but when you fall on links like this :
http://stackoverflow.com/questions/9197232/jquery-ui-selectmenu-how-do-i-set-the-dynamic-width-correctly
where all answers starts with "it is failing for me", it is not really easy to estimate that there's a solution, sorry for that :$

**Comment by fnagel** [comment]
It does work but you need to adjust your CSS (eg. margin, padding, font style) or just set a width manually via options.

**Comment by cutmaster** [comment]
Well we'll try manually via options and let you know (because of course we've got several different select)... Thanks.

**Comment by fnagel** [comment]
Feel free to post a demo fiddle (#61) and I will see if I can help!

**Comment by fnagel** [comment]
Issue closed, please feel free to reopen if needed!
