### ISSUE TITLE
Absolute positioning

### ISSUE THREAD

**Issue by Wimmen** [fnagel/jquery-ui#250]
At the website I am currently working on all the selects are absolute positioned using the style attribute. For the selectmenu plugin to work in my case I had to at 'style': this.element.attr('style') at the creation of the newelement to make it work. Not sure if it is something that needs to be in the main plugin, but maybe it helps someone else.

**Comment by fnagel** [comment]
Can you give an example fiddle? See #61

**Comment by Wimmen** [comment]
see [example](http://jsfiddle.net/GXtpC/523/)
Select speedA and speedA2 are both positioned absolute, speedA is replaced with selectmenu and is now positioned inline.

**Comment by fnagel** [comment]
You need to position the select within a div. Selectmenu is based upon the jQuery UI position plugin and is not possible to determine the position of hidden elements. 

Please see here: http://jsfiddle.net/GXtpC/526/
