### ISSUE TITLE
Does not maintain classes

### ISSUE THREAD

**Issue by holisticnetworking** [fnagel/jquery-ui#252]
This plugin works great on some levels, but because I need to style it differently than other elements, I'd like to be able to maintain the jQuery UI class-based styling. However, when the widget is converted, it does not maintain any previously-specified classes, nor do I see a way of inserting them natively in your widget.

Thanks!

**Comment by fnagel** [comment]
No, there's currently no automatic way to do this. You could try using the widget method after init and modify the lis by using find and addClass. Another idea would be to use the format option to modify the lis content on init.

Hope that helps!

**Comment by fnagel** [comment]
Another idea would be the new, 1.9 compatible version. See #140

Can I close this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as issue seems to be solved. Please reopen if needed.
