### ISSUE TITLE
Window position scrolls after window resize on open select menu

### ISSUE THREAD

**Issue by jpsolero** [fnagel/jquery-ui#253]
Browser:  Chrome and Firefox 12
MAC Os X 10.7.4

Open a window. I.e. - http://jquery-ui.googlecode.com/svn/branches/labs/selectmenu/index.html
Resize the window
Click on a select menu at the bottom of the screen (or at the top, it depends on the widget position)
Bug --> The window scrolls its position

**Comment by fnagel** [comment]
Your version is totally outdated.

**Comment by fnagel** [comment]
Please use latest version (https://github.com/fnagel/jquery-ui/zipball/selectmenu) or a tagged version: https://github.com/fnagel/jquery-ui/tags

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by jpsolero** [comment]
Yes,it worked perfectly after using the proper version.

thanks

**Comment by fnagel** [comment]
Nice, thanks for the feedback!

**Comment by latkf** [comment]
Please can somebody help me. I have the same problem (The select menu moves). I use the last version 1.3 with jQuery 1.8.2 and the problem is always there.

Thanks

**Comment by fnagel** [comment]
Please open a new issue for this and provide a demo (see #61)
