### ISSUE TITLE
positionOptions is undocumented

### ISSUE THREAD

**Issue by dguzzo** [fnagel/jquery-ui#254]
in [the demo linked](http://jsfiddle.net/fnagel/GXtpC/embedded/result/) from your wiki page, there is this in the source:

``` javascript
$('select#filesC').selectmenu({
    style:'popup',
    positionOptions: {
        my: "left center",
        at: "right center",
        offset: "10 0"
    }
});
```

yet **positionOptions** is completely undocumented. even if this plugin is using jQuery UI Position utility stuff by proxy, the Readme page should still list this as an option and describe what it does, even if it seems self explanatory. [here's some discussion](http://stackoverflow.com/questions/8197074/jquery-ui-selectmenu-dropdown-opens-up-instead-of-down) of this property from Stackoveflow.

**Comment by fnagel** [comment]
Confirmed. Thanks for reporting!

Will be fixed in next release.

**Comment by fnagel** [comment]
Added to documentation.
