### ISSUE TITLE
Inconsistent use of `this.namespace` and `this.widgetBaseClass`

### ISSUE THREAD

**Issue by aglemann** [fnagel/jquery-ui#256]
ie.

```
self.namespace + '-state-disabled'
'ui-state-active'
self.widgetBaseClass + '-item-focus'
'ui-selectmenu-' + Math.random()

```

etc..

Is this all intentional? If not I'd be happy to clean it up...

Assuming "ui-selectmenu" should always be replaced with "widgetBaseClass"
Classes used by jQuery UI Core should remain "ui-" prefixed
All other classes should use "namespace" prefix

Is that right?

**Comment by fnagel** [comment]
Sorry for the late response, I configured something wrong when GitHub changed there notification system.

Afaics this.namespace could be removed for ui-state-disabled etc. Replacing "ui" by using this.namespace seems unneeded. Even the official jQuery UI widget do not replace it. Please note that ui-state-disabled, ui-state-focus, ui-state-hover are jQuery UI CSS framework related classes and should not be changed.

All ui-selectmenu usages should be replaced by widgetBaseClass, thats correct.

Question answered? Im not sure if I understand this issue completely :-)

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
