### ISSUE TITLE
Lists get clipped

### ISSUE THREAD

**Issue by ghost** [fnagel/jquery-ui#258]
On some occasions the select list will get clipped at the top of the window, which makes it impossible to reach the top options by mouse. Is it possible to force the select list to always expand downwards?

I should add to this that maxHeight is set to 'null'. When removing this option, i.e. forcing a scrollbar, the select list seems to behave properly.

**Comment by fnagel** [comment]
Sorry for the late response, I configured something wrong when GitHub changed there notification system.

Try configure the positionOptions.collison option. See jQuery UI position plugin for doucmentation.

Feel free to comment here if you need more help! A demo fiddle (see #61) or a demo link kis always useful!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by ghost** [comment]
Hi! Here's a demo fiddle where you can see the issue in action. There's one list with maxHeight set to 'null', and another list with the collision property set to 'fit'. The first list is clipped by the viewport, and the other one briefly flashes before it disappears.

http://jsfiddle.net/K6UYK/2/

**Comment by fnagel** [comment]
Did you try removing maxHeight? Null is no valid value. Seems to work for me http://jsfiddle.net/K6UYK/3/

**Comment by ghost** [comment]
Yes, that was the solution I settled for, but at first I wanted a dropdown without scrollbars, and maxHeight null seemed to do just that. Until I saw this odd behaviour. But since maxHeight 'null' isn't supported, I should probably close this issue.

**Comment by fnagel** [comment]
What exactly you wish to realize?

**Comment by ghost** [comment]
At first I wanted a dropdown without a max height (no scrollbars inside the dropdown), that would grow as tall as it needed to be. I eventually abandoned this idea and settled for a dropdown with a max height set. However, that approach too seems to have the clipping issues. In the following fiddle I have set the max height to be 800 px. A bit tall maybe, but just to illustrate how the list will sometimes "drop upwards" and get clipped by the viewport. In my opinion it should always drop downwards if there's not enough space above the select list. That way it will never be clipped. http://jsfiddle.net/K6UYK/4/

**Comment by fnagel** [comment]
Try playing arround with the collison option of the Position plugin. See: http://api.jqueryui.com/position/

"fit flip" seems to do the trick: http://jsfiddle.net/K6UYK/5/
