### ISSUE TITLE
Possible to hide options instead of disable?

### ISSUE THREAD

**Issue by HackWeight** [fnagel/jquery-ui#259]
Thanks so much for the selectmenu control!  It's been working well so far for me, but I am running into a question that I do not know how to solve.  

We are basically doing cascading dropdown lists so you select a certain value in List A and then I have a list of option values that I need to allow in List B.  Right now I am disabling all the options for each index that is not valid by doing:

``` javascript
$('select#ddlListB').selectmenu('disable', index);
```

This works, however ideally I would like to be able to hide the individual option and not show it at all.  So something more like:

``` javascript
$('select#ddlListB').selectmenu('hide', index);

// would also need to add
$('select#ddlListB').selectmenu('show', index);

```

Or would there be a better jQuery way of hiding these items?

**Comment by fnagel** [comment]
Sorry for the late response, I configured something wrong when GitHub changed there notification system and therefore did not receive any emails :-(

There is no built-in mechanism to really hide elements. You could change the ui-state-disabled CSS style, perhaps in combination with a own style for the widget (see default demo, #speedAa).

Does this help?

**Comment by tschettler** [comment]
I saw this as well. What you can do is add a class to the select option that has "display: none" and then just call selectmenu over the select element again. The selectmenu call will add the class to the li item, so you'd need to have that as a style rule as well. 

The following should work:
<code>.hidden, .ui-selectmenu-menu li.hidden { display: none; }</code>

Script to hide the third option:
<code>$('select option:eq(2)').addClass('hidden');
$('select').selectmenu();</code>

**Comment by HackWeight** [comment]
Thank you!  tschettler's suggestion worked great.  I've got it working in my dropdown now.  

While it would be nice to have "hide" and "show" options integrated as a new feature, this is a great workaround.

**Comment by tschettler** [comment]
Glad it worked for you!

If you are using optgroups, there's an additional step to take if you don't want the optgroup header to display in the selectmenu. After calling selectmenu() again, you can do this:
<code>$('.ui-selectmenu-group').not(':has(li:not(.hidden))').hide();</code>

**Comment by fnagel** [comment]
Is this issue solved?

**Comment by HackWeight** [comment]
Yes, it is solved in the sense that there tschettler's workaround works.  I would say that adding "hide" and "show" items by index would be a nice new feature so the workaround wouldn't need to be used.  

For instance the workaround does this:
$('select option:eq(2)').addClass('hidden'); // add the 'hidden' class to the selectmenu option of index 2
$('select#ddlListB').selectmenu(); // reload the selectmenu

Where it would be clearer to be able to do this:
var index = 2;
$('select#ddlListB').selectmenu('hide', index);

**Comment by fnagel** [comment]
@mkrajew Please open a new issue for that, with a reference to this issue. THX!
