### ISSUE TITLE
Disable or remove option from selection

### ISSUE THREAD

**Issue by ic3y** [fnagel/jquery-ui#260]
Hi Felix,

This small script works on normale selectmenu's and it works on selectmenu's on this demo http://view.jqueryui.com/selectmenu/tests/visual/selectmenu/disabled.html
But i can't get it to work on the files i downloaded here: https://github.com/fnagel/jquery-ui

I tried to get all files from the first URL, but then nothing seems to work as it should.

// Metadata
$("#year").selectmenu({

```
// listen to the select event of the custom menu, not the original dropdown
select: function(){
    var val = $(this).val();

   if(val == "2008"){
         $("#c2").find("option:eq(1)").removeAttr("disabled");
    }
    else{
        $("#c2").find("option:eq(1)").attr("disabled", "disabled");
    }

    // must call this to reflect the change
    $("#c2").selectmenu("refresh");
}
```

});

What it should do is disable (or better yet, hide, but i don't know if that's possible) option nr 1 of select #c2 when someone selects "2008" in the selectmenu called year.

**Comment by HackWeight** [comment]
You just need to use the enable/disable options of the selectmenu like this:

``` javascript
$('#c2').selectmenu('enable', index);
$('#c2').selectmenu('disable', index);
```

The methods you can use are here:
https://github.com/fnagel/jquery-ui/wiki/Selectmenu

I haven't found a way to completely hide an option though.  Just posted a question about that 2 days ago.

**Comment by ic3y** [comment]
Thanks for the reply, but i don't need to enable or disable a complete menu, but just an option.

**Comment by HackWeight** [comment]
That code IS for disabling an individual option.  You pass in the index of the option you want to disable.   

So if you want to disable index 1, you call 

``` javascript
$('#c2').selectmenu('disable', 1);
```

You can call 'disable' without an index to disable the entire menu but if you pass in a number, it is the index of the option you want to disable.

**Comment by ic3y** [comment]
I respect your help, but i can't get it to work. I am trying this:

// Metadata
$("#year").selectmenu({

```
// listen to the select event of the custom menu, not the original dropdown
select: function(){
    var val = $(this).val();

   if(val == "2008"){
         //$("#c2").find("option:eq(1)").removeAttr("disabled");
         $('#c2').selectmenu('disable', 1);
    }
    else{
        //$("#c2").find("option:eq(1)").attr("disabled", "disabled");
        $('#c2').selectmenu('enable', 1);
    }

    // must call this to reflect the change
    $("#c2").selectmenu("refresh");
}
```

});

**Comment by ic3y** [comment]
Oh my, it seems to work.. Damnit, i have been working on this for two days now. Almost going bezerk. Thanks a lot!

One more question if i may ask. I am using a chained menu. Sometimes the year field isn't shown. Automatically the above script doesn't disable the menu (while it should). Is it possible to always disable the menu unless 2008 in year is selected?

**Comment by HackWeight** [comment]
Check out this fiddle:
http://jsfiddle.net/pC7wq/1/

It shows it working when you select "2008" from the 1st dropdown, it will disable the 1st index from the 2nd dropdown.  You don't need to call "refresh".

Hope this helps!

**Comment by HackWeight** [comment]
I'm not sure I understand exactly what you mean, but you can disable the entire menu by just omitting the "index" parameter as in

``` javascript
$("#c2").selectmenu("disable");
```

Not sure if that's what you were asking?  So you could disable the menu on page load, then enable it once the appropriate condition has been met.

**Comment by ic3y** [comment]
Thanks for all your help, it's really appreciated!

I see you didn't understand my question, because i didn't explain it well enough.
I would like this option: $('#c2').selectmenu('enable', 1); ONLY enabled when 2008 i selected in the year select-menu Always disabled in any other case. So for example if nothing is selected in the year-selectmenu or if the year-selectmenu is hidden, etc. etc. $('#c2').selectmenu('enable', 1); should be disabled.

Also, do you know if there is an option to add 'selected' to an option? 
This doesn't work, but you know what i mean: $('#c2').selectmenu('select', 1);

**Comment by HackWeight** [comment]
I don't think the selectmenu will be able to do it automatically but it's certainly something you can add.  You'll have to add it for every condition you want.

I'd probably move the code from the select section into a different method, then call it from the select method.  Then you can also call that method from other places such as page load, when the selectmenu is shown or hidden, etc.  All it would do is check what the current page conditions are and then update whether the option is enabled or disabled.

**Comment by ic3y** [comment]
Thanks!

I am still learning this stuff, so your help was appreciated. I think it works now.

I'll try and read further into all this and see if I am able to help you out with your question about hiding options. Perhaps you could also ask this on stackoverflow.

**Comment by fnagel** [comment]
Sorry for the late response, I configured something wrong when GitHub changed there notification system and therefore did not receive any emails :-(

Is this question solved? Could it be closed?

**Comment by fnagel** [comment]
And thanks for helping each other out. Really nice to see :-)

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as issue seems to be solved. Please reopen if needed.
