### ISSUE TITLE
How can I disable the Selectmenu Widget for specific fields?

### ISSUE THREAD

**Issue by ChayaCooper** [fnagel/jquery-ui#263]
The Selectmenu Widget is creating duplicates of Multiselect fields. Is there a way to disable the Selectmenu Widget for specific Select fields (as opposed to the entire form)?

**Comment by fnagel** [comment]
What exactly do you mean with Multiselect? The Selecmenu Widget does not support multiselect feature.

I'm not quite sure if I understand you right, but I will try :-)
You have a form with a few native selects but you want only specific to be replaced by Selectmenu Widget, right? 

A demo fiddle (see #61) or a link would be helpful!

**Comment by ChayaCooper** [comment]
I have a lot of native Selects and a few MultiSelects (I'm using another plugin for those). 

I'd like to replace all the native Selects with the Selectmenu Widget, and disable it for all multiselects or disable specific ones (either by class or individually).  Doing it this way would be a lot more efficient and create less room for mistakes by another developer. 

Can that be done? If not, how would I specify which native Selects should be replaced by the Selectmenu Widget?

**Comment by fnagel** [comment]
Yes, thats pretty easy. Just call the Selectmenu widget on those selects you need.

That can be done by any jQuery selector. Are you familiar with the concept of jQuery selectors?
Example: add a CSS class to all non-multi selects and use $(".yourCssClass").selectmenu() or use a jQuery selector which does no select multiselects (google for it!).

**Comment by ChayaCooper** [comment]
I was hoping it would be an easy question ;-)

I haven't used jQuery selectors before, but thanks to StackOverflow I found the correct selectors :)

$("select#categories:not([multiple])")  // <select> with single only
$("select#categories[multiple]")  // <select> with multiple

I couldn't find a set of easy-to-follow instructions to show me how to use it though, and $("select#categories:not([multiple])").selectmenu(); didn't work :-( Would you be able to show me where to insert it?

**Comment by fnagel** [comment]
Hey Chaya, 

here is a demo fiddle: http://jsfiddle.net/GXtpC/591/

**Comment by ChayaCooper** [comment]
That's easy :-D Thank you so much!

**Comment by fnagel** [comment]
Your're welcome!
