### ISSUE TITLE
maxHeight not working in combination with style: ‘dropdown’

### ISSUE THREAD

**Issue by danielkoch** [fnagel/jquery-ui#265]
In my case the option maxHeight are not working with the combination style : "dropdown". Ist this a known issue?

**Comment by fnagel** [comment]
It should. Can you give a demo fiddle? See #61

**Comment by danielkoch** [comment]
Sorry, the problem are solved. Caused by a other website component.

**Comment by fnagel** [comment]
You're welcome :-)
