### ISSUE TITLE
Using fnagel jquery-ui selectmenu with WordPress

### ISSUE THREAD

**Issue by dominornovus** [fnagel/jquery-ui#266]
After some time, I've figured out how to successfully apply the selectmenu widget to WordPress.

WordPress installations come complete with a bundle of jQuery scripts.

The fnagel selectmenu will not work the default bundle of jquery and jquery-ui scripts and instead has to be referenced externally using Google CDN.

Here's an example of the working code using to get the selectmenu working with WordPress: http://pastebin.com/ttnQR9Qv

I had to deregister the default local jQuery library for WordPress, enqueue the Google CDN and then enqueue the selectmenu script and CSS.

I'm posting this here for two reasons:

1) It may help other WordPress users.
2) To ask why the selectmenu doesn't work with the default jQuery library for WordPress.

**Comment by fnagel** [comment]
You're using totally outdated scripts as the google CDN is a thousands years old. Note: there is no CDN for my fork so please host these on your own server.

**Comment by dominornovus** [comment]
Why is the official jQuery website recommending the Google CDN and how can it be outmoded if I'm linking to version 1.8.12? Forgive the greenness. I'm a novice when it comes to jQuery. 

Are you saying I should upload your fork to my website and use that instead of any other jQuery library such as Google CDN, WordPress's bundle or a locally installed version of the standard jQuery bundle?

I still don't understand why the selectmenu works with the Google CDN but not WordPress. Based on what you've explained, wouldn't it make more sense if the selectmenu _didn't_ work with the Google CDN but _did_ work with the WordPress default jQuery bundle? 

Thanks for your time. The selectmenu is a fantastic UI widget.

**Comment by fnagel** [comment]
Official website?

**Comment by fnagel** [comment]
Let me try to explain:

There are currently three versions. 

The old one: jQuery UI selectmenu widget originally developed by Scott (filament group) http://filamentgroup.com/lab/jquery_ui_selectmenu_an_aria_accessible_plugin_for_styling_a_html_select/
This version is on google CDN. Its years old and wont work with any newer jQuery / UI
Please note the notice at the website, redirecting to my fork!

My fork: an improved version of the jQuery UI selectmenu widget originally developed by Scott (filament group). Its available here on Github (this is its issue tracker!), in different versions. v1.1, v1.2 (tags, see downloads) and dev (latest, the selectmenu branch)

Official jQuery UI widget: not stable yet, available on jQuery UIs GitHub accoutn (selectmenu branch), will be released with jQuery UI 1.10, please see #140 for more informations

**Comment by fnagel** [comment]
by they way: this is outlined in the readme and the wiki page of this repo.

**Comment by dominornovus** [comment]
My prior understanding:

Your project was an alternative version of jQuery as a whole and you were saying that the Google CDN to jQuery as a whole is obsolete/outmoded.

My current understanding:

Your project represents an additional UI widget and not a substitution for jQuery as a whole. The CDN specifically for the selectmenu is an outmoded version by Filament Group. No CDN exists for the current selectmenu. 

Sorry for the confusion. I've now successfully applied the selectmenu to WordPress in harmony with the default jQuery bundle that comes with WordPress i.e. no longer dependent on an outmoded CDN for the selectmenu.

Working code and instructions for fellow WordPress users:http://pastebin.com/DCZzmwUv

Thanks for your time.
