### ISSUE TITLE
Links #nogo are triggered on latest version of Firefox (15.0.1)

### ISSUE THREAD

**Issue by khepin** [fnagel/jquery-ui#267]
On the latest version of FF, whenever an element is selected, the #nogo link is actually triggered.
So the app / page is navigating to the #nogo anchor which in our case (a one page app). Triggers a change to a completely different page.

Removing the "href" altogether solves the issue for now.

**Comment by fnagel** [comment]
Im pretty sure you are using Selectmenu wrong. Please add a demo fiddel, see #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by tay** [comment]
We're also experiencing this issue with the selectmenu element on Firefox 15.0.1 (it works on Chrome, Safari, and older versions of Firefox). For us, it's only happening on a couple of selectmenus (we use it in multiple contexts). I'll try to isolate it and make a demo tonight.

**Comment by khepin** [comment]
Checked this morning and still seeing this on FF#16. I'll try to make a quick sample later today as well.

**Comment by khepin** [comment]
It seems to happen somehow if `$('select').selectmenu()` is called twice. But still can't reproduce it in a more simple example for now.

**Comment by tay** [comment]
We're using jquery-ui version 1.8.16 - what are you using?

**Comment by khepin** [comment]
We're on 1.7.2 right now. Still wasn't able to isolate it and reproduce outside our app...

**Comment by fnagel** [comment]
Any updates on this? I prefer a demo fiddle but a public link should fit to take a quick look at the problem.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by tay** [comment]
We upgraded jquery-ui and it went away.

**Comment by fnagel** [comment]
So this issue could be closed?

**Comment by tay** [comment]
Yeah, we fixed it by upgrading our version of jquery-ui.

**Comment by fnagel** [comment]
Thanks for the feedback. Please reopen if needed.
