### ISSUE TITLE
IE9 script error: unrecognized expression: li:not(.ui-selectmenu-group).slice(0,1)

### ISSUE THREAD

**Issue by brunis** [fnagel/jquery-ui#269]
IE9 script error:
Line: 2
Error: Syntax error, unrecognized expression: li:not(.ui-selectmenu-group).slice(0,1)

**Comment by fnagel** [comment]
You are using an outdated version.

**Comment by brunis** [comment]
i just downloaded it yesterday? .. maybe i need a service to run and update it nightly?

The readme file still points to the same archive:
https://github.com/fnagel/jquery-ui/zipball/selectmenu ..

**Comment by fnagel** [comment]
Im not able to reproduce the error in IE9 and there is no according "slice" within the latest code.

When does the error occur? Please post a demo fiddle, see #61

**Comment by brunis** [comment]
maybe it's jquery 1.8.2 that fails ..  but i can't use jquery.ui on jsfiddle with jquery 1.8.2 :(

**Comment by fnagel** [comment]
Thats possible, see #261

Mhh why? Just remove old jQuery and add newer via any CDN.

**Comment by brunis** [comment]
FireFox has the same issue, it just logs it silently. I probably had "display every script error" turned on in IE9
Error: Syntax error, unrecognized expression: li:not(.ui-selectmenu-group).slice(0,1) @ http://localhost/trunk/Scripts/jquery-1.8.2.min.js:2

**Comment by brunis** [comment]
apologies for closing, i just thought it would redirect me, not close the issue! :)

**Comment by brunis** [comment]
here's the jsbin version: http://jsbin.com/iruvug/1/ jsfiddle is a pain in the ass!

also notice how it seems to adjust to the original select's calculated width, which always gives terrible results!

**Comment by ghost** [comment]
see also:
http://bugs.jquery.com/ticket/12612

**Comment by fnagel** [comment]
Ahhh ok. I have no idea where this ".selector" is for. 

Its was included in the original forked code but I a lot of people have contributed code to this fork so I have no idea why its there.Could be related to #29, but Im not quite sure.

I removed it as it seems to be useless and everything works as expected. I've pushed a patch, please test and give feedback!

Thanks for reporting and investigating. 

ps: Please search for "width". We had this discussion a lot.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by ghost** [comment]
it works for me.

**Comment by fnagel** [comment]
Thanks for the feedback!

@brunis Does it work for you too?

**Comment by brunis** [comment]
Yes, it works now, good job!

**Comment by fnagel** [comment]
Thanks for the feedback!
