### ISSUE TITLE
Change selected value on source select?

### ISSUE THREAD

**Issue by emaz** [fnagel/jquery-ui#27]
I must be missing something with this widget, as far as I can see it does not change the selected value on the source selecte element on change?
Are you supposed to do that by yourself in the callback or what, seems like it should be handled within the widget since it's replacing the original select?

Edit: I'm sorry, i was a bit too hasty with my conclusion. Read the code to quickly and missed the value-method. Sorry again for spamming! Any mod can delete this entry.

**Comment by fnagel** [comment]
No problem :-)
Thanks for your contribution.

**Comment by vzmind** [comment]
No I confirm that there is an issue in FF. Not in Safari. IE I dont care. 
On the project main page (http://www.filamentgroup.com/lab/jquery_ui_selectmenu_an_aria_accessible_plugin_for_styling_a_html_select/), the discution mention:

@Kris: Use the selectmenu method to address the control once you’ve built it.
$(’#Menu’).selectmenu(’value’,4);
4 would be the index number of the option in the select (0-based).

This have worked for me to patch the FF version

**Comment by fnagel** [comment]
I cant confirm your problem @vzmind
Please try to unhide the original select via firebug. Now you should be able to see the value is changed!

**Comment by fnagel** [comment]
Please give feedack! Use latest commit or this version: https://github.com/fnagel/jquery-ui/zipball/selectmenu_v1.1.0

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if necessary.
