### ISSUE TITLE
New feature to hide and show options

### ISSUE THREAD

**Issue by HackWeight** [fnagel/jquery-ui#272]
Per Issue #259
Would appreciate a new feature that would allow "show" and "hide" of individual options.  

For instance a workaround to hide an option as the control is now, you need to do this:

``` javascript
$('select option:eq(2)').addClass('hidden'); // add the 'hidden' class to the selectmenu option of index 2
$('select#ddlListB').selectmenu(); // reload the selectmenu
```

Where it would be clearer to be able to do this:

``` javascript
var index = 2;
$('select#ddlListB').selectmenu('hide', index);
```

Proposed API:

``` javascript
// hide an individual item
$('select#ddlListB').selectmenu('hide', index);

// show an already hidden item
$('select#ddlListB').selectmenu('show', index);
```

**Comment by demonslord** [comment]
Hi, see my changes here:

https://github.com/demonslord/jquery-ui/commit/4e10fe4c74a97cd669db3f170ef131a94d0179cd

**Comment by fnagel** [comment]
I will pull this asap. I'm off on holiday tomorrow so plese be patient.
Sorry :-/

**Comment by demonslord** [comment]
Hey fnagel, no problem ;)

**Comment by fnagel** [comment]
I tested your PR and commented it, please take a look!

**Comment by fnagel** [comment]
Closed. See PR itself: #291
