### ISSUE TITLE
jQuery UI 1.9 compatibility 

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#273]
Any experience so far? 

UPDATE: 
confusion in this thread: UI 1.9 does NOT come with jQuery 1.9.x but with 1.8.x

**Comment by fnagel** [comment]
See #115 for Position redesign.

**Comment by last-partizan** [comment]
I'm using jquery-ui.selectmenu from your repo with jquery-1.9.1 and jquery-ui 1.10.0, it works, jquery-migrate show only one warning: "JQMIGRATE: jQuery.fn.attr('selected') may use property instead of attribute" for this code (line 275).

```
        this.element.find( 'option' ).each( function() {
            var opt = $( this );
            selectOptionData.push({
                value: opt.attr( 'value' ),
                text: self._formatText( opt.text(), opt ),
                selected: opt.attr( 'selected' ),
                disabled: opt.attr( 'disabled' ),
                classes: opt.attr( 'class' ),
                typeahead: opt.attr( 'typeahead'),
                parentOptGroup: opt.parent( 'optgroup' ),
                bgImage: o.bgImage.call( opt )
            });
        });
```

**Comment by fnagel** [comment]
Thanks for reporting! Are you aware how to fix this?

**Comment by last-partizan** [comment]
http://jquery.com/upgrade-guide/1.9/#attr-versus-prop-
I assume here attr can be replaced by prop for "selected"/"disabled" and maybe for "class".
This .prop('selected') and .prop('disabled') now returns boolean value and if your code depends on old behavior (attr returns string) it must be rewritten.

**Comment by fnagel** [comment]
I was aware of the newer prop method but I do not exactly know the difference to attr method. This is a good explanation: http://stackoverflow.com/a/5876747/991681

Any other issues with jQuery 1.9 and later UI version?

If you need a version working with the latest jQuery / UI you should test the jQuery UI Selectmenu branch (using jQuery 1.9 and jQuery UI 1.10.1pre): https://github.com/jquery/jquery-ui/tree/selectmenu

See here for more info #140

**Comment by last-partizan** [comment]
Don't noticed any other issues.

**Comment by fnagel** [comment]
Notice to myself: check this finally! Update for 1.10 needed!

**Comment by fnagel** [comment]
Selectmenu is now considered jQuery 1.8.x / jQuery UI 1.9.x ready.
