### ISSUE TITLE
support nested optgroups?

### ISSUE THREAD

**Issue by flxmrk** [fnagel/jquery-ui#277]
I know its not exactly per w3c specs, but would be super helpful if this supported nested optgroups for better visual hierarchy.

I've tried looking around
// optgroup or not...
if (selectOptionData[i].parentOptGroup.length)

But couldn't quite figure out how to modify to make it respect nested optgroups in a select like so:

```
`<select name="test">
  <optgroup label="Main Cat 1">
    <optgroup label="Sub Cat 1">
      <option>The option here</option>
      <option>Another option here</option>
    </optgroup>
    <optgroup label"Sub Cat 2">
      <option>First op of subcat2</option>
      <option>Second op of subcat2</option>
    </optgroup>
  </optgroup>
  <optgroup label="Main Cat 2">
    <optgroup label="Sub Cat 1 of maincat2">
      <option>The option here</option>
      <option>Another option here</option>
    </optgroup>
    <optgroup label"Sub Cat 2 of maincat2">
      <option>First op of subcat2</option>
      <option>Second op of subcat2</option>
    </optgroup>
  </optgroup>
</select>`
```

I'd gladly donate something somewhere if I could get this modification :)

**Comment by flxmrk** [comment]
ahh well, I can never leave well enough alone ;)  I ended up making the necessary modifications.  If you want me to share, I'd be happy to, just not sure the proper means of sharing such mods on here.

**Comment by flxmrk** [comment]
Ahh smack spoke too soon - got the list appear perfectly, until you switch to one of the items in the list, then what appears selected is something much farther down the list.  I'll have to understand your events better in order to figure out why it does this.  If you got any clues, i'm all ears =)

**Comment by flxmrk** [comment]
figured it out, had to do with a optgroups that didn't have any direct descendent options.  Its all fully functional now.

**Comment by fnagel** [comment]
I'm not that happy to implement features based upon invalid HTML. But what about forking my branch, add your changes and pushing it to GitHub so anybody who needs could use it?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Reopen if needed.
