### ISSUE TITLE
New selectmenu implementation doesn't sync to the select element.

### ISSUE THREAD

**Issue by kfox1111** [fnagel/jquery-ui#278]
When elements are changed in the select menu, the hidden select elements are unchanged. In this example, a callback to watch for changes does not get fired if .selectmenu() is called. If you comment out the line, the alert fires as expected. If you inspect the DOM, the hidden select element does not change.

http://efox.cc/temp/jquery.selectmenu.html

**Comment by fnagel** [comment]
I'm sorry but I wasn't aware you're talking about the new official selectmenu widget. This GitHub accoun is for the older branch only. Please refer to the Selectmenu Wiki or the pull request next time:
https://github.com/jquery/jquery-ui/pull/492
http://wiki.jqueryui.com/w/page/12138056/Selectmenu

Regarding your question:
Selectmenu widget does not work that way you need to use the change callback. 

```
$('#speed').selectmenu({
    change: function(){
        alert($('#speed').val());
    }
});
```

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by kfox1111** [comment]
Sorry for the late reply.

I changed my code to use the change callback as suggested and things are working well. Thank you for the suggestion.

Not being able to simply use the native callback though is a bit confusing since other jquery ui widgets do use the underlying callback. Button for example. It may be a good feature to support in the future. More of a wish list item now though.

Thanks,
Kevin

**Comment by fnagel** [comment]
Problem is that there is no crossbrowser way to use these callbacks. We would need to to do some kind of event polling which is quite performance hungry.

Please feel free to start a discussion about this at the Wiki page, I'm sure Jörn or Scott are able to explain it much better.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by kfox1111** [comment]
Not sure what more to say. It works well the way it is, other then requiring ever so slight code changes to the javascript using it. If it can't reasonably be done because of lack of web browser support, that's totally understandable. Hopefully some day if that changes, then the support can be added. I've been using it for the last two months on my site and its been working great.

Thanks,
Kevin

**Comment by fnagel** [comment]
Ok, thanks for the feedback. I will close this issue for now.
