### ISSUE TITLE
$(document).bind('mousedown') etc gets fired on every click of the dom

### ISSUE THREAD

**Issue by charge-valtech** [fnagel/jquery-ui#279]
Hi there, I've noticed that this is getting fired even before the selectmenu has been opened, so every click on the dom fires this event 

```
// document click closes menu
            $(document).bind("mousedown.selectmenu-" + this.ids[0], function (event) {
                //check if open and if the clicket targes parent is the same
                if (self.isOpen && self.ids[1] != event.target.offsetParent.id) {
                    self.close(event);
                }
            });
```

I've edited mine so that it is inside the open: function and then put $(document).unbind(); inside the close: function is this something you were aware of?

**Comment by fnagel** [comment]
I must have missed that one, sorry! :-/

Can you post a demo fiddle? Its really easy, see #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
