### ISSUE TITLE
_setOption for icons

### ISSUE THREAD

**Issue by demonslord** [fnagel/jquery-ui#280]
Hello,
If you try change icons by setOptions:

$("#mySelect").selectmenu("option","icons",[ find:".item1",icon:"ui-icon-alert"]);

Select doesnt refresh.

Possible solution:
1. Create new function e.g: SetIcons
2. Call it in _init
3. Verify in _setOption, if == "icons", them call it.

Best Regards,
Alexander Bulei

**Comment by fnagel** [comment]
Hey Alex, that would be a feature request. Can you send a pull request?

**Comment by demonslord** [comment]
Hi fnagel,
yes i can.

Thanks.

Best Regards,
Alexander Bulei
