### ISSUE TITLE
Chrome/Icons not showing when demos run from web server

### ISSUE THREAD

**Issue by SirFizX** [fnagel/jquery-ui#284]
All the demos work fine locally however when I uploaded,extracted, and ran the demos from my web server the chrome/icons were missing. Please see pictures.
http://k55i.img-up.net/Local6e81.png
http://z18i.img-up.net/Serverd401.png

**Comment by demonslord** [comment]
Hi SirFizX,
Check your path's..(jquery theme, images...)

Best Regards,
Alexander Bulei

**Comment by fnagel** [comment]
Are you using the latest version?

**Comment by SirFizX** [comment]
Thanks. Once I started messing with the Super Theme Switcher I realized my paths were wrong. 
Great work!

Cheers,
Eric Eisaman
