### ISSUE TITLE
style options for height and hover?

### ISSUE THREAD

**Issue by jedierikb** [fnagel/jquery-ui#287]
Two styling questions the selectmenu community might be able to answer:

[1] 
How do I adjust the height of my selectmenus to match the height of other jQueryUI widgets such as the spinner?  Take a look at this fiddle:
(UPDATED LINK)
http://jsfiddle.net/YwLzn/

[2] How do I not show the menu styling on the selectmenu until mouseover?  Hoping to make the select menu look just like plain old text until the user mouses over and then see it is a selectmenu.

**Comment by fnagel** [comment]
_1:_ Adjust the according default CSS styles of Selectmenu

_2:_ Just init the Selectmenuon mouseover

**Comment by jedierikb** [comment]
Thanks, fnagel. 

regarding [1]
I am not sure where to make the change to adjust the height
http://jsfiddle.net/Tk7VQ/
does not work.

regarding [2]
I want the text in the selectmenu to stay in the exact same place on mouseovers/mouseout, and I think inits on mouseover might produce some offsets.  I was thinking to turn off the decoration on the selectmenu (the borders, etc.)  Your feedback on this is much appreciated.

**Comment by demonslord** [comment]
Hello,

Q1: You can override it by css style 
.ui-selectmenu { line-height:19px;height:19px}

Example: http://jsfiddle.net/kXgyM/

Q2: Something like this?

Examle: http://jsfiddle.net/jxZtq/

**Comment by jedierikb** [comment]
this is very helpful.

Q1:
Possible to vertically center the text in the selectmenu?
And possible to dynamically query and set the correct size instead of hardcoding it into the css?

**Comment by jedierikb** [comment]
Q2:
Something like this...
![mouseout](https://f.cloud.github.com/assets/374586/78863/1722732c-6196-11e2-9284-4a807e96860d.png)

and then on mouse over:
![mousever](https://f.cloud.github.com/assets/374586/78862/16fac638-6196-11e2-8be0-b52f17daeb51.png)

**Comment by fnagel** [comment]
Q1: 
Yes, just adjust the CSS: http://jsfiddle.net/kXgyM/1/
Mhh, no, this must be implemented by yourself. Perhaps by giving the Selectmenu wrapper classes.

Q2:
Try to remove the "ui-state-default" class on mouseover manually.
See: http://jsfiddle.net/kXgyM/5/

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
