### ISSUE TITLE
<select> as data source and formatter with the new official selectmenu

### ISSUE THREAD

**Issue by therazor** [fnagel/jquery-ui#289]
Hi there,

while trying to migrate from the version of selectmenu in this repository to the [new jquery version](https://github.com/jquery/jquery-ui/tree/selectmenu), I stumbled upon a couple of **issues**:
1. there is currently no built-in way to use the native `<select>` as a data source after initialization.  
   As hinted already in issues #270 and #278, this is because there is no widespread enough [mutation observers](https://developer.mozilla.org/en-US/docs/DOM/MutationObserver) support.
2. while it is possible to [modify the renderer](https://github.com/jquery/jquery-ui/blob/selectmenu/demos/selectmenu/custom_render.html) to implement the formatter option, that is only good if all the selects have to be formatted the same way.

These are the **solutions** I would suggest:
1. use the `.change()` event - the old version already [did that one way](http://jsfiddle.net/Razor/HtQ92/3/) already.  
   The new one [does not](http://jsfiddle.net/Razor/eEsAb/1/).  
   Implementing the change event both ways would allow to set the value simply with `$('select').val('x').change()` and get the value with `$('select').change(function(){ $(this).val('x') })`
2. simply bring back the `format` function, it seems to be the cleanest way to tackle this problem.  

does that sound reasonable?  
Any other ideas?

**Comment by fnagel** [comment]
1) There is a way to use the native select as da source after initialization: just call the refresh() method on the element to rebuilt the menu with all changed attributes!
You suggest to add something like `this.element.trigger( "change" );` to the _select() method, right?

2) A few other jQuer UI Widgets work this way and Im pretty sure it wont be changed, sorry :-/  Would you mind explaining the problem with the custom render implementation? I see no difference between setting an option or a method.

**Comment by therazor** [comment]
1. Yes, I would suggest to add that and `this.element.change( _select );`, with code to avoid infinite loops.  
   This could be a way to handle the lack of mutation observers and to keep in sync other code/plugins.  
   Refresh is not ideal when [conditionally loading](http://jsfiddle.net/Razor/J5a8U/) selectmenu.
2. AFAIK no other plugins need their base extended just to be formatted like [one of the "official" visual designs](http://wiki.jqueryui.com/w/page/12138056/Selectmenu) (last example in the pic)  
   Perhaps there could be a solution similar to [jquery mobile custom listview](http://jquerymobile.com/test/docs/lists/lists-formatting.html), but implemented with `data-selectmenu-aside`, `data-selectmenu-footer` etc?  
   The main problem is, with several different selects needing different formatting, using `_renderItem` would become a tightly coupled mess.

**It is possible to do all of the above already** using a custom `_renderItem/_select`, however I believe it would be rather nice to have built in support for those use cases, since they could reasonably be common enough.

**Comment by fnagel** [comment]
1) I understand your point and follow your argumentation. Perhaps @jzaefferer could join us here in order to have a UI team member with us when discussing this?

2) Please take a look at Autocomplete for another example for a render\* method. 
Anyway, I understand your intention but change requests like this need to be discussed with the UI team. 

Perhaps we should move the discussion to the Selectmenu Wiki as this seems the proper place for it.

**Comment by scottgonzalez** [comment]
We're not going to trigger native `change` events. On one hand, you're asking us to try to normalize back to the standard behavior of when `change` events occur, but on the other hand, you're saying that you want to change that behavior and trigger `change` events on your own when they wouldn't normally occur.

> Refresh is not ideal when conditionally loading selectmenu.

That seems like a very simple problem to work around with a small helper method.

> AFAIK no other plugins need their base extended just to be formatted like one of the "official" visual designs (last example in the pic)

It's impossible to include that data in a standard select. You would need a custom data source anyway, so you might as well have a custom renderer. If you don't like the idea of setting the render method, then create an extension which adds a formatter option.

> Perhaps there could be a solution similar to jquery mobile custom listview, but implemented with data-selectmenu-aside, data-selectmenu-footer etc?

We don't want to add one option, so we're definitely not going to add two options. We also will not implement options through `data-` attributes.

> The main problem is, with several different selects needing different formatting, using _renderItem would become a tightly coupled mess.

This is easily avoided by writing an extension. Our widgets are designed for this.

---

Please keep discussion of jQuery UI in the appropriate places. This discussion should have been initiated in [the planning wiki](http://wiki.jqueryui.com/Selectmenu), [the Developing jQuery UI forum](https://forum.jquery.com/developing-jquery-ui), or [#jqueryui-dev on IRC](http://irc.jquery.org/).

**Comment by therazor** [comment]
That sounds pretty definitive so just going to add that, while I know that everything can be added to the base widget as you said, I believe that these use cases might be common enough to justify an "official" implementation

Thanks to both for your time!

**Comment by fnagel** [comment]
THX @scottgondzales and @jzaefferer for helping out here!
