### ISSUE TITLE
Issue with jQuery 1.4.4

### ISSUE THREAD

**Issue by tuzemec** [fnagel/jquery-ui#29]
in the list, this part causes jQuery 1.4.4 to throw an error

```
.bind('mouseout blur', function(){
if($(this).is( self._selectedOptionLi() )){ $(this).addClass(activeClass); }
$(this).removeClass(self.widgetBaseClass + '-item-focus ui-state-hover');    
});
```

The error is "expr.replace is not a function" on line (jQuery source):
    4148: expr = expr.replace(/\=\s*(['"]])\s]/g, "='$1']");

Actually I'm not sure if this is a jQuery core bug, but when I change the bindings to "mouseleave blur" everything is fine.
Maybe it deserves a bit of investigation.

**Comment by michaelcaplan** [comment]
`.is()` is being passed a jQuery object, when it is expecting a string selector.  the call to `self._selectedOptionLi()` somehow needs to be addressed, but I'm not sure how.  `self._selectedOptionLi().selector` doesn't seem to do the trick.

Should the expression just be:

```
if($(this).is( 'li' )){ $(this).addClass(activeClass); }
```

?

**Comment by fnagel** [comment]
Please indent code with 4 spaces so that markdown puts it in a pre block.

**Comment by tuzemec** [comment]
Actually why do we need the self.selectedOptionLi() and self.focusedOptionLi() calls?

Can't we just toggle the two classes ("ui-state-hover" and self.widgetBaseClass + '-item-focus')?

So at the end we'll have just:

```
.bind('mouseenter focus', function(){
    $(this).addClass(self.widgetBaseClass + '-item-focus ui-state-hover'); 
})
.bind('mouseleave blur', function(){
    $(this).removeClass(self.widgetBaseClass + '-item-focus ui-state-hover'); 
});
```

That will even eliminate the weird bug that was causing in some cases the slected li to loose it's "ui-selectmenu-item-selected" class.

**Comment by bluefox** [comment]
I second tuzemec's change, I've removed the check (there are two places) and it seems to be working fine without them.

**Comment by tuzemec** [comment]
Then I guess we can close this issue. It works fine with the latest changes.
Thank you, Felix :-)

**Comment by fnagel** [comment]
Some of my comments (last night) are missing. I dont know why, guess its GitHub...

...you're right. I fixed this problem. Please test!

@michaelcaplan
Why dont use selector? Works fine for me so far!

**Comment by tuzemec** [comment]
Yeah, it seems github went crazy for a moment.

There's another bug connected to the mouseenter / mouseleave. I think I know how to fix it, but it will be better if I fill it in another issue later today.

**Comment by fnagel** [comment]
Closed, as this issue is resolved.
