### ISSUE TITLE
Text missing in list items and in button

### ISSUE THREAD

**Issue by bigsmoke** [fnagel/jquery-ui#290]
After upgrading to jQuery 1.8.3 / jQuery-UI 1.9.2 and selectmenu 1.30, the anchors in ul.ui-selectmenu-menu-dropdown no longer have any text content (only the 'html' attribute is set). Neither does span.ui-selectmenu-status.

The following functions as a temporary work-around to fix the labels ...

``` javascript
jQuery('div.ui-selectmenu-menu a').each(function(){
      $(this).html($(this).attr('html'));
});
```

and to fix the currently selected item ...

``` javascript
  $('#my-select-button span.ui-selectmenu-status').text( $('#my-select option:selected').text() );
```

I still suspect that the bug lives somewhere between the keyboard and the chair, but I spent enough time on it to think it wise to submit this.

**Comment by bigsmoke** [comment]
I forgot to mention that I also tried the newest dev. version of fnagel-jquery-ui. Same problem.

**Comment by fnagel** [comment]
No problem, you're welcome!

Is this problem reproducible in the latest testing fiddle? See #61 
Any specific browser?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
