### ISSUE TITLE
Clicking on item in menu that has already been selected?

### ISSUE THREAD

**Issue by dmcgrew** [fnagel/jquery-ui#292]
I am using selectmenu with isotope. The problem I'm having is hard to explain so I'll try to explain it with the following scenario...

Lets say I have 2 selectmenus.

<b>Menu 1</b>
Dogs
Cats 
Birds

<b>Menu 2</b>
Red
Blue
Green

I have isotope filtering tied to each of these menus and I only want to filter by 1 of them at a time (no combo filters). First I choose Dogs from Menu 1, then I choose Blue from Menu 2. So far, so good, isotope filters my elements that are tagged with Blue. Now the problem comes when I try to select Dogs from Menu 1 again. That menu acts as if I already have something selected and I cannot select it again. Thus I can't go back and select Dogs. What I have to do is select something else in Menu 1, then select Dogs to get it to work. I'm assuming this is working as designed but is there any way around it?

Thanks!

**Comment by Romanow88** [comment]
You can add a custom onclick event handler for the list of items that appears, where you can get the selected item value and do your filtering logic.

**Comment by fnagel** [comment]
Are you aware of the differences of the select and change callback events? As @Romanow88 mentioned you should be able to built the needed functionality based upon these events. I already did for different websites, for example: http://www.klosterfrau-marke.de/unsere-produkte.html

If you're able to post an example of your problem in a fiddle I assume our help could be more precise! See #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
