### ISSUE TITLE
Nested items

### ISSUE THREAD

**Issue by ppritcha** [fnagel/jquery-ui#295]
I'd like to have support for nested items, like in the jqueryui menu widget.  For example, there would be a right-pointing arrow next to an item, like "Delphi" in the example here: http://jqueryui.com/menu/.

**Comment by fnagel** [comment]
This won't happen for this legacy branch.

But this should be possible with custom renderer for the upcoming official
jQuery UI Selectmenu Widget, see #140

**Comment by ppritcha** [comment]
Thanks for the response!

If I understand correctly, that means that when the official Selectmenu widget is released as some point in the future, I'd be able to write a custom renderer for it that would display the arrow and handle showing the second window of nested items.  I was hoping for some built-in support, but since the official version seems to be a somewhat stripped-down version of the widget here, it looks like I may be on my own to develop the functionality I need.  Are there any plans to add more features to the official Selectmenu widget at a future time?

**Comment by fnagel** [comment]
Yes, thats right. It should be possible as we utilize Menu Widget anyway. 

Having a submenu in a selectmenu is a special use case and I don't think this is considered important enough as even the pop-up support has been dropped. The official selectmenu is less feature rich than this branch, but much faster, reliable and stable. And thats a good thing. The old implementation has issues from positioning to accessibility and is some parts are hardly to maintain.

I assume a lot of people will complain as most see this branch as an official (which it never was) and will miss some of the features like pop-up style, index and value methods, etc.
Perhaps there will be add-ons like this one for pop-up style: https://github.com/fnagel/jquery-ui-extensions

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
