### ISSUE TITLE
SelectMenu stops working in IE8 when DOM changes 

### ISSUE THREAD

**Issue by chernobil** [fnagel/jquery-ui#298]
Hi
the issue is only in IE7 and IE8 - the select menu stops showing when there is some DOM changing event (hide/show element for example) at the time when the selectmenu has to be opened. One of the reasons for the issue is that these browsers trigger window.resize not only when the actual window is resized but even when you show/hide element (and many other cases) . 
Here is an example http://jsfiddle.net/EUNBj/2/ (btw jsfiddle doesn't work in Browser Mode IE8 of the IE) so you won't be able to see the problem with modern browser, but it's good ilustration .
To reproduce the issue in the example : 
1. type something in the input 
2. click the select menu bellow 

I'm using jQuery UI Selectmenu version 1.3.0. And have developed the following "fix" on line 267 : $( window ).bind( "resize.selectmenu-" + this.ids[ 0 ], $.proxy( self.close, this ) );
changed to 

```
var lastHeight = $(window).height();
var lastWidth = $(window).width();

        // needed when window is resized
        $(window).bind("resize.selectmenu-" + this.ids[0], $.proxy(
            function (e) {
                if ($(window).height() != lastHeight || $(window).width() != lastWidth ) {

                    //set this windows size
                    lastHeight = $(window).height();
                    lastWidth = $(window).width();

                    self.close(e);
                }
            }, this));
```

This solved it. The idea is not to close the select menu on window resize unless it's an actual resize

**Comment by fnagel** [comment]
Would you mind to test if this issue is still a problem in latest version?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please re-open if needed.
