### ISSUE TITLE
Menus on a non-modal dialog show underneath the dialog window

### ISSUE THREAD

**Issue by ubunoir** [fnagel/jquery-ui#300]
When a menu is opened on a non-modal dialog, it gets covered by the dialog window.

Here's a fiddle for the latest library version:

http://jsfiddle.net/BN9Tu/2/

I've tested it on IE9 and Firefox 20.0.1. 

The problem seems to be with the mousedown handlers which increment z-index both in the selectmenu (fired first) and in the dialog (fired second). They result in the same z-index value for the menu and the dialog.

For example, in the `_refreshPosition` function:

``` javascript
        this.listWrap
            .removeAttr( 'style' )
            .zIndex( this.element.zIndex() + 1 )
            .position( $.extend( positionDefault, o.positionOptions ) );
```

`this.element` z-index is initially 1001, so `this.listWrap` z-index is getting incremented to 1002.

Then, in the ui.dialog `moveToTop` function, we have:

``` javascript
        $.ui.dialog.maxZ += 1;
        this.uiDialog.css( "z-index", $.ui.dialog.maxZ );
```

where `$.ui.dialog.maxZ` is also getting incremented from 1001 to 1002.

**Comment by fnagel** [comment]
Problem verified.

It seems this is due to dialog changes. Any idea how to solve this problem?

ps: are you aware there is a almost ready version that (hopefully) will be shipped with jQuery UI 1.11? See #140

**Comment by ubunoir** [comment]
Don't know nothing about any dialog changes, but one thing is worth noting: 

The following commit https://github.com/fnagel/jquery-ui/commit/690bbee3f0798ba944111f46d10f540803b7f224 has caused that the dialog's mousedown handler, which brings it to the top, started to work when opening a menu. Before it was blocked by the selectmenu's mousedown handler.

For a temporary solution I made a simple workaround for this problem - I'm adding 2 to z-index instead of 1:

``` javascript
        this.listWrap
            .removeAttr( 'style' )
            .zIndex( this.element.zIndex() + 2 )
```

It works fine for me, but I don't think it can be regarded as a proper solution.

PS. Yes, I heard about the UI 1.11 version. Looking forward to it.

**Comment by fnagel** [comment]
Thanks for pointing this out! 

We'll see if a proper solution could be found. Thanks for your contribution!

**Comment by escapedcat** [comment]
I'll check it and get back to you as soon as I get to it.

**Comment by escapedcat** [comment]
Hey guys,

I think we should stick to allow eventPropagation.
Cause also in this case there's a valid reason to allow it. The mousedown will bring the modal to the top (if it's behind another modal). And this should also happen, when clicking on the selectmenu or any other element within the modal.

Have a look here:
http://jsfiddle.net/escapedcat/VsU9A/
Open both modals and place the foo-modal a bit over the selectmenu-modal. Clicking the the hidden selectmenu-modal brings it to the front. Also when you click the selectmenu, cause we allow propagation. 

But I get the problem that the selectmenu-menu is hidden now :)
I'm not aware of all the dependencies regarding z-index in jQuery UI. For me it looks like that '+2' is a valid solution atm.
But let me know your feedback, thanks.

**Comment by fnagel** [comment]
This one is definitly related: #293

**Comment by fnagel** [comment]
+2 works for now. We'll stick to this for now. Brand new Selectmenu is coming soon!

Please check latest commit and give feedback! I've added a dialo.html demo file. 
Hopefully we'll not run into problems like this as the new Selectmenu has a bunch of unit tests.

**Comment by ubunoir** [comment]
All works fine for me. Thank you for the support!

**Comment by fnagel** [comment]
Nice, thanks for the feedback. 

@escapedcat Could you test this as well?

**Comment by fnagel** [comment]
Pushed another follow-up fix, please test again if possible.

**Comment by escapedcat** [comment]
@fnagel Yep, I'll test and check the html/body issue as well as soon as I have time.

**Comment by fnagel** [comment]
Any feedback for this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
