### ISSUE TITLE
Error on 'instance' for menu widget instance

### ISSUE THREAD

**Issue by pdias** [fnagel/jquery-ui#304]
Hello,

I do not know if it is the correct place to put this question.

I am using jquery.ui.selectmenu (http://api.jqueryui.com/selectmenu) with jquery ui 1.10.3, but i always have this error:

`Error: no such method 'instance' for menu widget instance`

Can you help me?

Thank you,

Paulo

**Comment by fnagel** [comment]
Seems you are using new API with old selectmenu.
I guess you're using element.selectmenu("instance"), right?

Mind the difference:
This branch is legacy and works with older UI versions.
Official version (see #141) for current / future branches.

**Comment by pdias** [comment]
Thanks for your response and "yes, you were right".

But i have another question... 

When we create an option, eg "Choose your gender ..." and this option disabled in the list ...
When selectmenu is created, this option appears selected by default ... the question is, is there any way to change eg the color of the text (like a placeholder) ?

Thanks again,

Paulo

**Comment by fnagel** [comment]
Mhhh, nothing implemented I guess. But you could search for the first element by using the widget method.

The new selectmenu is easy to exend. Just change the renderItem method.

**Comment by pdias** [comment]
Ok, i will test.

Thanks,

Paulo
