### ISSUE TITLE
Losing focus

### ISSUE THREAD

**Issue by pdias** [fnagel/jquery-ui#306]
Hello,

In dropdown style, if you click and click the box again closing it, without selecting anything new, it loses focus. After that you can't use the arrows unless you tab away and tab back.

That this happening with jquery ui 1.10.3, tested with 1.9.2 and everything is ok ...

Tests were done with IE10 and Firefox 21.0

Example:

http://jsfiddle.net/psaid/Kfwc6/2/

Thanks,

Paulo

**Comment by fnagel** [comment]
This fork does not work with jQuery UI 1.10.x and probably never will as there is a new, upcoming official Selectmenu Widget in work. Please see: #140

**Comment by pdias** [comment]
Ok and thanks

Paulo

**Comment by fnagel** [comment]
Please feel free to ask for help or give feedback!
