### ISSUE TITLE
Significant lag when removing and adding select options

### ISSUE THREAD

**Issue by kwienken** [fnagel/jquery-ui#307]
I have an application that changes the available options on several selects based on the value of a dependent field. When calling .selectmenu() again on just one select after removing one option there's no lag. But, when adding/removing multiple options on multiple selects and then calling .selectmenu() again there's about a 3 second lag. I've noticed the lag updating 7 selects with 2-10 options.

**Comment by fnagel** [comment]
Demo? #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
