### ISSUE TITLE
Wrapping selectmenu in div for css theme scope

### ISSUE THREAD

**Issue by torrentx** [fnagel/jquery-ui#31]
On the open event, this.list is always being appended to the body.

I had attempted to wrap the selectmenu in a div like $(#id-menu).wrap('in a div with a class for the scope'); 
Should I be doing this a different way or perhaps update the open event to reappend to it's previous parent?

**Comment by fnagel** [comment]
What would you like to do? Do you like a custom styling for some selectmenu lists?

**Comment by torrentx** [comment]
Yup.  Basically I'm wanting to apply separate themes like: http://www.filamentgroup.com/lab/using_multiple_jquery_ui_themes_on_a_single_page/

**Comment by fnagel** [comment]
I will add a wrapper div option soon. Please be patient as there are a lot of issues atm.

**Comment by torrentx** [comment]
Thank you!  It's a great plugin, and your work on it is much appreciated.

**Comment by sirsk** [comment]
i improve similar feature in the latest version ..
adding a line like to default settings at the beggining
code of  jquery ui selectmenu..( line 20 for example )

<code>
options: {
        transferClasses: true,
        style: 'dropdown',
        ----> labelx: 'body',
</code>

where labelx is the wrapper to the container and body the default value 
in case the user do not include a option in call to the fuction selectmenu();

And after that i change line 136

<code>
 from -> .appendTo('body') 
 to -> .appendTo(o.labelx)
</code>

next i change the line 398

<code>
from -> .appendTo('body')  to -> .appendTo(this.options.labelx)
</code>

finally i call the fuction at the same form
includind the wrapper of my choise

<code>
.selectmenu( { labelx: '#div_that_you_want' } ) ;
</code>

Maybe you want minified the code ... 
down from 18 kb -> to 13 kb
http://www.minifyjs.com/javascript-compressor/
ENJOY -> jquery.ui.selectmenu.min.js 

Hopping this maybe help you..
Diego

**Comment by fnagel** [comment]
Hey Diego, 

so your fix is an option to add the list elements to a defined element. Not sure for what your improvement is useful for.This issue is about wrapping all added elements to a div so we can use different jQuery UI Theme.

Ive added an option called wrapperElement which wraps all added elements into a HTML tag. $.wrap parameters accepted, so something like:
    "<div wrap class="wrap" />"
could be used.

Please give feedback!

**Comment by sirsk** [comment]
is a way to display controls with diferents themes like rows in one page...

for example
1st row ( ui-darkdarness )
2nd row (ui-start)
...

**Comment by torrentx** [comment]
@fnagel  Thanks for the update.  It might be a few days before I get a chance to check it out.

**Comment by fnagel** [comment]
@torrentx and @all
Any feedback yet? Would be nice to close this issue.

**Comment by torrentx** [comment]
@fnagel.  Pulled the latest today and tested it.  PERFECT!  Thank you!

**Comment by fnagel** [comment]
Thanks for the feedback. Closed, please reopen of necessary.
