### ISSUE TITLE
Ideas to get the option label

### ISSUE THREAD

**Issue by pdias** [fnagel/jquery-ui#310]
I know it is not the best place to put this question ... so my apologies.
I need to pick the option label ... is there any way to do this?

I do this to get the value:

```
$('select#otheraddress_country').selectmenu("value")

```

if i have Portugal selected i get PT....

But i need also the option label... in this case "Portugal".

Thanks,

Paulo

**Comment by fnagel** [comment]
Can you give me an example what you need? See #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by pdias** [comment]
Sorry for not responding quickly, but I was on vacation and when I returned things were a bit complicated.

On this issue, could not solve using SelectMenu. I chose to perform a search on the server side.

Thanks,

Paulo
