### ISSUE TITLE
enable and disable has been swapped

### ISSUE THREAD

**Issue by snorrekim** [fnagel/jquery-ui#312]
In a changeset https://github.com/fnagel/jquery-ui/commit/fc576eacc4df048e64719761b72ce9fb8d92d3c9 about 9 months ago I believe a bug was introduced: 

It basically swapped the functionality of "enable" and "disable".

Now, if you want to disable an option, you have to use $('select').selectmenu("enable", 2). 

The current comment "// true = enabled, false = disabled" above _toggleOtpgroup is misleading as it actually the other way around. It also leads me to believe that the implementation error should be fixed there, as the intent is probably what the comment is saying.

Even though the demo "disable_enable.html" was updated to support the change at the same time I doubt that this was intentional. It is confusing and the comment in the code says it should be the other way around.

**Comment by fnagel** [comment]
Problem confirmed. Working on a solution right now...

**Comment by snorrekim** [comment]
Should note that it seems that the "aria-disabled"  bool is set correctly.

**Comment by fnagel** [comment]
I've pushed a fix. Please test and give feedback!

**Comment by snorrekim** [comment]
Sorry for taking so long to get back to you. I've taken a look and although I am not sure what it is used for I believe the field "aria-disabled" is set wrong now. I think that was the only field that was correct before. I don't know exactly how that field is used though, so I might be wrong, I haven't noticed any effects from it being set like this.

**Comment by fnagel** [comment]
I'm pretty sure aria-disbled is correct now. I've double checked again :-)
Only thing remaining issue was that aria-disabled (a boolean property) was set as "disbaled" when an option is disabled by HTML on init.

The general functionality works again?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed. Please re-open if needed.
