### ISSUE TITLE
Selectmenu closes dropdown when moving scrollbar

### ISSUE THREAD

**Issue by alesnav** [fnagel/jquery-ui#317]
Hello there!

I had problems with selectmenu because when the select list is very large and a scrollbar appears, if you try to move that scrollbar you will get selectmenu closed.

You can solve this issue by adding a new condition in "if" clause on line 162:

&& !$(event.target).hasClass('ui-selectmenu-menu-dropdown')

This way, the whole "if" clause would be:

if ( self.isOpen && !$( event.target ).closest( "#" + self.ids[ 1 ] ).length && !$(event.target).hasClass('ui-selectmenu-menu-dropdown'))

I don't know if this is the best way to solve it, but works perfect.

Thanks!

**Comment by fnagel** [comment]
We had a similar issue fixed a few days ago, did you test latest version?

If the problem persists, would you mind posting a demo fiddle? See #61

**Comment by alesnav** [comment]
Well, you can see it in your own example:

http://jsfiddle.net/fnagel/GXtpC/

Expand the select with label "Select an Address" and try to move the scrollbar. You can't.

Thanks!

**Comment by fnagel** [comment]
Sorry for the delay, pretty busy atm.

Problem confirmed. Seems like a regression. Any idea?

**Comment by fnagel** [comment]
This is related to #309. Fixed in 32689789772a74b90f92b712d205745b1a2eb1d2

**Comment by alesnav** [comment]
Ok fnagel, it works now.

No problem, we understand that the time is more expensive than gold!!

Thanks!

**Comment by alesnav** [comment]
Uh, sorry, I thought I reopened it -_-
