### ISSUE TITLE
IE7 and IE8 .focus() problem

### ISSUE THREAD

**Issue by cyclecz** [fnagel/jquery-ui#318]
Hi,

I had a problem with IE8 in 1.4.0pre version on line 562 and I identified the problem that IE 7+8 cannot focus not visible element. 

So code:

```
if ( link.length ) {
    link[ 0 ].focus();
}
```

I changed to:

```
if ( link.length ) {
    if ( $(link[ 0 ]).is(':visible') ) { link[ 0 ].focus(); }
}
```

And works fine.
cyclecz

**Comment by fnagel** [comment]
Is this reproducible in default demo? Please see #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given.
