### ISSUE TITLE
selectmenu not working with jquery 1.4.3 and jquery ui 1.8.6

### ISSUE THREAD

**Issue by mondo1287** [fnagel/jquery-ui#32]
Have I done something wrong or is this a bug?  I cannot get selectmenu to display properly on any browser.

Here's my test:
http://www.mondotech.org/jquerytesting/jqueryselect/

**Comment by dannycohn** [comment]
It looks like you forgot to include the selectmenu css file...

**Comment by fnagel** [comment]
dannycohn seems to be right, please note that the selectmenu widget is no official one so its specific CSS is not included in the API files.
