### ISSUE TITLE
Selected Option Text

### ISSUE THREAD

**Issue by calvinlloyd** [fnagel/jquery-ui#320]
I would like to edit/replace a string within the selected option text upon selection...for instance, suppose the options in the dropdown are 'a: cat', 'b: dog' and c: mouse'...if user selects 'a: cat', i want the selected option text to only display 'cat'...without the 'a: '

is this possible?

**Comment by fnagel** [comment]
No, this is not possible by using an option. You probably could do this by using a callback method, please see the wiki.

**Comment by fnagel** [comment]
Closed. Please re-open if needed.
