### ISSUE TITLE
Problem changing the value of a hidden select

### ISSUE THREAD

**Issue by alesnav** [fnagel/jquery-ui#321]
Hello!

I added a comment in a very old issue (https://github.com/fnagel/jquery-ui/issues/58), but I think that open a new one will be easier.

I am using Fancybox, but the problem is the same than tabs. I must init selectmenu this way:

$("select").hide();
$("select").peek("selectmenu", { inline: true });

The first line is needed because selectmenu function initialized from peek won't hide select elements on the page.

My second question (I tried to get it done, but I couldn't :( ) is: how I can change the value of a select that is already hidden?

I tried with:

$('select#fsector').selectmenu("index", 0);

And it changes the value, yes, but visually it does not select the value. Then, I tried to do it using Peek... but I don't know how to use it for this purpose...

Any idea?

Thanks!!

**Comment by fnagel** [comment]
Thanks for opening a new issue, I was not aware of the new comment on the old one.

All you code snippet seem correct and I should work as you expect. I would say there is some side effect or project specific issue that breaks your code. I willing to help you but I would ask for a demo fiddle or something I could test and edit without building a similar setup myself. Please take a look at #61 -- it's pretty simple to post a minimal demo fiddle.

Yours
Felix

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given.
