### ISSUE TITLE
Menu not scrollable on Android 2 (Gingerbread)

### ISSUE THREAD

**Issue by brlewis** [fnagel/jquery-ui#322]
A bug in old versions of the Android browser prevents internal divs from scrolling. I fixed this locally by leaving the height as auto if navigator.UserAgent contains 'Android 2'. This is more of an issue today because new cheap phones are coming out running Gingerbread because they don't have enough memory for Honeycomb, or Ice Cream Sandwich.

**Comment by fnagel** [comment]
I agree this is a problem which should be addressed. Is it reproducible by using the default demo?
Are you able to provide a possible fix? Please see #61 or send a PR!

Please note this version of Selectmenu has several mobile issues atm, see https://github.com/fnagel/jquery-ui/issues?labels=mobile

**Comment by brlewis** [comment]
It's reproducible in any demo where on desktop the menu has a scrollbar. Unfortunately you need an emulator or device running Android 2. The fix was done on my employer's time. Although they probably wouldn't mind me contributing it, it might be simpler if you implemented it independently. Let me know if you want me to chase down the proper permissions anyway.

**Comment by fnagel** [comment]
I'm currently busy on other projects so this will need to wait until
somebody provides a fix or is willing to sponsor development.

**Comment by brlewis** [comment]
Pull request: https://github.com/fnagel/jquery-ui/pull/323

**Comment by brlewis** [comment]
Hi,

Any comment on my pull request to resolve this issue?

**Comment by fnagel** [comment]
Sorry for the delay, I'm pretty busy atm.

Merged. Thanks for the contribution!

**Comment by brlewis** [comment]
You're welcome, and thanks for merging.
