### ISSUE TITLE
"menuWidth" option is not working in IE8,IE7

### ISSUE THREAD

**Issue by dkedar** [fnagel/jquery-ui#324]
I used this Jquery Plugin in one of my website.
Its very useful for UI Development.

I have samll Issue that "menuWidth" option is not working in IE7 and IE8. Is there any other solution?

Please let me know.

**Comment by fnagel** [comment]
Please add a demo fiddle to reproduce, see #61

**Comment by dkedar** [comment]
I have checked my Jquery Code, and I found that I wrote multiple document.ready tags into single js file. Also in HTML Code jquery file duplicated. I have removed the duplicated versions of Jquery and I also removed the the multiple instances of document.ready function. now the code is working fine. thnaks

only I have one question is that which lower version of Jquery is supported to this plugin
currently I am using 1.6.4 version of Jquery

**Comment by fnagel** [comment]
Good to hear uts working for you now.

This plugin was tested with jQuery version 1.6.4 in release 1.2.1. Perhaps some newer version will work, too -- the latest ones will not work. Please see readme for more info:
https://github.com/fnagel/jquery-ui/blob/selectmenu/readme

**Comment by fnagel** [comment]
Closed as no feedback was given and issue seems solved.
