### ISSUE TITLE
Dropdown menu closes when its scrollbar is clicked on

### ISSUE THREAD

**Issue by ianthedev** [fnagel/jquery-ui#325]
The displayed dropdown menu closes when its scrollbar is clicked on.

This issue has been seen on Firefox and Google Chrome.

**Comment by fnagel** [comment]
Which version are you using? 
Problem seems not reproducable in latest FF and default demo: http://jsfiddle.net/fnagel/GXtpC/

**Comment by ianthedev** [comment]
The plugin's version is 1.5.0pre. Firefox is 27.0.

And I use the latest jQuery (1.10.2) and jQuery UI (1.10.4).

**Comment by fnagel** [comment]
Are you able to reproduce this issue in the posted fiddle (which uses latest commit)?
I'm not, neither in Chrome 32 nor in FF27/28beta using Windows7.

Please note this plugin is not tested in latest jQuery and jQuery UI! Please see: #286 

You could try the upcoming official jQuery UI Selectmenu Widget, see #140

**Comment by ianthedev** [comment]
Yeah, the demo on jsfiddle works. I will try to find the cause. Thanks.

**Comment by fnagel** [comment]
I guess its the newer jQuery UI version, try that first!

**Comment by ianthedev** [comment]
I got it. It turns out to be caused by the minified plugin code which I manually packed at a javascript packer (http://dean.edwards.name/packer/).

I repacked at there again and use the new minified code, and everything works fine. I also tested using the previously minified code again, and the same issue occurs. Therefore I had confirmed the issue was caused by the previously minified code.

And why I repacked it again and it works? I really don't know. At least it works fine now.

**Comment by fnagel** [comment]
Mhh, thats a strange error. I added a issue to introduce proper unit tests and linting, perhaps its the code itself. See #327

**Comment by ianthedev** [comment]
Thank you.

**Comment by mainman** [comment]
Hi,  I've got the same problem on FF Aurora 29 a2. But code not minified... I'm in dev.
1.5.0pre
jquery 1.10.2
jquery-ui 1.10.3
Problem occurs since updating in jquery 1.10
Thansks for any help

**Comment by fnagel** [comment]
Sorry for the late response -  very busy atm.

Can you provide a demo fiddle or a link? See #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by ianthedev** [comment]
It seems to work fine now. Thanks.

**Comment by fnagel** [comment]
Great!
