### ISSUE TITLE
Set class?

### ISSUE THREAD

**Issue by ianthedev** [fnagel/jquery-ui#328]
Can we set a class name through options? Other ui's have that option.

**Comment by fnagel** [comment]
You could use "transferClasses" option or use the widget method to modify generated elements like every other jQuery UI Widget does.

**Comment by ianthedev** [comment]
Sorry, I didn't see an option called "transferClasses" in the [documentation](http://wiki.jqueryui.com/w/page/12138056/Selectmenu). Could you elaborate on its usage?

**Comment by fnagel** [comment]
You are using the old legacy version, a private fork I work on in my free
time. It's documentation is here:
https://github.com/fnagel/jquery-ui/wiki/Selectmenu

The wiki site you linked to is the original, not yet released one I'm
working on for jQuery UI.

Please consider reading the readme of this project. Or the Wiki page you
linked to.

**Comment by ianthedev** [comment]
Thanks. It's description says: "Transfer classes from select". I still don't understand. Could you explain?

**Comment by ianthedev** [comment]
Please explain?

**Comment by fnagel** [comment]
The option transfers all (CSS) classes from the original select to the generated one.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by ianthedev** [comment]
I'm sorry. I have no idea about what you were referring to.

**Comment by fnagel** [comment]
I just wanted to have some feedback if you managed to fix your issue and if this ticket could be closed.

**Comment by ianthedev** [comment]
Sorry. I mean I don't know what the following explanation means:

`
The option transfers all (CSS) classes from the original select to the generated one.
`

**Comment by fnagel** [comment]
When transferClasses option is enabled all classes set for the original, native select will be transfered to the generated menu. So <select class="test">...</select> will result in <a class="test selectmenu ui-widget ui-state-default ui-corner-all">...</a>

Please note that this option has been removed some time ago and is no longer available in the latest versions, see #229

**Comment by ianthedev** [comment]
I see. Thanks.
