### ISSUE TITLE
An option to disable auto-setting width?

### ISSUE THREAD

**Issue by ianthedev** [fnagel/jquery-ui#329]
Is there an option to disable auto-setting dropdown menu's width?

**Comment by fnagel** [comment]
Please check the wiki for all available width options.

**Comment by ianthedev** [comment]
Thanks. There doesn't seem to have one. Could we have one in future builds?

**Comment by fnagel** [comment]
I dont't think we need another width config. What's your usecase?

**Comment by ianthedev** [comment]
I had found that setting width to "auto" works exactly as expected. Thanks.

**Comment by fnagel** [comment]
Nice!
