### ISSUE TITLE
Need a way to set the value programatically

### ISSUE THREAD

**Issue by dannycohn** [fnagel/jquery-ui#33]
There doesn't seem to be a way to set the value of the selectmenu programmitcally. For example, if I had a select element with id "mySelectElement" that I made into a selectmenu, and i wanted to select one of the options, I should be able to do 

<code>
$('#mySelectElement').selectmenu();
$('#mySelectElement').selectmenu('setValue', 'valueOfThirdOption');
</code>

As it stands now, I can set the value if I know the index of the option that I want to select, but why can't I set the value using the value itself, just like I would a non-selectmenu select element <code>$('#selectElement').val('valueOfThirdOption')</code>

**Comment by fnagel** [comment]
You would like to to set the value (the current selected option) via its value attribute:

```
<option value="VALUE">somewhat</option>
```

so you could use it like this:

```
$('#mySelectElement').selectmenu('setValue', 'VALUE'); 
```

to set the value (the current selected option) of the select. Did I get you right?

Shoudl be easy to implement. We need a check if the parameter to the value method is a number or a string.

**Comment by dannycohn** [comment]
That's what I'm looking for.  

Checking if it's a number would be ambiguous though.  What if the values of my options are numbers.  Yes, I could pass in the number a a string to be sure it was treated as a value and not an index, but it's somewhat ambiguous.  The 'value' function that already exists shouldn't really ever treat the parameter as an index, since the function name is 'value'.  There should be a separate function called 'index' or 'selectedIndex' that takes an index as a parameter.  Such an egregious flaw in function naming might warrant breaking backwards compatibility for existing implementations of selectmenu.

**Comment by caerphoto** [comment]
As far as I understand it, the actual values for each `<option>` are always strings, so it'd be easy enough to tell what action needs to be taken based on the type of the parameter passed to `value()`.

On the other hand, I agree that `value()` is not a good name for the function as it is, since it doesn't change or retrieve the value of the select element, merely its selected index. In the meantime, this should work for most cases:
    value: function(newValue) {  
        if (arguments.length) {
            switch (typeof newValue) {
                case "number": {
                    this.element[0].selectedIndex = newValue;
                    break;
                }
                case "string": {
                    this.element[0].value = newValue;
                    break;
                }
                default: { }
            }
            this._refreshValue();
            this._refreshPosition();
        }
        return this.element[0].selectedIndex;
    },

With this, you can either call `$someElement.selectmenu("value", 3)` to select the 4th item (i.e. item with index 3), or alternatively `$someElement.selectmenu("value", "FOO")` to select the item that has the value "FOO".

**Comment by fnagel** [comment]
Ive commited a version with correct method naming. I added some kind of legacy support based upon caerphoto post so its still possible to use 
     .selectmenu("value", 4)
to select a option based upon its index. Usage of 
    .selectmenu("value")
as a getter (to retrieve the index of the currently selected option) is no longer possible. Use this code instead:
    // as setter
     .selectmenu("index ", 4)
    // or as getter
    .selectmenu("index")

Please test and report your feedback so I could close this issue.

**Comment by cburgdorf** [comment]
+1 for not setting the index if the value is a number. Consider that you are setting values retrieved from a webservice that come as numbers. You would have to set them like this:

$truck.selectmenu("value", tour.TruckID + "");

**Comment by fnagel** [comment]
Your right. A environment as you mentioned it above would cause problem atm. So what is more important? Legacy support or API consistency? Some opinions please, we need a democratic decision here :-)

I plan to release tagged versions in the near feature to have better possibilities to test and commit dev versions. Perhaps the current legacy support should be dropped with the first tagged (aka v 1.1.0) version?

**Comment by dannycohn** [comment]
API constancy is more important.  This is not a final release so it is expected that APIs can change.  jQuery standard is to have a "val" or "value" function that accepts a string or number and sets the value to that argument.  The fact that select inputs also have an index associated with them is irrelevant, the value is the value, not the selected index.

**Comment by caerphoto** [comment]
FWIW I agree with dannycohn - any new users of the selectmenu are likely to be confused if they get different results depending on the typeof value parameter, especially when there's now an 'index' method as well.

**Comment by cburgdorf** [comment]
+1 for a clean API

**Comment by fnagel** [comment]
So the legacy support will be removed with tagged version 1.1

**Comment by fnagel** [comment]
Legacy support has been removed in latest commit.
