### ISSUE TITLE
Surplus event following keyup

### ISSUE THREAD

**Issue by sronsiek** [fnagel/jquery-ui#332]
Where there are drop-downs with large numbers of options,  keypress functionality comes into it's own. I have tried this in various browsers with and without this plugin, and have noted the following:

Without selectmenu: Open a drop-down, mouse happens to be over any of the options. The selected option is the one the mouse is over. Now select a different option via keyboard entry to select by leading letters of an option. On the last keyup the highlighted selection remains the one last selected via keyboard (the mouse has not moved).

Repeat the same with selectmenu, and the highlighting seems to go to the correct option, but then immediately jumps back to the option under the mouse. 

It seems like a surplus mouseover event is being fired after the keyup - possibly only the first time.

Any workarounds for this?

**Comment by fnagel** [comment]
I'm very sorry, but I'm currently too busy to fix an issue like this. Typeahead is a really f***ed up feature and it seems this a ugly bug you've spotted here. This fork is coming to an end as the official Selectmenu Widget already landed in the jQuery UI master branch, see #140 for more information.

In short: I work on this in my spare time and I'm not willing to fix this on my own. Patches and PRs are welcome. Sponsoring is possible too.

**Comment by sronsiek** [comment]
Can you price a fix?

**Comment by fnagel** [comment]
Please write me an email: info AT felixnagel DOT com

**Comment by fnagel** [comment]
I did not receive any email from you, is this issue still a problem?

**Comment by fnagel** [comment]
Ok, I tried to reproduce this but without success. I testing with latest dev version on Win8.1 and latest FF. I'm using the first select in the default demo. Here is what I've done:

Tabbing to the first select. My mouse cursor is directly beneath the button (so the menu will expand under my cursor). I use STRG+ALT to open the menu. "Slow" is selected, "Medium" is highlighted as the mouse cursor is over that item. I type "fa" for faster -> the selected item changes to "faster". I hit ENTER and the selectmenu closes with "faster" selected. Seems to work as expected. 

Am I doing something wrong while reproducing the issue? Is it a browser specific issue? Please provide some more information.

Can you reproduce your issue with the default demo? Please try this default demo, too: http://jsfiddle.net/fnagel/GXtpC/

**Comment by fnagel** [comment]
Missed the "with large numbers of options" part so I've tested again with the typehead demo -- seems to work as expected too.

**Comment by sronsiek** [comment]
I do not believe this is browser specific though I cannot recall all the platforms that were tested. I can reproduce (in at least chromium 34.0.1847.116 and Firefox 24 ESR - both on Linux). I believe it is also present in IE8 and FF / Chrome on Windows.

I have forked yr demo to http://jsfiddle.net/3BuK2/1/

I just added a load of options beginning with 'B' to the drop-down example (I said you need many options).

Click on the 'dropdown' style selector (4th from top). Move the mouse over 'Slower' & leave it there (do not click). Now type 'b' on the keyboard. The selection should go to the first option beginning with 'b' or 'B'.

In fact is does. Now the background showing a subset of the options has scrolled - and the selection now jumps to whatever is under the mouse pointer (which has not moved). As I said originally - it seems there is an addition mouseover event fired.

**Comment by fnagel** [comment]
Ok, I'm now able to reproduce this issue (even in the typeahead.html demo).

**Comment by fnagel** [comment]
Agree, it seems a additional mouseover event is triggered.

> It seems like a surplus mouseover event is being fired after the keyup - **possibly only the first time.**

Agree, seems to happen on the first try only.

**Comment by fnagel** [comment]
I've pushed a proposed fix, please test and give feedback!

**Comment by sronsiek** [comment]
I presume pushed refers to jsfiddle. I have tested on http://jsfiddle.net/3BuK2/1/
and confirm this issue is fixed in the version currently running there.

Pls state version & any dependencies required to obtain the fix.

**Comment by fnagel** [comment]
Pushed means I've added a new commit here on GitHub. The demo fiddles (incl. your one) make use of the latest dev version (aka latets GitHub commit) by default.

No new dependencies -- just update your jquery.selectmenu.js file to the latest version: https://github.com/fnagel/jquery-ui/blob/selectmenu/ui/jquery.ui.selectmenu.js

**Comment by sronsiek** [comment]
This issue is fixed as per previous link (version ??).
The ticket can be closed.
