### ISSUE TITLE
Move focus on change?

### ISSUE THREAD

**Issue by tstar** [fnagel/jquery-ui#333]
I want to move the focus from selectmenu to another element on event "change". But it does not work, the focus stays on selectmenu element. This only works on the "close" event. Without using selectmenu there is no problem with moving focus on the event "change" from standard <select> element.

```
<select id="sm" onchange="$('#test').focus();">
    <option value="1">Test 1</option>
    <option value="2">Test 2</option>
</select>
<input type="text" id="test" />

<script>
    $('#sm').selectmenu();
</script>
```

How can I solve this problem?

Thank you.

**Comment by fnagel** [comment]
You should use the change callback event:

```
$('select').selectmenu({
    change: function(e, object){
        // change focus
    }
});
```

See the wiki for more info: https://github.com/fnagel/jquery-ui/wiki/Selectmenu

ProTip: Never manually change the focus. That's bad practice. Don't use inline JavaScript.

**Comment by tstar** [comment]
So too does not work, because the event "change" is triggered before the list is closed, and after the list is closed focus returned to the selectmenu element.

**Comment by fnagel** [comment]
Please post a demo fiddle (see #61) and describe what exactly do you want to achieve.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given.

**Comment by tstar** [comment]
Sorry for delay. In jQuery UI 1.11 selectmenu does not have this problem. Thank you.

**Comment by fnagel** [comment]
No problem, thanks the feedback!
