### ISSUE TITLE
Data Fetching issue in .NET

### ISSUE THREAD

**Issue by Two2code** [fnagel/jquery-ui#335]
Hi, I am using the version which supports jQuery 1.7.2 and having issues when it display value imported from database, it somehow has many "undefined" data in the list along with data that I have. any ideas please ?

Thanks

**Comment by fnagel** [comment]
I would need a basic example of what you try to do. A fiddle would be helpful, see #61

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given.
