### ISSUE TITLE
Does menuWidth accept value auto ?

### ISSUE THREAD

**Issue by sanjeev-chauhan** [fnagel/jquery-ui#338]
The native drop down behavior is If option text is longer than width of drop down then the menu stretches to show full option text without wrapping.
Can i achieve the same in this plugin without specifying a fixed menuWidth ?

**Comment by fnagel** [comment]
No, this is currently not possible in this version but in the new official selectmenu (see #140).

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given.
