### ISSUE TITLE
this._refreshValue is not a function

### ISSUE THREAD

**Issue by paperrobots** [fnagel/jquery-ui#34]
I have a few select fields that I'm showing/hiding based on another select fields value. It works fine in styling the shown selects the first change. After that it no longer works and I receive this error: "this._refreshValue is not a function". Any ideas?

**Comment by fnagel** [comment]
Please provide a working example zip (based upon the latest commit).

**Comment by paperrobots** [comment]
Ok styles aren't perfect but you get the idea. 

http://cl.ly/3G7T

If you select "Defense" from the drop down, another should apear. Then select "General Industry" and it should hide again. Select "Defense" once more and it will appear, but unstyled. Let me know if you need more then that.

**Comment by fnagel** [comment]
Please use the internal callbacks. I outlined the usage in this file (latest commit):
https://github.com/fnagel/jquery-ui/blob/cc6290c6f8cbec4a36556a0e7c7cb69b23ad2a6c/demos/selectmenu/dependency.html
