### ISSUE TITLE
How can I use placeholder

### ISSUE THREAD

**Issue by Hokwang** [fnagel/jquery-ui#343]
I want to input placeholder, like 'Choose...' or "Select a job".

But there's no way right now, right??

**Comment by fnagel** [comment]
Please take a look at this issue: #234 
Let me know if this helps.

**Comment by Hokwang** [comment]
I want a placeholder like https://github.com/silviomoreto/bootstrap-select/issues/121.

Finally I choose bootstrap-select plugin.
