### ISSUE TITLE
Change ui-select-menu display to inline-block rather than block

### ISSUE THREAD

**Issue by idevtech** [fnagel/jquery-ui#35]
It would be helpful to use inline-block rather than block for the ui-select-menu style because this allows it to be inline w/ other elements. Because of it's block style it was wrapping to the next line when adjacent to other elements. Changing the style to inline-block provided more flexibility.

Great job!

**Comment by fnagel** [comment]
Please see this issue:
https://github.com/fnagel/jquery-ui/issues#issue/20
