### ISSUE TITLE
z-index not updating when selectmenu used inside dialog

### ISSUE THREAD

**Issue by DeadBigRedDog** [fnagel/jquery-ui#36]
It appears the z-index is set to a static 1005 inside the css for the selectmenu.  This works at first but if you create a jQuery dialog and add a few input box's and a selectmenu then start clicking the input box's you will noticed that the z-index starts increasing for each click.  Six clicks later and the selectmenu dropdown no longer appears.

**Comment by fnagel** [comment]
Please see this issue as this problem has already been reported:
https://github.com/fnagel/jquery-ui/issues#issue/20

**Comment by DeadBigRedDog** [comment]
I don't think they are the same.  The issue I reported is very specific to using the selectMenu inside a jQuery dialog.

I solved the issue with a bit of a hack.
Inside the function _refreshPosition right before this line // set values
            this.list.css({
I do the following bit of code (I only care about this inside a dialog)
try { var z = 0; z = +this.newelement.parentsUntil('.ui-dialog').parent().css('z-index') + 1; z += 1; this.list.css('z-index', z); } catch (exc) { } //fix for dialog

**Comment by fnagel** [comment]
Sorry, Ive posted the wrong link. Check this one:
https://github.com/fnagel/jquery-ui/issues#issue/23

Is it possible you're using a outdated version of the widget? Its now using the position plugin and I committed a fix for the above mentioned issue #23

**Comment by DeadBigRedDog** [comment]
That would be it, I just pulled down the latest code with all the fixes.  Nicely fixed.  Did not realize the had that method to handle the zindex.
