### ISSUE TITLE
How to fix empty space inline-blocks with another dom elements? and ISSUE SCROLL

### ISSUE THREAD

**Issue by sirsk** [fnagel/jquery-ui#37]
for example:
http://gestionb.host.sk/img/Space.gif

I'm creating dinamically content there is someone tip to repopulate a selectmenu without ajax callback, before use selectmenu i rebuild the select with a global scope class array this way only one call to server is needed , and actually i don't know the method to refresh delete destroy the selectmenu and recreate the new selectmenu..
hopping some help.
My best regards
Diego.

**Comment by sirsk** [comment]
First sorry for my deprecated english.
Finally i found the solution to my first question, div widths and css float: left;
However also i founded a issue maybe a bug, the true is i don't know ..
i uploaded a video with the content of this issue..feel free to take a look !!
http://www.youtube.com/watch?v=Dq29zMsHZWk
My best regards 
Diego

**Comment by sirsk** [comment]
a better solution to my first question was.. apply this style at the class of normal inputs  
.inputsui{ margin: 0; padding: 0.49em; line-height: 0.8;} 
Now i use combobox by autocomplete ui and works perfect also i found a method to destroy them and refresh for a dynamic selects

<code>
destroy: function() {
  this.element
     .next("input")
     .next("button").remove();
  this.element
     .next("input").remove();
  this.element.show();
 $.Widget.prototype.destroy.apply(this);
}
</code>

**Comment by fnagel** [comment]
So this is the issue to the vids you posted here:https://github.com/fnagel/jquery-ui/issues#issue/30 right?

I must confess I do not really understand your issue. If this problem still persists plase provide a fully working example zip.

**Comment by sirsk** [comment]
Is right..!
The problem is solved.!
Today i download again the selectmenu.js and the theme css, every works fine..
really i dont now why the elements missing focus..i dont have the original files of the test anymore...

Simple & nice...^^
Thanks, Regards
Diego

**Comment by fnagel** [comment]
Ok, nice. So this issue is closed.
