### ISSUE TITLE
select menu flickers on FF

### ISSUE THREAD

**Issue by codefields** [fnagel/jquery-ui#39]
On a long dropdown (200 options) scrolling down to the bottom, select an option and then click again on the dropdown it produces a flicker. Just in firefox 3.6

**Comment by fnagel** [comment]
Could you please provide a working example zip as Im not able to reproduce the issue.

**Comment by codefields** [comment]
http://wavemate.org/

select the last country or any at the bottom of the list.
then if you select again you will see a weird flicker.
just in FF.
thank you!

**Comment by fnagel** [comment]
Please test the latest version of the plugin as you are using an outdated one.

**Comment by fnagel** [comment]
Closed as no feedback was given. Please re-open if necessary.

**Comment by juja** [comment]
This bug still appears in FF 3.6, even with the actual version of select-menu.

**Comment by fnagel** [comment]
This issue is confirmed in FF 3.6.x but not FF 4 Beta12 and all other major browser. 

I've tried to re-enable double positiong in function open and to re-order the open function. Both without success. Any idea what to do?

**Comment by fnagel** [comment]
This problem seems to be fixed within this issue: https://github.com/fnagel/jquery-ui/issues/#issue/84

Please test and report!

**Comment by juja** [comment]
It Works! Problem solved

Thanks for your time.

**Comment by fnagel** [comment]
Nice! Thanks for your fast feedback. So lets see if there are any other problems with changing from visibility to display...
