### ISSUE TITLE
Disabled options

### ISSUE THREAD

**Issue by torrentx** [fnagel/jquery-ui#40]
Not an issue, but a feature I needed.

I needed to add a feature so that a number of the options in the list could be disabled.  So these disabled items would still show up, but not be selectable.  

I made the following changes in my local copy.

I added the code block

<pre>
if ($(event.currentTarget).children().attr('disabled')) {
                            return false;
                        }
</pre>

at line 159 after if(self._safemouseup)

and again at line 311 at the beginning of the change event.

**Comment by fnagel** [comment]
Thanks for your contribution, its really appriciated!
This only helps the new option from not getting selected, right? 

Please take a look here as its partly the same issue.
https://github.com/fnagel/jquery-ui/issues#issue/18

**Comment by fnagel** [comment]
I will close this issue to reduce duplicate issues in the "open" list.

**Comment by fnagel** [comment]
This feature is now supported, please read info, test and report here: https://github.com/fnagel/jquery-ui/issues#issue/18
