### ISSUE TITLE
Fails when you have an empty select

### ISSUE THREAD

**Issue by mherbold** [fnagel/jquery-ui#46]
When you have an empty select, the widget fails and the original select is displayed as well as the selectmenu widget is displayed next to it.  Many web sites use dynamically generated select controls which could very well be empty.

**Comment by vdcprivate** [comment]
Go to line 323. You will find a line like this

//append status span to button
this.newelement.prepend('<span class="'+self.widgetBaseClass+'-status">'+ selectOptionData[this._selectedIndex()].text +'</span>');

change it with this one

this.newelement.prepend('<span class="' + self.widgetBaseClass + '-status">' + this._selectedIndex() + '</span>');

and you're on the way! 

@Felix: this should be committed in the main code :)

**Comment by mherbold** [comment]
That worked for me.  Thanks!

**Comment by fnagel** [comment]
As this was asked a few weeks ago I will implement this as soon as I've finished this issue: https://github.com/fnagel/jquery-ui/issues#issue/17
which needs some major refactoring.
I must confess I don't see the value of this feature but it seems I am wrong. What would be the best way to display an empty option / select? Perhaps the original behavior would be fitting: display an empty field by default and an empty option on click.

@vdecristofaro 
Your fix only helps to prevent the widget from crashing, right?

Please notice that this is a low priority request as there are a few bugs left and some more important feature to do. You are welcome to help me out here!

**Comment by mherbold** [comment]
The original web browser behavior would be just fine (and is probably what people would expect).  Dynamically generated web pages with selects being populated from a database, the select could very well be empty if there are no items in the database.  That's just one of many reasons I can think of to support empty selects.

**Comment by vdcprivate** [comment]
Felix,
you're right. My suggestion just prevent the browser from crashing. I am not so strong with javascript and jquery and I think I cant help too much with a better solution. :(

I also think this is a low priority issue expecially if there is a workaround that prevent the crash.

**Comment by fnagel** [comment]
Please test the latest commit and give feedback. Ive added empty options and optgroup support! Please note there is a open issue with empty optgroups: https://github.com/fnagel/jquery-ui/issues/129

**Comment by vdcprivate** [comment]
I can confirm that the latest commit is a solution for this issue.
Thanks

**Comment by fnagel** [comment]
Thanks for your feedback. Closed as solved.
