### ISSUE TITLE
Problem with jquery 1.4.4 and jquery ui 1.8.6

### ISSUE THREAD

**Issue by vdcprivate** [fnagel/jquery-ui#47]
I have downloaded the latest version of jquery and jquery ui version.
Now when I try to click on a selectmenu widget I get the following error on the console:

jquery-1.4.4.min.js:101
Uncaught TypeError: Object #<an Object> has no method 'replace'
k.matchesSelector        jquery-1.4.4.min.js:101
c.extend.filter                jquery-1.4.4.min.js:109
c.fn.extend.is                jquery-1.4.4.min.js:105
$.widget._create.optGroupName            jquery.ui.selectmenu.js:173
c.event.handle                                      jquery-1.4.4.min.js:63
c.event.add.h.handle.o

**Comment by fnagel** [comment]
I need to test this as soon as I've finished this issue: https://github.com/fnagel/jquery-ui/issues#issue/17
which needs some major refactoring. I could handle this more quickly if you provide a example zip.

**Comment by vdcprivate** [comment]
Actually I have tried to extract all to code I have to a single simple page. I did not experience the same error as in my application so I should investigate a bit more but anyway I am getting a different behaviour between using 

jquery 1.4.3 + jquery ui 1.8.5

against 

jquery 1.4.4 + jquery ui 1.8.6

You can try it with this page: http://bit.ly/fEHl8c

**Comment by fnagel** [comment]
I'm not able to reproduce your problem. Please provide some more information like browser and what exactly needs to be done to reproduce the issue.

Take a look here (latest version of the selectmenu widget with jQuery 1.4.4 and jQuery UI 1.8.6): http://jsbin.com/acufu3
