### ISSUE TITLE
handling of window resize doesn't work

### ISSUE THREAD

**Issue by saus** [fnagel/jquery-ui#52]
the window resize event does not call _refreshPosition because the proxy function is only created and not called.

edit: Can't figure out how to add labels, but this issue should probably have the "_selectmenu" and "bug" lebels

ui/jquery.ui.selectmenu.js - lines 215-217: (dec 24, 2010 version)
    $(window).bind("resize.selectmenu", function(){
    $.proxy(self._refreshPosition, this);
    });

should be:
    $(window).bind("resize.selectmenu", $.proxy(self._refreshPosition, this));

**Comment by fnagel** [comment]
Sorry, but I dont see the difference here. It should be no difference if I call the proxy function directly or within a anonymous function. Could anybody take a look too?

ps: Sorry, only admins could set labels afaik.

**Comment by saus** [comment]
$.proxy doesn't call the function, only creates it.
It's easy to test; just put a selectmenu inside a div with style="width: 500;margin: 0px auto;" and try resizing the window when the select is open.

**Comment by fnagel** [comment]
I see, thanks for your contribution. Will be pushed to GitHub soon.

**Comment by fnagel** [comment]
Follow up: https://github.com/fnagel/jquery-ui/pull/44

**Comment by fnagel** [comment]
Pushed to GutHub, please give feedback!
