### ISSUE TITLE
Not rendering in FF when served in Thickbox

### ISSUE THREAD

**Issue by Boshco** [fnagel/jquery-ui#55]
I've implemented selectmenu in a page that will be served using Thickbox. The selectmenu renders / functions perfectly when the page is viewed in a Firefox window (or tab).

However, the selectmenu does not render when that same page is served in a Thickbox window.

Firefox version 3.6.13
jQuery v1.4.4

Any help would be greatly appreciated.

**Comment by fnagel** [comment]
Please provide a fully working example zip with latest selectmenu.

**Comment by revsystems** [comment]
I would bet this is the same issue as here: https://github.com/fnagel/jquery-ui/issues#issue/58

**Comment by fnagel** [comment]
Yepp, that's right. Seems to be the same problem -- thanks for pointing that out.

**Comment by fnagel** [comment]
@Boshco
Please test if the solution provided here works for this problem too, so this issue could be closed.

https://github.com/fnagel/jquery-ui/issues#issue/58/comment/733745

**Comment by Booth** [comment]
I was having a similar issue where a hidden selectmenu would have an inline width of 0px. The Peek() plugin solution worked for me.

If you are dealing with hidden selectmenus, you will have to loop through them, get the width with Peek(), then do your selectmenu call:

var widthActual = '';
    $('select.selectmenu').each(function(){
        widthActual = $(this).peek("width");
        //jquery ui select menu
        $(this).selectmenu({style:'popup',width:widthActual});
    });

Feel free to let me know if that is going about the solution in a convoluted way.

**Comment by revsystems** [comment]
Did `$("select.selectmenu").peek("selectmenu", { style: 'popup' })` work for you? I think the selectmenu plugin handles setting the width automatically, as long as the original `<select>` is js-visible.

**Comment by Boshco** [comment]
Unfortunately, the peek() solution is not working for me. My situation is slightly different in that my selectmenu is not in a hidden div on the same page. It is in a separate page with a form that is served in a Thickbox window. I've put the call to the peek.js file in both the parent page and the form page, but I did not have any success -- the select menu is still only 1pixel wide. Unfortunately, I can't send a code example because the project is a proprietary dashboard for a client. Sigh. (If I can get the okay to produce a non branded version, how do I submit code for review?) Many, many thanks for all of your suggestions.

**Comment by fnagel** [comment]
I'm sorry the workaround did not work for you. Easiest way to submit code examples is to use this: https://github.com/fnagel/jquery-ui/issues#issue/61

**Comment by fnagel** [comment]
Are you able to post some example code or can I close this issue?
