### ISSUE TITLE
selectmenu typeahead should allow multiple characters

### ISSUE THREAD

**Issue by spacedevin** [fnagel/jquery-ui#56]
The default functionality on a selectmenu element in OSX is to find "better" options if more than one key is pressed after one another. Currently ui.selectmenu is cycling through all the available options based on a single character.

**Comment by spacedevin** [comment]
Commited. https://github.com/fnagel/jquery-ui/issues/#issue/57

**Comment by fnagel** [comment]
Closed as duplicate.
