### ISSUE TITLE
Clicking empty select throws script exception

### ISSUE THREAD

**Issue by rolek** [fnagel/jquery-ui#59]
When the select is empty, it is styled correctly, but throws exception when clicked:

Error: this.list.addClass(self.widgetBaseClass + "-open").attr("aria-hidden", false).find("li:not(." + self.widgetBaseClass + "-group):eq(" + this._selectedIndex() + ") a")[0] is undefined

**Comment by fnagel** [comment]
Please see this issue: https://github.com/fnagel/jquery-ui/issues#issue/46

Closed as thsis is a duplicate.
