### ISSUE TITLE
Keyboard control

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#6]
Its not possible to use arrow keys, page up, and page down (while home and end does work) at the moment after open the list with space.Additional there is no visual focus set.

The var newIndex is NaN in function _moveFocus. This affects all browsers. 

Thanks to Andreas for reporting this issue. http://github.com/fnagel/jquery-ui/issues#issue/5

**Comment by adoerler** [comment]
I'm not sure if it's usefull, but you could check the code of jquery-ui-autocomplete (http://jqueryui.com/demos/autocomplete/default.html) where the keyboard is working.

**Comment by fnagel** [comment]
Thanks for the link but I already familiar with keyboard control in jQuery. The problem is Im not the initial developer of this widget and Im not quite in the internal functionality. This problem needs some further investigation and perhaps some remanufacturing.

**Comment by fnagel** [comment]
Removed support of up and down arrow keys as these throw errors in all browsers. This needs further investigation.

**Comment by phazei** [comment]
There are a couple other keyboard issues.
Alt+up/down should open the menu, it does not, that is standard functionality.
Space does open the menu, it should not, not standard.

Also, it seems to steal all keyboard control when focused, at least in FF 3.6.8.  If it's in focus, and it hit F5 to refresh page, nothing happens, same thing for Ctrl+w, and tapping Alt to get to the browser menu bar.

**Comment by fnagel** [comment]
You're right, these are problems too. I think we could use the auto-complete specification as a plan what to implement: http://www.w3.org/TR/2009/WD-wai-aria-practices-20090224/#autocomplete

I fixed the blocked keyboard issue, thanks again. Your help is really appreciated.

**Comment by phazei** [comment]
I looked at that, and it says open the entire box on any arrow.  I think it would be better to stick with recreating the default functionality.  I wouldn't want the box to open entirely on just arrow, I'd only want to move through the choices.  There should also be a configuration option to loop around or not.  Currently it loops on up, but not down.  Home and end would to select the first and last items would also be good.

**Comment by bluefox** [comment]
I've downloaded the latest code and modified the _moveFocus function to work correctly on up/down/left/right/home/end

_moveFocus: function(amt){
        var newIndex = -1;
        if(!isNaN(amt)){
            var currIndex = parseInt(this._focusedOptionLi().data('index') || 0, 10);
            newIndex = currIndex + amt;
        }
        else { newIndex = parseInt(this._optionLis.filter(amt).data('index'), 10); }

```
    if(newIndex < 0){ newIndex = 0; }
    if(newIndex > this._optionLis.size()-1){
        newIndex =  this._optionLis.size()-1;
    }

    this._optionLis.eq(newIndex).find('a:eq(0)').focus();
},
```

NOTE: The focus part is copied from _typeAhead, as I'm not sure if anything else is required. I've also removed all setting of aria since the _typeAhead doesn't seem to set them.

NOTE2: I'm also wondering what's the use of _moveSelection function, and all the keydown binding under this.newelement. During my testing, I've yet to see the keydown events being triggered, perhaps it can be safely removed?

**Comment by fnagel** [comment]
@bluefox
Thanks for your support. 
NOTE: These work nice afaics.
NOTE2: No, these are used when the menu is not opened but using up/down arrow while focus the "fake" select.

@phazei
I agree, the widget should work like a native select. The default functionality is restored as it simply works again (see above). 
I fixed the issue when pressing ALT or F5 while focusing the "fake" select element.

Your fixes will be commited soon!
