### ISSUE TITLE
Call for real world examples!

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#60]
Please post some real world examples. They will be added in the Wiki as demos.

Thanks and happy posting!

**Comment by fnagel** [comment]
http://www.broadbandmap.gov/rank
Thanks to rworth, see http://twitter.com/#!/rworth/statuses/38360818181603328

**Comment by CHWiseJS** [comment]
Not exactly a real world example,
but please see: http://www.wisejs.com/wisejs/products/demo/VisualizeUIE.aspx

in the real world, in the second half 2011.

**Comment by fnagel** [comment]
Clean up and push!

@CHWiseJS 
Any news on the real world example?

**Comment by CHWiseJS** [comment]
Hi,
I apologize for not answer before.
I don't have no real case to be shown in the demo.
The plugin will be used in projects: TMS and WMS.
They are confidential applications of customer. I can't put on demo.
regards,
CHW

**Comment by mvanderw** [comment]
http://holocron.so/db

Just a note: I'm currently actively developing here, so things will likely change/break rapidly. In addition, I'm using a fluid width layout here so I'm planning on tweaking the source here and there to allow for changing window widths (probably boils down to recalculating the menu width- skimming through the source I think the width is calculated on init() and then never changes).

The scrollbar issue I mentioned in #147 was "something" in my form css. This is a side-project of mine and I've previously been playing with styling the default select; something there boogered the scrollbar. I'm not curious enough to properly investigate that though. =)

Thanks again for a fantastic plugin. So far it's been working beautifully and its been very easy to integrate & adapt. =)

**Comment by fnagel** [comment]
push!
