### ISSUE TITLE
Support for disabled optgroups?

### ISSUE THREAD

**Issue by ghost** [fnagel/jquery-ui#62]
Hi,

One of the little known features of `<select>` elements is disabling an optgroup. This should effectively disable all options in the optgroup. I looked through the source but couldn't find anything that would do this.

Will support be added eventually? I imagine this is low priority...

**Comment by fnagel** [comment]
This could be a nice feature so I will see what can be done when I work on the enable / disable single options, see issue18
https://github.com/fnagel/jquery-ui/issues#issue/18

**Comment by fnagel** [comment]
Is this feature supported by the original select tag?

**Comment by revsystems** [comment]
In my tests on windows, yes.

**Comment by fnagel** [comment]
This feature is now supported, please read info, test and report here: https://github.com/fnagel/jquery-ui/issues#issue/18
