### ISSUE TITLE
_refreshPosition problem

### ISSUE THREAD

**Issue by mherbold** [fnagel/jquery-ui#63]
In _refreshPosition if the menu is determined to collide with the bottom of the browser window then the code does menuTop -= listHeight... and unfortunately it does no checking to see if the resulting position is negative which puts the topmost items outside of the browser window and inaccessible.  To fix this, add this:

menuTop = Math.max(0, menuTop);

Right before the line with the // set values comment.  This will prevent selectmenu from ever putting the top of the select menu outside of the browser window.

**Comment by fnagel** [comment]
Please check the latest commit as it seems youre using an outdated version of the widget. Latest version uses the jQuery UI position plugin.
