### ISSUE TITLE
validation and selectmenu

### ISSUE THREAD

**Issue by ackzell** [fnagel/jquery-ui#65]
great work on the plugin!

I am trying to use this other one plugin which validates the form alongside the selectmenu plugin.

http://www.position-absolute.com/articles/jquery-form-validator-because-form-validation-is-a-mess/

I'm trying to make the <select> elements required, and do so by creating the element the way this validation plugin needs it. It works because before applying the selectmenu everything goes well...

my problem is that when I use the selectmenu plugin on  &lt;select&gt; elements validation stops working on those elements

what can I do?

**Comment by fnagel** [comment]
This could be a problem because the original selects are hidden. This needs further investigation in the functionality of the validation plugin. Im pretty busy right now so please provide a example (perhaps at jsfiddle? or) as a zip.

**Comment by ackzell** [comment]
Thank you very much.
I've been busy as well on some other parts of the project, but I will make that zip file and post it as soon as possible. thanks!

**Comment by ackzell** [comment]
I'm not sure how to upload .zip files here, so I'm providing a link to download it from somewhere else... <a href="http://www.mediafire.com/?a9cfl4p55p6wif5">here</a>

This is actually a project that involves the Smarty engine but I managed to remove all the complexity of it...

and so, the thing is as I said before, both validation plugin and the selectMenu plugin aren't getting along.... 

thanks in advance!

**Comment by fnagel** [comment]
This is not forgotten but Im very busy right now and not sure when Im able to take a look on this. Please understand that this is a very specific problem which is therefore low priority. I have only a certain amount of spare time to support dev of selectmenu and will allocate it the best I can.

**Comment by ackzell** [comment]
I completely understand, do not worry... I know what it is to be busy....

**Comment by asad-c** [comment]
The following fixed this issue for me:

```
$("#SelectList").selectmenu({
    change: function (e) {
        $("#Form").validate().element("#SelectList");
    }
});
```

**Comment by ackzell** [comment]
all right!
I'll try that as soon as I can, thanks!

**Comment by ackzell** [comment]
@aichaudhry 
thank you for answering.
I have a question though...

Is this code using the validation plugin I described on the question?
If so, the code is not really working for me :(

thank you again

**Comment by asad-c** [comment]
Sorry, my mistake, I was having the exact same problem as you, but with a different validation plugin:
http://bassistance.de/jquery-plugins/jquery-plugin-validation/

**Comment by ackzell** [comment]
Thanks, I just tried it really quick... but it might help if I adapt it to the other one plugin I need to use...

I'm not sure if I can do something similar, but I'll try anyways

**Comment by fnagel** [comment]
Closed. Please reopen if needed.
