### ISSUE TITLE
Problem with the new refresh functionallity.

### ISSUE THREAD

**Issue by mad-doctor** [fnagel/jquery-ui#67]
1. Call .selectmenu() on empty select element (<select></select>)
2. Dynamically add options including one that has to be selected by default (<option selected="selected">default option</option>
3. Call selectmenu() to refresh the content - the selected option is the first option, not the one with the selected attribute.

Tested on Firefox 3.6 so far. I can provide a working demo tomorrow, if needed.

**Comment by fnagel** [comment]
Back from holidays and still pretty busy. I will check this asap, but it would be helpful if you could provide a demo. You could use: http://jsfiddle.net/fnagel/hsn95/5/

**Comment by mad-doctor** [comment]
I've done a more extensive test and I have to say that it was my fault :) The default fields were improperly entered in the database and that made me think that ui.selectmenu does not respect option's "selected" attribute. Everything is working perfectly now, so we can close this issue.

**Comment by fnagel** [comment]
Thanks for your feedback. Issue closed. Please re-open if necessary.
