### ISSUE TITLE
Not working formater.

### ISSUE THREAD

**Issue by paranormal** [fnagel/jquery-ui#68]
In default examples http://github.com/fnagel/jquery-ui/zipball/selectmenu
and http://jsfiddle.net/paranormal/vrHbA/ I have not work format function.

I try find like original select tag.
Click to select, press key and select element start with this key.

**Comment by fnagel** [comment]
The address formatting is done by using regEx. Please take a look at the default.html file and the "Same with option text formatting" demo. You are missing the correctly formatted text within the options.

**Comment by paranormal** [comment]
I copy addressFormatting from default.html.
I use "dropdown" Style in default.html

1) I click to select a speed:
2) I press f

And nothing

On http://wiki.jqueryui.com/w/page/12138056/Selectmenu this operation works.

**Comment by fnagel** [comment]
Your option HTML is wrong / misses format. Take a look at the demo. The demo is outdated and it has correct HTML formatting within the option.

**Comment by paranormal** [comment]
AAA!!!
I have this problem, because I use vimperator.
Without vimperator all work good.
Thx.

**Comment by fnagel** [comment]
Closed as solved.
