### ISSUE TITLE
Whilst trying to implement selectmenu in an existing application

### ISSUE THREAD

**Issue by redmanscave** [fnagel/jquery-ui#69]
OS: Windows / ASP.NET MVC
jQuery/UI: 1.4.4 / 1.8.6 

I have a form with 2 standard html select elements (the first select list is populated when the form loads and the other 2 are populated upon selection of the previous list (ie cascade down) when a select list changes the lower selects are disable (with first option set to 'loading...') they are then populated based on the previous select where empty selects are set with a one option "(select)". The data for the cascading selects is received via jquery ajax calls where the items are add in this way:

$("#MySelect").get(0).options.length = 0;
$("#MySelect").get(0).options[0] = new Option('(loading...)', '');

The items are populated by getting the data and adding constructed 'option' tags and added to the select, something like this:

var selectOptions = '<option value="">(select)</option>';
for (var i = 0; i < Data.Item.length; i++) 
{
selectOptions += '<option value="' + Data.Item[i].Value + '">' + Data.Item[i].Text + '</option>'; 
}
$("#MySelect").get(0).options.length = 0;
$('#MySelect').append(selectOptions);
$('#MySelect').attr('disabled', '');

The selectmenu plugin, I assume replaces the markup and in my example would expect my code to not work, which it doesnt (and dont know of a better way to add items that wold be compatible with the plugin). The validation plugin, does seem to work on initial check which is good... and have these ideas as feedback:

Could the plugin be extended/updated with;

1) have the option style='default', that would render the select unchanged (ie to test normal select functionality without the style)
2) functions to clear, add, remove, disable, select, items (possibly already exists) that would perform these to either the 'default' select or to the rendered select as configured in the options.
3) Default the item css to not wrap (long items seemt to wrap which does look odd)
4) What would speed up development of this (ie donation to implement these things specifically if they are good ideas?)

HTH

**Comment by fnagel** [comment]
Hey redmanscave, 

concerning your questions:
1) this is not possible as the widget imitates the original HTML tag select and option with divs and spans to have a consistent look in all browsers
2) Please see this post (and following): https://github.com/fnagel/jquery-ui/issues/closed#issue/17/comment/609583
In short: you need to add/ delete / modifiy the options of the original select and update the widget via:
      $("#MySelect").selectmenu()
3) Please specify this question as I do not understand what exactly you're looking for
4) This widget is maintained in my spare time and I try to allocate time the best I can. If youre willing to donate I will prefer your issue and make sure I work on the request asap.

**Comment by redmanscave** [comment]
Hi,

Thanks for the quick response...

Yes, calling $("#MySelect").selectmenu(); after modifying the select listr works just fine, thanks for that. :-)

What I did notice was that although the select gets disabled via jquery, ie disabled="diabled" then enabled by setting disabled="", the rendered selectmenu remains disabled.

The only other thing i needed to do was set the width otherwise the content for an item wraps if its too long (I havent looked at the css yet to see where to adjust that)

Thanks again.

**Comment by fnagel** [comment]
Hey, 

take a look at the (newly updated) disable_enable demo file. This should explain you what can be done and show known problems. Take a look here, too:
https://github.com/fnagel/jquery-ui/issues#issue/18

The main reason Im using (and developing) this widget: linebreak for long option text. But Im still not sure if I get you right. Please provide a demo for more help! Take a look here, how to do this easy:
https://github.com/fnagel/jquery-ui/issues#issue/61
