### ISSUE TITLE
YUI compressor throwing errors when compressing selectmenu

### ISSUE THREAD

**Issue by tanem** [fnagel/jquery-ui#74]
Hi there,

We've just noticed YUI compressor (v2.4.2) throws a few errors when trying to compress the current/latest version of selectmenu ("missing formal parameter").

Looks like it's related to the function starting on line 432:

```
function focusOptSeq(elem, ind, char) {
  focusFound = true;
  $(elem).trigger(eventType);
  typeof(self._prevChar) == 'undefined' ? self._prevChar = [char] :  self._prevChar[self._prevChar.length] = char;
};
```

Is it possible to alter the name of the "char" parameter to something else?  We've tried that on our local selectmenu copy and YUI compressor is ok with that.

Is this because char started out as a reserved word in js, but is reserved no longer?  Wondering if this is actually something that needs to change in the YUI compressor, as opposed to the selectmenu js...

Thanks,
- Tane

**Comment by fnagel** [comment]
I see no problem renaming the var. I will test this soon, thanks for reporting!

**Comment by fnagel** [comment]
Fixed and pushed to GitHub. Tested with http://compressorrater.thruhere.net/

Thanks for your contribution!

**Comment by tanem** [comment]
No probs - thanks for the prompt fix :)
