### ISSUE TITLE
Wrong resize handler

### ISSUE THREAD

**Issue by juzna** [fnagel/jquery-ui#75]
When I was reading source code of selectmenu, I have found a strange thing. In window-resize event, the handler is just creating a proxy but not calling it actually. Thus, when resizing the window having menu opened, it's not moved.

To fix this, just edit one line (and then it's actually working)

**Comment by juzna** [comment]
Sorry, the diff is formated badly, it should be:

```
@@ -228,7 +228,7 @@ $.widget("ui.selectmenu", {               
                // needed when window is resized
                $(window).bind("resize.selectmenu", function() {
-                       $.proxy(self._refreshPosition, this);
+                       self._refreshPosition();
                });
        },
```

**Comment by fnagel** [comment]
I'm already aware of this problem. We're working on it. Take a look at the link below.

This issue is related with: 
https://github.com/fnagel/jquery-ui/issues/52

Please test latest commit and give feedback on the issue above. Closed as duplicate.
