### ISSUE TITLE
_refreshPosition called twice in open()

### ISSUE THREAD

**Issue by juzna** [fnagel/jquery-ui#76]
In selectmenu's method open, there are two calls to _refreshPosition(). Is there special purpose for that? For me the first one seems redundant and everything I've tried is working event without it.

(This is kinda not a bug, but just tidying the code :)

**Comment by fnagel** [comment]
I will take a look soon, but I remember something about placing the widget at the very bottom of a page.

**Comment by fnagel** [comment]
I agree, it seems to be useless. I pushed these changes to GitHub. 

Please test and give feedback!

**Comment by fnagel** [comment]
Please give feedback!

**Comment by fnagel** [comment]
Any comments on this?

**Comment by odonnell-pb** [comment]
Hi, I have just downloaded and tested in the application I am developing. 

Prior to today, in IE 8 (and compatibility mode) the dropdown caused the screen to scroll and flash. It now works without the disconcerting flashing and scrolling. Thanks for the fix :)

**Comment by fnagel** [comment]
Sorry about the long waiting time, but I had an surgery and was not able to work on the selectmenu widget the last few weeks. 

Thanks for you contribution! Hard to get feedback on such issues.
Ive deleted this line. Closed as resolved!
