### ISSUE TITLE
Enhancement: Extending selectmenu

### ISSUE THREAD

**Issue by juzna** [fnagel/jquery-ui#77]
I did some refactoring to basic Selectmenu widget, so that it can be easily extended to show e.g. tables instead of a list.

Refactored version can be found at: http://helemik.cz/juzna/opensource/js/jquery-ui/jquery.ui.selectmenu.js

Sample of extension which uses tables: http://helemik.cz/juzna/opensource/js/jquery-ui/jquery.ui.selectmenu2.js

Are you interested in merging it into your code? (I can provide batch of small commits, each for one refactored feature/method)

**Comment by fnagel** [comment]
I will take a look a this soon, pretty busy atm. Thanks for your contribution!

**Comment by fnagel** [comment]
Closed. Please see here: https://github.com/fnagel/jquery-ui/issues#issue/81
