### ISSUE TITLE
Selectmenu popup menu width too large and flows off the screen

### ISSUE THREAD

**Issue by tauren** [fnagel/jquery-ui#79]
I've found a scenario where the popup menu gets sized incorrectly. I've created a demo of this in my fork. Here's the commit that contains the demo page:
https://github.com/tauren/jquery-ui/commit/b1cb98edb78e89c31f3c376f7ae225eb00190949

Basically, if a select has a width of 100% and it is inside of a sized container, the popup menu flows off the left side of the screen. I haven't completely tested when this happens and when it doesn't.

The solution I've been using is to set the selectmenu width parameter to the width of the select:

```
$('select').each(function() {
    var $this = $(this);
    $this.selectmenu({
        style:'popup',
        width: $this.width()
    });
});
```

**Comment by fnagel** [comment]
This could be related to this problem: https://github.com/fnagel/jquery-ui/issues#issue/86

**Comment by tauren** [comment]
That could certainly be a related issue. I've posted a live demo so you can see the problem in action:
http://tauren.github.com/jquery-ui/demos/selectmenu/minmenuwidth.html

**Comment by fnagel** [comment]
This seems to be related too: https://github.com/fnagel/jquery-ui/issues/87

**Comment by fnagel** [comment]
Would you please test if this error still occurs when using this version: https://github.com/fnagel/jquery-ui/zipball/selectmenu_v1.1.0 or latest version

Please take a look here how to post a demo: https://github.com/fnagel/jquery-ui/issues/61

**Comment by fnagel** [comment]
Please give feedback!

**Comment by tauren** [comment]
I just updated my fork from upstream and tested my positioning.html test page. After updating the jquery version, the demo page works properly. The addition of minMenuWidth is working correctly and the problem with the position of the popup being way too far to the left seems to be solved as well.  Thanks!

**Comment by fnagel** [comment]
So this issue could be closed. Please reopen if needed!
