### ISSUE TITLE
Better image support

### ISSUE THREAD

**Issue by tauren** [fnagel/jquery-ui#8]
This meets 95% of my needs in it's current form, great work!

The main problem I have is that I need to display images that I cannot specify in advance in my CSS file. For instance, I need to show a drop down list of people, with their profile photo next to their name. Currently, I'm displaying their Gravatar (http://gravatar.com), so I need to display an image like the following:

<img src="http://www.gravatar.com/avatar/ba0c49b9807f496ba4d567700b0cf2fe?d=monsterid&r=g&s=25">

Is this possible in the current version? If so how? If not, it would be a valuable feature.

**Comment by tauren** [comment]
I just made some enhancements in my fork. It is more of a hack than anything, I'm sure there are much better ways to do this. But I needed to get something working for a project. Maybe it will help, or at lease be useful to someone else.

Basically, if your option tag has a title attribute, and you have the icons option enabled, then the value of the option title attribute will be used as the background image.

I've added an example of using it to the selectmenu demo page:
http://github.com/tauren/jquery-ui/blob/selectmenu/demos/selectmenu/default.html

Here is the updated source:
http://github.com/tauren/jquery-ui/blob/selectmenu/ui/jquery.ui.selectmenu.js

**Comment by fnagel** [comment]
This sounds like a valuable feature. I thought of something more semantic here. What about a configuration array which can be passed to the widget? 
What is allowed within a option tag? We arent allowed to set a image tag directly, arent we?

**Comment by tauren** [comment]
The point is that I'd like the HTML to contain a URL, not the Javascript code. I'd like to be able to reuse the same JS code, but have thousands of different avatar URLs to display. For this same reason, I don't want to configure different CSS code like the widget requires now. So I'm unsure how passing a configuration array to the widget will help. Unless I'm misunderstanding your intent.

There aren't a lot of attributes available on the option tag.  That's why I used the title attribute. See here for a list of them:
http://www.w3schools.com/TAGS/tag_option.asp

Of course, I'm open to other ideas, as what I did feels like a hack. Can you explain what you have in mind in more detail?

**Comment by fnagel** [comment]
I'm getting your point and agree that an array passed in is not suitable. 

We can't add an image tag into an option tag as its invalid. An attribute is not acceptable to me as they have strict usage pattern and I don't like to break these. What about a style attr with background property. We could hide the background image as long no JS is active via background position.

What do you think?

**Comment by tauren** [comment]
Yes, do not put an image tag inside the option. What is wrong with using an attribute? What do you mean by "strict usage pattern"?  I agree that it isn't optimal to use the title attribute, but it is a valid attribute and could be used. Not very accessible though, since a screen reader would look for the title and not be happy with reading a URL...

I suppose style could be used with a background image. I had played with doing that, but didn't have the time to get it working. Using an attribute was simplest and most straightforward.

Another option is to use an HTML5 data- attribute, where we could define whatever we want, such as data-image, etc. http://ejohn.org/blog/html-5-data-attributes/

**Comment by fnagel** [comment]
I modified the script to work with any attribute tag as well with CSS background. Check out the new demo and wiki!

**Comment by tauren** [comment]
Very nice. Just tried it out and it works well. Will integrate it into my app and see if I run into any troubles. Made some fixes to default.html demo so that it works now too and sent you a pull request.

**Comment by fnagel** [comment]
Im glad you like it. I will take a look at your pull request soon.

So Ive got only 10 other issues to do :-)
