### ISSUE TITLE
IE6: scrollbar problems in menu

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#80]
Shows two scrollbar when opening menu.

**Comment by bluefox** [comment]
I believe this problem is caused by bgiframe, the iframe attached inside UL is causing IE6 to display scrollbars. We have a fix that was able to resolve this issue by warpping UL inside a DIV, then use the DIV to position the menu (that's when bgiframe is called to add the iframe). However, our code has lots of changes compare to the trunk version to suit our own needs so I'm not sure if we'll be able to provide a fix...

**Comment by fnagel** [comment]
Sorry, what bgiframe do you mean? We do not use a iframe within selectmenu. Did you mean bgimage?

**Comment by bluefox** [comment]
The selectmenu plugin doesn't use bgiframe directly, but bgiframe is called by $.position in IE6 to make sure the positioned items appear correctly without having to worry about underlying select element to bleed through. The way bgiframe is being added to the positioned element is causing IE6 to incorrectly displaying the scrollbar.

**Comment by fnagel** [comment]
Ahh ok, thanks for pointing that out. So this could be considered as a jQuery UI position problem or is itrelated to selectmenu?
Perhaps this problem is fixed when updating to the newer version of jQuery UI. Did you searched for a bug ticket at jQuery?

**Comment by bluefox** [comment]
I don't think this is a jQuery UI bug, to be more specific, it is because bigframe added a DIV inside the UL (the positioned element). Which renders the html invalid according to http://www.w3.org/TR/html401/struct/lists.html#h-10.2.

**Comment by fnagel** [comment]
Sounds reasonable. Any idea what to do against it?

**Comment by bluefox** [comment]
What I did in our patched version of selectmenu is to warp around the original positioned UL inside a DIV, then position the DIV instead. Which seems to work out fine for us, though I'm not sure if that's the best way to go about fixing the problem.

**Comment by fnagel** [comment]
There is already a wrapper functioanlity to use CSS scope. It wraps the newelement and the list in a div. Ive tried modifying the wrapperElement option with no success. Is there a example of how you did this?

**Comment by bluefox** [comment]
What we did was wrapping the ul element inside a div like so

```
this.listdiv = $('<div class="' + self.widgetBaseClass + '-menu"/>').append(this.list).appendTo('body');
```

And then it becomes the base element that needs to be modified to add the ui-selectmenu-open class when the menu is opened. (Also listdiv.remove is done on destory)

Then we simply change this.list.position with this.listdiv.position and it seems to work properly with bgiframe.

**Comment by fnagel** [comment]
Am I wrong or will this require additional changes and even some to the CSS? I was not able to get this running in IE6 by changing your above suggestions. Can you give some more hints or update your fork?

**Comment by fnagel** [comment]
Forget abut my last post. I think ive managed a working version.

Please test my latest commit and give feedback.

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by bluefox** [comment]
Tried the demos/selectmenu/disable_enable.html under IE6 and it seems to be working fine!

**Comment by fnagel** [comment]
Nice! Thanks your feedback. Closed as solved.

**Comment by betalb** [comment]
Hmm I seems that wrapper element "&lt;div&gt;" makes selectmenu a block-level element but it should be inline-block

**Comment by fnagel** [comment]
Would you mind to open a new issue for this problem? Perhaps with a demo fiddle? (see #61)
