### ISSUE TITLE
Bug with empty select

### ISSUE THREAD

**Issue by tauren** [fnagel/jquery-ui#82]
I'm getting an error reported when a select is empty. Thing still seem to work, but an error is shown in the console.

Uncaught TypeError: Cannot read property 'top' of null

It looks like it is happening in refreshPosition at this line:

```
  var _offset = "0 -" + (selected.outerHeight() + selected.offset().top - this.list.offset().top);
```

Here's a little more context:

```
_refreshPosition: function() {
    var o = this.options;
    // if its a native pop-up we need to calculate the position of the selected li
    if (o.style == "popup" && !o.positionOptions.offset) {
        var selected = this._selectedOptionLi();
        var _offset = "0 -" + (selected.outerHeight() + selected.offset().top - this.list.offset().top);
   }
```

I'll try to fix this when I have some time, but it is probably something simple you could fix quickly.

Tauren

**Comment by fnagel** [comment]
Please take a look here: https://github.com/fnagel/jquery-ui/issues#issue/46

**Comment by tauren** [comment]
Ah, I missed that one. But I'm not having troubles with browsers crashing. I'll need to see if it is the same bug or a different bug.

**Comment by mad-doctor** [comment]
I've also noticed an error when the select is empty. Clicking on an empty select gives error in Firefox and possibly other browsers - it tries to add some classes to non existent option elements. Here is a link - just click on the empty selectmenu with firebug console open - http://jsfiddle.net/hsn95/41/

Just tested it in Opera 11.01 - same error.

**Comment by fnagel** [comment]
Please test the latest commit and give feedback. Ive added empty options and optgroup support! Please note there is a open issue with empty optgroups: https://github.com/fnagel/jquery-ui/issues/129

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by mad-doctor** [comment]
I've been busy lately, but I'll try to test the latest commit on my order form and will report ASAP.

**Comment by fnagel** [comment]
@tauren
I would like to close this issue and release v1.2. Would you mind quick check if this problem is solved?

**Comment by tauren** [comment]
@fnagel: With the latest code in the selectmenu branch, I no longer get errors when a select is empty. This appears to be resolved. I'll close this issue. Thanks!
