### ISSUE TITLE
UTF-8 non-english symbols. Please provide better class regex for representators of <optgroup> tags

### ISSUE THREAD

**Issue by stanislaw** [fnagel/jquery-ui#83]
Hi.
If i selectmenu() on select with more than one ) optgroup tags, each having label with non-english symbols -- than it results in only one presentational <li ... role="presentation">.
Your /[^a-zA-Z0-9]/g is not enough.
Temporarily added my russian alphabet letters here )
Thank you.

**Comment by fnagel** [comment]
You're right, this is a problem. 

Do you no if its W3C conform to use non-english chars as a CSS class? The optgroup mechanism needs a rewrite if not.

What about to assign an id attr to the optgroup element if non English chars are used=

**Comment by stanislaw** [comment]
I don't know about w3c conformity )
I think some kind of rewrite needed anyway, because of doing this by such optgroup mechanism you mix content and structure.
Why not just form class names for optgroups by indexes of their original places inside <select></select>?

**Comment by stanislaw** [comment]
http://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

**Comment by fnagel** [comment]
Fixed in latest commit, thanks for your contribution!
