### ISSUE TITLE
Select Menu flickers on FF 3.6

### ISSUE THREAD

**Issue by juja** [fnagel/jquery-ui#85]
On a list with many items(dropdown style), when select the last one and re-open the menu there is a flicker.

Firefox 3.6 in GNU/Linux and Windows.

**Comment by fnagel** [comment]
Thanks for your contribution! 

Does this problem appears on a long dropdown (200 options), only? Please see: 
https://github.com/fnagel/jquery-ui/issues/unreads#issue/39

Closed as duplicate.
