### ISSUE TITLE
MenuWidth impacted by both a container with a percent width and hiding the element during create

### ISSUE THREAD

**Issue by Akkuma** [fnagel/jquery-ui#87]
A demo of this problem can be viewed here (saw in at least both Chrome and FF): http://jsfiddle.net/eJVwG/

If you set a % width on the select and set a % width on a container the menu is drastically off in size. Additionally, even when the container is 100% width the menu is still slightly too large.

The easiest solutions would be to do either:
- Don't hide the element until the end of init
- Show the element before the width calculation in init and then hide the element after (tested this and saw it worked)

**Comment by Akkuma** [comment]
Here is the quick fix: https://gist.github.com/874807

**Comment by fnagel** [comment]
Are these related? https://github.com/fnagel/jquery-ui/issues#issue/86 and https://github.com/fnagel/jquery-ui/issues#issue/79

**Comment by Akkuma** [comment]
There is a very high likelihood that these problems are related. I'm guessing those people didn't do as much testing and would have found that it is any % width and not only 100%.

**Comment by fnagel** [comment]
Would you please test if this error still occurs when using this version: https://github.com/fnagel/jquery-ui/zipball/selectmenu_v1.1.0 or latest version

**Comment by fnagel** [comment]
Please give feedback!

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if necessary.
