### ISSUE TITLE
Keyboard navigation, usability, & styling issues with disabled functionality

### ISSUE THREAD

**Issue by gcko** [fnagel/jquery-ui#89]
First I would like to say thank you for getting this functionality into selectmenu's. This is a good start, however there are a few issues that I have identified. These are all found within the disable_enable.html demo.

(1) Tab into a selectmenu, try to navigate down and up using the arrow keys. Note that keying up will loop you through the list, while keying down does not.

(2) Tab into a selctemenu, press and hold the down arrow key. note that it selects the next option but does not scroll the list (this is different from the behavior when you press and hold the up arrow key).

(3) Click a selectmenu so that the menu opens up. try to use the arrow keys to navigate. note that the following error is thrown in Firefox:

recIndex is not defined
[Break On This Error] if (newIndex === recIndex) { 

(4) on the disable option demo, disable the option. tab into the corresponding selectmenu. try to navigate past the disabled option. Note that you cannot.

(5) Disabled options receive hover states (they should not)

**Comment by gcko** [comment]
Please note that in the pull request I sent, The keyboard issues are handled correctly within the code

**Comment by gcko** [comment]
I accidentally closed this issue; is it possible for me to reopen this or should I just create a new one?

**Comment by fnagel** [comment]
Reopened and marked as v1.1 milestone as disable functionality should be a major feature for the first tagged version.

**Comment by fnagel** [comment]
First of all thanks for testing this an giving feedback! 

1) Fixed, please test latest commit and give feedback!

2) is related to 1), fixed

3) is solved, see: https://github.com/fnagel/jquery-ui/issues/99

4) Confirmed, needs further investigation.

5) I opened a new issue for this problem: https://github.com/fnagel/jquery-ui/issues/103

**Comment by fnagel** [comment]
Closed and opened new issue for 4)
https://github.com/fnagel/jquery-ui/issues/116
