### ISSUE TITLE
Issue with having dot(.) symbol in name and id attributes

### ISSUE THREAD

**Issue by leonate** [fnagel/jquery-ui#91]
When 'select' tag has symbol '.' in its name/id attribute selectmenu does not work (no entries are displayed).
For example having

<select name="group.id" class="dropdown" id="group.id" >
<option value="1" >Group A</option>
<option value="2" >Group B</option>
</select>
the select menu shows empty dropdown.
If I change group.id to groupId it works fine. Having dot ('.') in tag name or id is often important for many web frameworks for proper data binding of associated objects.

**Comment by fnagel** [comment]
This seems to be a jQuery selector engine related problem as . is used as a selector for CSS classes. So Im not quite sure if this is a selectmenu related problem. Please see here for more infos: http://docs.jquery.com/Frequently_Asked_Questions#How_do_I_select_an_element_by_an_ID_that_has_characters_used_in_CSS_notation.3F

Additionally using dots is not allowed according to W3C: http://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

Does the jQuery FAQ solves the problem for you?

**Comment by leonate** [comment]
Possibly you are right. Probably selectmenu plugin applies some operations which rely on 'id' attribute value of select tag and fails shortly because of JQuery issue with . symbol. It looks like there is no way to solve the problem except removing . from id..

**Comment by fnagel** [comment]
Problem is that jQuery will fail to search for your elements and therefor almost every jQuery script will fail. Perhaps you shoudl try mootools which does not work with sizzle selector engine and therefor does not rely on dots and #

I'm sorry for your but webstandards should be applied where ever possible to avoid problems like this.
