### ISSUE TITLE
Tabbing out of a select menu that has been opened via clicking doesn't record option

### ISSUE THREAD

**Issue by mjost5v** [fnagel/jquery-ui#98]
Steps to recreate:
1. Open a menu via clicking
2. Go down via the down enter
3. Press Tab to select option
4. Option isn't recorded as the selected option

I found that this issue could be resolved by giving the case $.ui.keyCode.TAB: the same code to execute as the case $.ui.keyCode.ENTER: and case $.ui.keyCode.SPACE: cases when transfering menu click to menu button (the binding occurs line ~170).

**Comment by fnagel** [comment]
Thanks for your contribution. I will take a look soon.

**Comment by fnagel** [comment]
Thanks for reporting! Issue is fixed, please reopen if necessary.
