### ISSUE TITLE
Error Arrowing Through List

### ISSUE THREAD

**Issue by i2amsam** [fnagel/jquery-ui#99]
I'm getting an error bringing up a list and then arrowing (up/down arrows) through the choices.   It doesn't change item and it throws an error.

I can replicate on the demo site
http://jsfiddle.net/hsn95/85/embedded/result/

In chrome on Windows I get the error:

recIndex is not defined on line 601 of selectmenu.js for this line:

   //Occurs when a full loop has been made
   if (newIndex === recIndex) { 
            return false; 
    }

**Comment by fnagel** [comment]
Thanks for your contribution. I will take a look soon.

**Comment by fnagel** [comment]
Thanks for reporting this issue. This problem is confirmed in FF4, too. 

As somebody sent me changes to this function which seems to work correctly, Im not quite sure if this if statement is still in use. Seems useless to me. Fixed and committed soon. Thanks!

**Comment by i2amsam** [comment]
Great!  Thanks!!
